### ISSUE TITLE
Dplyr crashes R 3.3.0 32-bit when using mutate or summarize when code should return an error

### ISSUE THREAD

**Issue by daltonhance** [hadley/dplyr#1835] opened 2016-05-18 18:11 UTC
I can confirm that this happens only with 3.3.0 32 bit. It does not occur with 64 bit 3.3.0 or with 32-bit 3.2.4. I am not able to confirm the exact circumstances under which it happens.

``` R
library(dplyr)

tst <- data.frame(
  grp = c(rep("A", 16), rep("B", 16), rep("C", 16)),
  x   = rnorm(16*3),
  y   = rnorm(16*3)
)

tst %>% 
  mutate(corr = cor(x, y, na.rm =  T))
```

Using the 64-bit 3.3.0, the second chuck of code correctly returns the helpful error:
`Error: unused argument (na.rm = TRUE)`.  Under 32-bit 3.3.0, R instead crashes.

**Comment by pkoki** [comment] 2016-05-24 13:34
Are you running R in RStudio by any chance? It seems that RStudio does not handle errors in dplyr correctly. 

I get the same error, but only when running RStudio IDE. It does not crash RGui but results in "Error: unused argument (na.rm = TRUE)", as expected.

Corrected version of your code:
```
library(dplyr)

tst <- data.frame(grp = c(rep("A", 16),
                          rep("B", 16),
                          rep("C", 16)
),
x = rnorm(48),
y = rnorm(48)
)

tst %>%
  mutate(corr = cor(x, y, na.rm = T))
```

Here is a second example with similar behavior for filter():
```
library(dplyr)
a <- data.frame(x = c(1, 2, 3), y = c("a", "b", "c"))
a %>% filter(w == 5)
```
Under Rstudio the R session terminates, under RGui it just returns an error, as expected.
This has been happening under the last few preview releases of RStudio IDE.

version info: 
RStudio Version 0.99.902
R: "R version 3.3.0 (2016-05-03)", "i386-w64-mingw32"
dplyr: Version: 0.4.3.9001, Built: R 3.3.0; i386-w64-mingw32; 2016-05-24 13:18:12 UTC; windows

**Comment by daltonhance** [comment] 2016-05-25 17:17
I am running RStudio Version 0.99.896. So I guess it's that particular
combination of R 3.3.0 32 bit and RStudio Version 0.99.896.


On Tue, May 24, 2016 at 6:34 AM, Peter Konings <notifications@github.com>
wrote:

> Are you running R in RStudio by any chance? It seems that RStudio does not
> handle errors in dplyr correctly.
>
> I get the same error, but only when running RStudio IDE. It does not crash
> RGui but results in "Error: unused argument (na.rm = TRUE)", as expected.
>
> Corrected version of your code:
>
> library(dplyr)
>
> tst <- data.frame(grp = c(rep("A", 16),
>                           rep("B", 16),
>                           rep("C", 16)
> ),
> x = rnorm(48),
> y = rnorm(48)
> )
>
> tst %>%
>   mutate(corr = cor(x, y, na.rm = T))
>
> Here is a second example with similar behavior for filter():
>
> library(dplyr)
> a <- data.frame(x = c(1, 2, 3), y = c("a", "b", "c"))
> a %>% filter(w == 5)
>
> Under Rstudio the R session terminates, under RGui it just returns an
> error, as expected.
> This has been happening under the last few preview releases of RStudio IDE.
>
> version info:
> RStudio Version 0.99.902
> R: "R version 3.3.0 (2016-05-03)", "i386-w64-mingw32"
> dplyr: Version: 0.4.3.9001, Built: R 3.3.0; i386-w64-mingw32; 2016-05-24
> 13:18:12 UTC; windows
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hadley/dplyr/issues/1835#issuecomment-221270354>
>



-- 
Dalton Hance, M.S.
(541) 231-9474

"That would be a good world, free and out-doors.
But the vast hungry spirit of the time
Cries to his chosen that there is nothing good
Except discovery, experiment and experience and discovery: To look
truth in the eyes,
To strip truth naked, let our dogs do our living for us
But man discover.
It is a fine ambition,
But the wrong tools. Science and mathematics
Run parallel to reality, they symbolize it, they squint at it,
They never touch it: consider what an explosion
Would rock the bones of men into little white fragments and unsky the world
If any mind for a moment touch truth."
-robinson jeffers
"The Silent Shepherds"

**Comment by hadley** [comment] 2016-05-26 13:30
@pkoki @daltonhance I delete the irrelevant stuff to make it easier to see the actual issue

But it's unlikely I'll have the time to fix given that it doesn't reproduce on my computer.

**Comment by pradeepthiyyagura** [comment] 2016-05-27 23:08
I agree with the bug.

Summarize does not work in the new 3.3 version

> R.version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          3.0                         
year           2016                        
month          05                          
day            03                          
svn rev        70573                       
language       R                           
version.string R version 3.3.0 (2016-05-03)
nickname       Supposedly Educational      
> iris %>% group_by(Species) %>% summarize(avg =mean(Sepal.Width)) %>% arrange(avg)
       avg
1 3.057333

> R.version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          1.2                         
year           2014                        
month          10                          
day            31                          
svn rev        66913                       
language       R                           
version.string R version 3.1.2 (2014-10-31)
nickname       Pumpkin Helmet              
> iris %>% group_by(Species) %>% summarize(avg =mean(Sepal.Width)) %>% arrange(avg)
Source: local data frame [3 x 2]

     Species   avg
      (fctr) (dbl)
1 versicolor 2.770
2  virginica 2.974
3     setosa 3.428

**Comment by kevinushey** [comment] 2016-06-02 17:30
I was initially able to reproduce this crash on 32bit R, but it went away after reinstalling both Rcpp and dplyr.

**Comment by ShuguangSun** [comment] 2016-06-08 15:28
`cor(1,3, na.rm=T)` itself produce the error

> Error in cor(1, 3, na.rm = T) : unused argument (na.rm = T)

**Comment by ShuguangSun** [comment] 2016-06-08 15:39
cor(1,3, na.rm=T) itself produces the error

> Error in cor(1, 3, na.rm = T) : unused argument (na.rm = T)

If my understanding is correct, the mutate is not vectorized?

**Comment by naofumi-fujii** [comment] 2016-07-07 10:41
I faced this problem on
- Windows7
- 32bit
- RStudio 3.3.0, 3.3.1

and this is my code that causes crash.
```R
iris %>%
  group_by(Sepal.Length, Sepal.Width, some_not_exisiting_colname) %>%
  summarise(sum(Petal.Width))
```

hope this helps.

**Comment by mikedolanfliss** [comment] 2016-07-08 01:45
Same here on Win7, 32bit, R3.3.0. dplyr errors crash R entirely. Tried a reinstall of dplyr and Rcpp, but no dice yet.

**Comment by kevinushey** [comment] 2016-07-08 02:55
This is indeed a bad interaction between 32bit versions of R 3.3.x and RStudio. Hopefully, this will be fixed on the RStudio side soon.

**Comment by CBSti** [comment] 2016-08-03 14:07
Had the same problem and same OS/software conditions (Windows 7, 32 bit, R 3.3.1 ...). I installed the preview version of RStudio from
https://www.rstudio.com/products/rstudio/download/preview/ 
as suggested, now it works again. I get proper error messages instead of the R Session and/or RStudio crashing. Just some feedback, if this was already known, feel free to delete this comment.

**Comment by kevinushey** [comment] 2016-08-09 22:45
Thanks for the confirmation @CBSti -- indeed, this should now be resolved in the RStudio preview release.

To anyone stumbling upon this issue, please install the [preview release](https://www.rstudio.com/products/rstudio/download/preview/) of RStudio to resolve this issue.

**Comment by ZedLeb** [comment] 2016-09-07 20:41
I experienced these fatal error crashes today and would like to try the preview release but I'm using RStudio Portable.  

Does anyone know if (and how) I can install?

**Comment by kevinushey** [comment] 2016-09-07 20:57
Both installers and portable versions of the preview release of RStudio are available at https://www.rstudio.com/products/rstudio/download/preview/.

**Comment by ZedLeb** [comment] 2016-09-07 21:25
Many thanks for rapid response!
On 7 Sep 2016 10:57 p.m., Kevin Ushey <notifications@github.com> wrote:Both installers and portable versions of the preview release of RStudio are available at https://www.rstudio.com/products/rstudio/download/preview/.

**Comment by ZedLeb** [comment] 2016-09-08 14:29
Installed the preview version today and I'm not crashing any more.  Thank you!
I noticed this new version runs the whole of a dplyr piped chain too - that caught me off guard :)

**Comment by pushkar-patil** [comment] 2016-09-21 06:28
Me too was facing the same issue. While using mutate() in dplyr, the rstudio crashed completely.
Installed the preview version and now its working. Thanks!!!

**Comment by krlmlr** [comment] 2016-11-07 23:56
Seems to be resolved by the RStudio preview release. Can we close this?

**Comment by kevinushey** [comment] 2016-11-07 23:57
Yes indeed (the fixes are also part of the current RStudio release, v1.0.44).

**Closed** 2016-11-08 00:06 UTC
Labels: bug, data frame

**Comment by tandrewsimpson** [comment] 2017-04-15 16:18
Instead of reinstalling RStudio, try removing all your packges. That worked for me! I used this code:

```
ip <- installed.packages()
pkgs.to.remove <- ip[!(ip[,"Priority"] %in% c("base", "recommended")), 1]
sapply(pkgs.to.remove, remove.packages)
```
