### ISSUE TITLE
Using filter in combination with shiny's reactive values

### ISSUE THREAD

**Issue by Bart6114** [hadley/dplyr#1794] opened 2016-05-02 09:12 UTC
In the below minimal example: the filter statement's right-hand side uses a reactive value of which a sub-item is selecting using `$`. This results in an error `invalid subscript type 'double'`. Selecting using `[[` works. Also, `subset` does work with the `$` operator. 

```
library(dplyr)

server <- function(input, output) {
  
  reactive_value <- reactive({
    list(gear = 3)
  })
  
  output$table <- renderTable({
    mtcars %>%
      # filter(gear == reactive_value()[['gear']])
      # subset(gear == reactive_value()$gear)
      filter(gear == reactive_value()$gear)
    
  })
}

ui <- fluidPage(
  tableOutput("table"))
)

shinyApp(ui = ui, server = server)
```

**Comment by hadley** [comment] 2016-05-02 14:23
Duplicate of #1400

**Closed by hadley** 2016-05-02 14:23 UTC
