### ISSUE TITLE
Problem with left_join and umlauts

### ISSUE THREAD

**Issue by neuwirthe** [hadley/dplyr#1898] opened 2016-06-07 17:06 UTC
The attached file contaids mydf1 and myd2 which are tbl_df's with variables containing umlauts.
[leftjointest.RData.zip](https://github.com/hadley/dplyr/files/303124/leftjointest.RData.zip)

I could not send these tbls as by dput output becaus if I do that, the problem does not occur.

`left_join(mydf1,mydf2)
`

on these tbl_df's does not work correctly.
Both tbl_df's are in the same order for the join, and the left_join should just hate  the last variable of mydf2 appended to mydf1. But if the join variable partname contains umlauts, the join contains NA instead.

**Comment by hadley** [comment] 2016-06-07 21:02
Can you please provide a minimal reproducible example inline?

**Comment by neuwirthe** [comment] 2016-06-08 09:28
I managed reproducible inline code!

```
library(dplyr)
library(tidyr)
xdf1 <- data_frame(nr=1:3,wb=31:33,ÖVP=11:13)
xdf1x <- xdf1
colnames(xdf1x) <- c("nr","wb","ÖVP")
Encoding(colnames(xdf1))
Encoding(colnames(xdf1x))
xdf1g <- gather(xdf1,varname,val1,-nr)
xdf1xg <- gather(xdf1x,varname,val1,-nr)

xdf2 <- data_frame(nr=1:3,wb=31:33,ÖVP=21:23)
xdf2x <- xdf2
colnames(xdf2x) <- c("nr","wb","ÖVP")
Encoding(colnames(xdf2))
Encoding(colnames(xdf2x))
xdf2g <- gather(xdf2,varname,val2,-nr)
xdf2xg <- gather(xdf2x,varname,val2,-nr)

left_join(xdf1g,xdf2g)
left_join(xdf1xg,xdf2xg)
left_join(xdf1g,xdf2xg)
```

The very last line has the error. In fact, we do not get an error but an incorrect result.
The problem is that in that case I am joining two tbl_df where one of the key variables (varname) has 
values with umlauts.
In one of the tbls  (xdf1g), the encoding of all the values of varname are "unknown"
are encoded as UTF-8, whereas in xdf2xg the values with umlauts (not all the values, just the values with umlauts), are encoded as "UTF-8".

This problem is platform specific. It occurs on my Mac.
Here are the session details:
```
> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.5 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tidyr_0.4.1      dplyr_0.4.3.9001

loaded via a namespace (and not attached):
[1] lazyeval_0.1.10.9000 magrittr_1.5         R6_2.1.2             assertthat_0.1       rsconnect_0.4.3      DBI_0.4-1           
[7] tools_3.3.0          tibble_1.0-5         Rcpp_0.12.5         
> packageVersion("dplyr")
[1] ‘0.4.3.9001’
> packageVersion("tidyr")
[1] ‘0.4.1’
```


It also occurs on Ubuntu 16.04
```
> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04 LTS

locale:
 [1] LC_CTYPE=en_US.UTF8       LC_NUMERIC=C             
 [3] LC_TIME=en_US.UTF8        LC_COLLATE=en_US.UTF8    
 [5] LC_MONETARY=en_US.UTF8    LC_MESSAGES=en_US.UTF8   
 [7] LC_PAPER=en_US.UTF8       LC_NAME=C                
 [9] LC_ADDRESS=C              LC_TELEPHONE=C           
[11] LC_MEASUREMENT=en_US.UTF8 LC_IDENTIFICATION=C      

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tidyr_0.4.1      dplyr_0.4.3.9001

loaded via a namespace (and not attached):
[1] lazyeval_0.1.10 magrittr_1.5    R6_2.1.2        assertthat_0.1 
[5] tools_3.3.0     DBI_0.4-1       tibble_1.0-5    Rcpp_0.12.5    
> packageVersion("dplyr")
[1] ‘0.4.3.9001’
> packageVersion("tidyr")
[1] ‘0.4.1’

```
It does NOT occur in Windows, though (in that case the encoding given for values containing umlauts is "latin-1":

```
> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tidyr_0.4.1 dplyr_0.4.3

loaded via a namespace (and not attached):
[1] lazyeval_0.1.10 magrittr_1.5    R6_2.1.2        assertthat_0.1 
[5] parallel_3.3.0  DBI_0.4-1       tools_3.3.0     Rcpp_0.12.4    
> packageVersion("dplyr")
[1] ‘0.4.3’
> packageVersion("tidyr")
[1] ‘0.4.1’
```

**Comment by neuwirthe** [comment] 2016-06-17 16:35
R 3.3.1 rc1 has the following note:

> match(x, t) (and hence x %in% t) failed when x was of length one, and either character and x and t only differed in their Encoding or when x and t where complex with NAs or NaNs. (PR#16885.)

Is left_join using this match. If so, this might be the reason for my problem.

**Comment by joelgombin** [comment] 2016-07-27 08:48
Well done for identifying the bottom if that issue. I've encountered the same issue.

**Comment by joelgombin** [comment] 2016-07-27 09:03
`merge` works fine, BTW (but it's slow!)

**Comment by uhkeller** [comment] 2016-10-07 10:33
I ran into this problem as well, with R 3.3.1 and dplyr 0.5.0 on Arch Linux. This seems like a pretty major bug to me, and frankly it's rather disconcerting that nothing seems to have happened on this front in four months.

**Comment by krlmlr** [comment] 2016-11-07 22:57
We're working on this problem. For now please ensure that all your character columns are encoded in UTF-8, but all your column names are encoded as "native", which is *not* UTF-8 on Windows.

**Comment by krlmlr** [comment] 2016-11-08 07:16
Closing, duplicate of #1885.

**Closed by krlmlr** 2016-11-08 07:16 UTC
