### ISSUE TITLE
Clash between dpylr::filter and lubridate

### ISSUE THREAD

**Issue by FSpanhel** [hadley/dplyr#2520] opened 2017-03-10 13:52 UTC
When I subset a dataframe with respect to a lubridate object using dplyr::filter I get unexpected results that do not occur when I subset using base commands. 

``` r
library("dplyr")
library("lubridate")

periods <- c("00:00:00", "01:00:00")
periods <- hms(periods)
data <- data.frame(periods)

data_base <- data[hour(data$periods) < 1, , drop = F] # subset periods using base
data_dplyr <- dplyr::filter(data, hour(periods) < 1) # subset periods using filter
print(data_dplyr) # throws a warning and indicates that data_dplyr$periods equals periods[1]
#> Warning in format.data.frame(x, digits = digits, na.encode = FALSE):
#> corrupt data frame: columns will be truncated or padded with NAs
#>   periods
#> 1      0S

data_base$periods # expected output, equal to periods[1]
#> [1] "0S"
data_dplyr$periods # equals periods, i.e., subsetting did not work as expected
#> [1] "0S"       "1H 0M 0S"
```

**Comment by zeehio** [comment] 2017-03-10 14:43
When using `base`, the structure of the data frame seems fine:
```
str(data_base)
```
```
'data.frame':	1 obs. of  1 variable:
 $ periods:Formal class 'Period' [package "lubridate"] with 6 slots
  .. ..@ .Data : num 0
  .. ..@ year  : num 0
  .. ..@ month : num 0
  .. ..@ day   : num 0
  .. ..@ hour  : num 0
  .. ..@ minute: num 0
```
However if we see the structure of the `dplyr` data frame, we see that only one out of the 6 slots is subsetted:
```r
str(data_dplyr)
```
```
'data.frame':	1 obs. of  1 variable:
 $ periods:Formal class 'Period' [package "lubridate"] with 6 slots
  .. ..@ .Data : num 0
  .. ..@ year  : num  0 0
  .. ..@ month : num  0 0
  .. ..@ day   : num  0 0
  .. ..@ hour  : num  0 1
  .. ..@ minute: num  0 0
```

This looks like a bug in dplyr

**Comment by zeehio** [comment] 2017-03-10 14:53
This is a problem with `dplyr::slice_` as well:

With simple types it works:

```r
dplyr::slice_(iris, 1)
```
```
  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1          5.1         3.5          1.4         0.2  setosa
```

In this case does not:

```r
data <- data.frame(periods = hms(c("00:00:00", "01:00:00")))
dplyr::slice_(data, 1)
```
```
Warning message:
In format.data.frame(x, digits = digits, na.encode = FALSE) :
  corrupt data frame: columns will be truncated or padded with NAs
```

**Comment by hadley** [comment] 2017-03-10 18:14
Duplicate of #2432

**Closed by hadley** 2017-03-10 18:14 UTC
