### ISSUE TITLE
improve summarise error message

### ISSUE THREAD

**Issue by libor-m** [hadley/dplyr#2595] opened 2017-03-30 07:06 UTC
When writing a longer pipeline and running it after it's done, mistakes can crawl in. Figuring them out would be easier, if the error message generated by returning multiple values from an aggregation step would include `summarise` and ideally a name of the column. That is

`Error: summarise is expecting a single value for column fail`

instead of the current 

`Error: expecting a single value`

```r
library(tidyverse)

df <- data.frame(treatment = c(rep(c("Stimulation", "Control"), 8)),
                 group = c(rep(c("A", "B"), 4),
                           rep(c("B", "A"), 4)),
                 value = rnorm(16, mean = 150, sd = 20))

df %>%
  group_by(group, treatment) %>%
  summarise(fail = value)
```

**Comment by hadley** [comment] 2017-03-30 12:05
Duplicate of #2448

**Closed by hadley** 2017-03-30 12:05 UTC
