### ISSUE TITLE
Issue connecting to MySQL with one-value %in% filters

### ISSUE THREAD

**Issue by Breza** [hadley/dplyr#2012] opened 2016-07-11 17:20 UTC
I normally have no problem running operations against the _people_ table of the _birch_ database (MySQL). However, I'm getting an unusual error when I try to filter using the %in% operator and I only have one value in the filtering vector. Here's a minimal example.

**This works fine**
```
birch %>%
tbl("people") %>%
select(email, school_name) %>%
filter(email %in% c('breza@gmail.com', 'andrew.breza@gmail.com'))
```

**But I get an error whenever my %in% only has one item**
```
birch %>%
tbl("people") %>%
select(email, school_name) %>%
filter(email %in% c('andrew.breza@gmail.com'))

#Error in .local(conn, statement, ...) : 
#  could not run statement: You have an error in your SQL syntax; check the manual that corresponds 
#to your MySQL server version for the right syntax to use near ''andrew.breza@gmail.com')) 
#`seuwdsljlw`
#LIMIT 10' at line 5
```

**Comment by hadley** [comment] 2016-07-11 17:23
Duplicate of #511

**Closed by hadley** 2016-07-11 17:23 UTC

**Comment by Breza** [comment] 2016-07-11 17:31
Thanks @hadley!
