### ISSUE TITLE
problem with formula argument in lm within dplyr pipeline

### ISSUE THREAD

**Issue by ggrothendieck** [hadley/dplyr#1648] opened 2016-01-31 15:08 UTC
As in http://stackoverflow.com/questions/35096201/residualize-an-observation-after-fitting-a-model-in-group-by/35097382#35097382

this works as expected but if we remove the double quotes around the formula then it gives an error.  

```
iris %>%
 group_by(Species) %>%
   do(mutate(., resid = resid(lm("Sepal.Length ~ Sepal.Width", .)))) %>%
 ungroup()
```

Interestingly as shown in the link above this works but only if we use data.table as shown here below and not if we replace `as.data.table(iris)` with `iris`, even if we pass the formula as a character string.

```
library(data.table)
as.data.table(iris) %>%
 group_by(Species) %>%
   mutate(resid = resid(lm(Sepal.Length ~ Sepal.Width, .))) %>%
 ungroup()
```

I am using dplyr 0.4.3, data.table 1.9.7 and "R version 3.2.3 Patched (2016-01-12 r69945)".

**Comment by hadley** [comment] 2016-03-01 15:03
Duplicate of #1589

**Closed by hadley** 2016-03-01 15:03 UTC
