### ISSUE TITLE
Also having error with dplyr, mutate and group_by

### ISSUE THREAD

**Issue by emargoli** [hadley/dplyr#1483] opened 2015-10-29 19:05 UTC
I believe I'm having a similar problem as #464 (Mutate fails with incompatible type error).  I have a database that is organized by species and I want to find out if a particular value is the same as a prior date or not and if so replace those with NA. 

The dataframe looks like:
   time G.vaginalis A.vaginae
1     0    5.909021  2.574031
2     1    2.574031  2.574031
3     2    3.207096  2.574031
4     3    2.574031  2.574031
5     4    2.794139  2.574031
6     5    4.008600  2.574031
7     6    6.056905  3.162415
8     7    6.911690  5.257679

I can transform it long and mutate an additional column to compare values at the time point previous (a simplified version):

df1%>%gather("species", "freq", -time)%>%
    group_by(species)%>%mutate(vcon1=ifelse(is.na(freq),0,ifelse(lag(freq,1)!=freq, 0, 1)))

But whenever I add on the next part to change the value based on that comparison:

df1%>%gather("species", "freq", -time, -row)%>%
    group_by(species)%>%mutate(vcon1=ifelse(is.na(freq),0,ifelse(lag(freq,1)!=freq, 0, 1)),
                                                     freq=ifelse(vcon2==0,freq, NA))%>%
                                         select(row,time, species, freq)%>%spread(species,freq)

I get the following error message:

 Error: incompatible types, expecting a numeric vector 

I've gotten around it by ungrouping prior to mutating the value (freq) but it appears this is still an active glitch or maybe I'm miss using dplyr/tidyr or not understanding something.

I upgraded the dplyr 0.3.4 based on the prior comments and still got the error message.

**Comment by hadley** [comment] 2015-10-30 11:12
It's probably because you have `NA` in your `ifelse` - that's a logical value, not a numeric value.  Try `NA_real_` instead. We are going to try and fix the underlying issue, but this is a duplicate of another issue so I'm going to close it.

**Closed by hadley** 2015-10-30 11:12 UTC

**Comment by bowerth** [comment] 2015-12-07 19:50
saved my evening, thanks a lot!
