### ISSUE TITLE
BUG: new functions like select_if, summarise_if, etc does not handle columns with ','

### ISSUE THREAD

**Issue by paullevchuk** [hadley/dplyr#2377] opened 2017-01-25 10:57 UTC
I checked release notes of purrr 0.2.2.9000 and found this:
"Mapping a function to each column of a data frame should now be handled with the colwise mutating and summarising operations in dplyr instead of dmap(). These are the verbs with suffix _all(), _at() and _if(), such as mutate_all() or summarise_if()."

It seems reasonable that purrr::dmap functions migrates to dplyr. But new functions do NOT handle tibble simplification of columns naming. Let's juts code simple example.

```{r}
library(tidyverse)

df <- tibble(payment_amount = runif(20, min = 10, max = 100),
             id = as.factor(rep(1:4, 5)))

bins <- c(0, 20, 50, 100)

df %>% 
  mutate(bin = cut(payment_amount, bins, boundary = 0)) %>% 
  count(id, bin) %>% 
  spread(bin, n) %>% 
  # does NOT work
  select_if(is_integer)

  # purrr analog works as it should be
  # keep(is_integer)
````
`select_if()` generates weird error: 
Error in parse(text = x) : <text>:1:3: unexpected ','
1: (0,
      ^

There are other cases when **select_if**, **mutate_if**, **summarise_if**, etc do not work with such column names. It seems that new implementation does not fully support tibble.

Please fix this before depreciating purrr functions. Thanks!
```

**Comment by romainfrancois** [comment] 2017-01-25 11:28
Probable related to #2361

**Comment by krlmlr** [comment] 2017-01-25 21:51
Same as #2243?

**Comment by paullevchuk** [comment] 2017-01-25 21:57
I identified that purrr functions (dmap family, keep, etc) do not have this problem. 

Is it reasonable just to move purrr code to dplyr?

**Comment by krlmlr** [comment] 2017-01-28 08:58
We could look at what purrr does differently, but moving all functions won't work because dplyr also has to take care of other data sources such as SQL tables.

#2386 is a draft for a generic and consistent solution, currently only for `select_if()`.

**Comment by paullevchuk** [comment] 2017-01-28 09:08
I understood it. I just suggest re-use piece of code as it just works. Thanks!
Probably you could explain me why purrr supports great extention - shortcuts like ~ , and, at the same time, dplyr does not absorb this great technique?

**Comment by krlmlr** [comment] 2017-01-28 10:23
Would that piece of code also work for SQL data sources?

**Comment by paullevchuk** [comment] 2017-01-28 17:39
Actaully I don't know. Sorry

**Comment by hadley** [comment] 2017-01-31 22:53
Closing as duplicate of #2243

**Closed by hadley** 2017-01-31 22:53 UTC
