### ISSUE TITLE
In mutate(), foo$var fails but foo$"var" works.

### ISSUE THREAD

**Issue by pfh** [hadley/dplyr#1716] opened 2016-03-16 00:47 UTC
I expected this code to work, but it produces an error:

```
foo <- list(var=10)
mutate(data_frame(x=1), y=foo$var)
# Error: invalid subscript type 'closure'
```

This seems to be because var is a function. Using $ with other functions also produces this error. Putting var in quotes produces the expected result:

```
mutate(data_frame(x=1), y=foo$"var")
# Source: local data frame [1 x 2]
# 
#       x     y
#  (dbl) (dbl)
# 1     1    10
```

I am using dplyr_0.4.3. (I tried installing the latest github version with devtools, but got the error "Malformed remote specification 'hadley/testthat'")

**Comment by pfh** [comment] 2016-03-16 00:56
Actually, any variable or column in the data frame has this problem.

```
mutate(data_frame(x=1), y=list(x=2)$x)
# Error: invalid subscript type 'double'
```

**Comment by hadley** [comment] 2016-03-16 01:30
Duplicate of #1400

**Closed by hadley** 2016-03-16 01:30 UTC
