### ISSUE TITLE
Select helpers expanded to mutate scope

### ISSUE THREAD

**Issue by danielsjf** [hadley/dplyr#2571] opened 2017-03-24 12:59 UTC
There exist helper functions to select multiple columns for select. It would be nice to have them available for mutate as well. A small (not working) example for the syntax:

```r
df <- data.frame(x = c('A','B','C'), X2017 = c(5,7,9), X2018 = c(1,8,3), X2019 = c(11,2,5))
df %>% mutate(max = pmax(X2017:X2019)) # use the ':' selector
df %>% mutate(max = pmax(num_range("X", 2017:2019))) # use the ':' selector
```

Most of these cases can probably be solved by using a gather, a group_by and a summarise. 

```r
df %>% gather(year, value, X2017:X2019) %>% group_by(x) %>% summarise(max = max(value))
```

However, this is already quite verbose. I often find myself using this structure and expanding these helper functions to mutate would be quite intuitive. Only the ':' selector could have an synonym like through_range(from, to) to avoid confusion with the R ':' notation.

**Comment by hadley** [comment] 2017-03-24 13:33
Effectively a duplicate of https://github.com/hadley/vctrs/issues/9

**Closed by hadley** 2017-03-24 13:33 UTC
