### ISSUE TITLE
Better syntax for mutate() than nested "ifelse" functions

### ISSUE THREAD

**Issue by reedblog** [hadley/dplyr#1518] opened 2015-11-07 01:09 UTC
All of the dplyr functions make R code more readable except for one pretty common case, conditionally assigning variable values with mutate(). The current syntax is something like:
 ```df <- mutate(df, newvar = ifelse(oldvar %in% c("a", "b", "c"), "group1", ifelse(oldvar %in% c("d", "e", "f"), "group2", ifelse(oldvar %in% c("g", "h", "i"), "group3", NA))))```

I saw a question on StackOverflow that gave a much better solution, borrowing from the "mosaic" package: http://stackoverflow.com/questions/24459752/can-dplyr-package-be-used-for-conditional-mutating?rq=1

```library(mosaic)
df <- mutate(df, newvar = derivedFactor(
  "group1" = oldvar %in% c("a", "b", "c"),
  "group2" = oldvar %in% c("d", "e", "f"),
  "group3" = oldvar %in% c("g", "h", "i"),
  .default = NA
))
```

Could something like this be the default syntax, please? 

Data frame for testing: ``` df <- data.frame(oldvar = letters)```

**Comment by romainfrancois** [comment] 2015-11-07 12:17
Duplicate of #631

**Closed by romainfrancois** 2015-11-07 12:17 UTC
