### ISSUE TITLE
Windowing operations on intervals

### ISSUE THREAD

**Issue by tchakravarty** [hadley/dplyr#1879] opened 2016-06-02 11:55 UTC
@hadley 

I am unable to get windowing functions to work when the objects have class `Interval` in a `tbl_df`. This is true whether I compose the interval from `chron` objects or `POSIXlt` objects. Here are examples of both: 

```{r}
# version 1: where the constituent dates have class "chron"
bb = data_frame(
  a = chron(c(1.001, 2.001)),
  b = chron(c(3.001, 4.001))
)

bb %>% 
  mutate(interval = interval(a, b)) %>% 
  mutate(int_overlaps(interval, dplyr:::lag(interval)))

# version 2: POSIXlt-based intervals
bb = data_frame(
  a = as.POSIXlt(strptime(c("2011-03-27 01:30:00", "2011-03-27 01:31:00"), "%Y-%m-%d %H:%M:%S"), tz = "UTC"),
  b = as.POSIXlt(strptime(c("2011-03-27 01:33:00", "2011-03-27 01:34:00"), "%Y-%m-%d %H:%M:%S"), tz = "UTC")
)

bb %>% 
  mutate(interval = interval(a, b)) %>% 
  mutate(int_overlaps(interval, dplyr:::lag(interval)))
```

I get the same error in either case -- `Error: trying to get slot "start" from an object of a basic class ("numeric") with no slots`. Not sure I am using `lag` wrong or whether this a limitation of `tbl_df`.

**Comment by hadley** [comment] 2016-06-07 21:11
This is basically a duplicate of #1581 - there's currently no dplyr support for intervals, unfortunately.

**Closed by hadley** 2016-06-07 21:11 UTC
