### ISSUE TITLE
mysql filter error when using %in% and only one element

### ISSUE THREAD

**Issue by williamjwest** [hadley/dplyr#1034] opened 2015-03-23 14:52 UTC
Error in .local(conn, statement, ...) : 
  could not run statement: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''xxxxxxxx') AS `master`' at line 3

res = tbl(dcon,"my_table") %>%
    filter(dealer_name %in% input$x )
res
This works without issue when input$x has more than 2 values and throws the error above when input$x has 1 value.

**Comment by hadley** [comment] 2015-05-19 15:49
Duplicate of #511

**Closed by hadley** 2015-05-19 15:49 UTC
