### ISSUE TITLE
infix operator translation for `%in%` needs parentheses

### ISSUE THREAD

**Issue by mdsumner** [hadley/dplyr#1795] opened 2016-05-02 14:12 UTC
The infix `%in%` translation fails when there's there's only one value in the table. 

This first syntax is an error, at least in SQLite. 

```R
library(dplyr)

dplyr:::default_op("%in%")("a", "b")
#<SQL> 'a' IN 'b'
dplyr:::default_op("%in%")("a", c("b", "c"))
##<SQL> 'a' IN ('b', 'c')
```

Example using SQLite. 

```R
db <- src_sqlite("aatest.sqlite3", create = TRUE)
dat <- copy_to(db, data.frame(a = c("b", "d")), name = "dat")

## ok
dat %>% filter(a %in% c("b", "c"))

## should be "WHERE "a" IN ('b')"
dat %>% filter(a %in% "b") %>% show_query()

dat %>% filter(a %in% "b") 
#Source: sqlite 3.8.6 [aatest.sqlite3]
#Error in sqliteSendQuery(con, statement, bind.data) : 
#  error in statement: no such table: b
```

This is  dplyr      * 0.4.3      2015-09-01 CRAN (R 3.2.5)

**Comment by hadley** [comment] 2016-05-02 14:27
Duplicate of #511

**Closed by hadley** 2016-05-02 14:27 UTC
