### ISSUE TITLE
Filter and %in% on MySQL tables

### ISSUE THREAD

**Issue by mstrimas** [hadley/dplyr#2010] opened 2016-07-10 22:07 UTC
Applying `filter(x, a %in% b)` to a `tbl_mysql` object can lead to an error if the variable b has length 1. For example,

```
b <- 1:10
filter(x, a %in% b) # works
c <- 1
filter(x, a %in% c) # error
```

The first `filter()` works, but the second doesn't. Seems the second gets converted to `SELECT * FROM x WHERE a IN 1`, when it should be `SELECT * FROM x WHERE a IN (1)` or `SELECT * FROM x WHERE a = 1`.

**Comment by DarioBoh** [comment] 2016-07-11 00:39
I posted about the [same issue two days ago on SO](http://stackoverflow.com/questions/38251927/how-to-filter-a-dynamic-table-based-on-a-single-value).
This replicates the error
```
my_db <- src_mysql(dbname = "dplyr", 
                   host = "dplyr.csrrinzqubik.us-east-1.rds.amazonaws.com", 
                   port = 3306, 
                   user = "dplyr",
                   password = "dplyr")
tbl(my_db, "dplyr") %>% filter(carrier %in% c("UA","AA")) #works
tbl(my_db, "dplyr") %>% filter(carrier %in% c("UA")) #doesn't work
```

**Comment by hadley** [comment] 2016-07-11 01:13
Duplicate of very old bug

**Closed by hadley** 2016-07-11 01:13 UTC
