### ISSUE TITLE
error when running median() in mutate + group_by (no NAs)

### ISSUE THREAD

**Issue by maype** [hadley/dplyr#2267] opened 2016-11-25 08:31 UTC
I get an " incompatible types, expecting a numeric vector" Error for the following code:

data1 <- data1 %>% 
  group_by(var1) %>% 
  mutate(median_var = median(RT[var2=="cond1"]))

data1 has no NAs (contrary to #1909 )
RT column  is indeed numeric, and running mean() instead of median() works fine.
R version 3.2.3.

example tibble:

var 1    var 2     RT
1         cond1    500
1         cond1    550
1         cond2    520
2         cond1    600
2         cond2    700
2         cond1    500

Thanks for checking this!

**Comment by krlmlr** [comment] 2016-11-27 09:47
Thanks. I can't replicate your problem with the current development version. Next time, please supply a reproducible example. From the information you gave, I have derived:

```r
data1 <- read.table(header = TRUE, text = "
var1 var2 RT
1 cond1 500
1 cond1 550
1 cond2 520
2 cond1 600
2 cond2 700
2 cond1 500
")

data1 <- data1 %>%
  group_by(var1) %>%
  mutate(median_var = median(RT[var2=="cond1"]))
```

**Comment by maayanru** [comment] 2016-11-27 10:48
Sorry, indeed I didn't give a good example (this was just meant to give an overview of what the file looks like).
I now attach a file of example data that does reproduce the above mentioned error.
I load it to R using:
data1 <- read.table("mydata.txt", header = TRUE, sep = ",", row.names = 1)

and run the same command:
data1 <- data1 %>%
  group_by(var1) %>%
  mutate(median_var = median(RT[var2=="cond1"]))

and get "Error: incompatible types, expecting a numeric vector"

Thanks again!

[mydata.txt](https://github.com/hadley/dplyr/files/614649/mydata.txt)

**Comment by krlmlr** [comment] 2016-11-27 10:49
Could you please inline mydata.txt and use triple-backticks ` ``` ` to denote code blocks?

**Comment by maype** [comment] 2016-11-27 11:56
mydata.txt is quite long (over 2000 rows), thus it was attached. 
This shorter similar example also works:

```
data1 <- data.frame(var1 = sample(c(1,2,3),50,replace=T), var2 = sample(c("cond1", "cond2"), 50,replace=T),RT = sample(300:1000,50,replace=T))
```
running the following command returns the Error: incompatible types, expecting a numeric vector
```
data1 <- data1 %>%
  group_by(var1) %>%
  mutate(median_var = median(RT[var2=="cond1"]))
```

But this works fine:
```
data1 <- data1 %>%
  group_by(var1) %>%
  mutate(median_var =(quantile(RT[var2=="cond1"],probs=0.5)))
```

hope this is better now.. thanks

**Comment by krlmlr** [comment] 2016-11-27 12:15
Thanks, confirmed. (One large code block is still a bit easier to copy-paste.)

The issue doesn't occur if RT is a numeric vector, not a vector of integers as in your example.

**Comment by hadley** [comment] 2017-02-27 00:04
Minimal reprex:

```R
df <- tibble(
  g = c(1, 2, 2), 
  x = c(1L, 2L, 3L)
)

df %>%
  group_by(g) %>%
  mutate(median(x))
```

**Comment by hadley** [comment] 2017-02-27 00:05
Duplicate of #1909

**Closed by hadley** 2017-02-27 00:05 UTC
Labels: bug, data frame, vector
