### ISSUE TITLE
Coercion of various date/time classes to numeric (including lubridate)

### ISSUE THREAD

**Issue by lelandbr** [hadley/dplyr#2214] opened 2016-10-27 21:35 UTC
I think I found a few more coercion problems. This involved dplyr, tidyr, and lubridate, but I posted here since it seems very similar to #509/#576

Here's a summary of when date/time classes are being coerced to numeric (see examples below):
- `dplyr::nth`, `first`, and `last` no longer coerce! (#509)
- `tidyr::fill` coerces most date/time classes in other columns, including `difftime`
- `dplyr::cummean` coerces most date/time classes, including `POSIXct` and `lubridate::Duration`. Likely this is an issue with [(lubridate issue #176)](https://github.com/hadley/lubridate/issues/176)? `mean`/`cummean` don't work on `lubridate::Interval` (which makes sense), or `lubridate::Period` (which maybe also makes sense?)
- `dplyr::lag` coerces `lubridate::Interval`, `lubridate::Period`, and `lubridate::Duration`
- `dplyr::lead` doesn't coerce anything, but it does give an error that I don't understand with `difftime` columns, and it makes mistakes with `lubridate::Interval` and `lubridate::Period`

I made the following test df which includes all the date/time classes I could find for comparison purposes.

``` r
# pack all the date/time classes I can find into one df:
df <- tibble(grps          = c("a","a","b","b","c","c"), 
             to.fill       = c(1,NA,3,NA,5,NA),
             to.arrange    = 6:1,
             base.Date     = as.Date(0:5,origin = "1970-01-01"),
             base.POSIXct  = as.POSIXct(as.character(base.Date)),
             # base.POSIXlt: tibble does not allow POSIXlt columns
             base.difftime = as.difftime(1:6,units="days"),
             date.date     = date::as.date(1:6), #doesn't display very well in a data.frame
             chron.dates   = chron::chron(0:5),
             chron.times   = chron::chron(times. = (1:6)),
             lubr.Interval = lubridate::interval( as_date(0:5), as_date(10:15) ),
             lubr.Period   = lubridate::period(days=1:6),
             lubr.Duration = lubridate::ddays(1:6)
             )
lapply(df,class) # show classes
```

Examples using this `df`:

``` r
# dplyr::nth() first() and last() do not coerce to numeric anymore
#      https://github.com/hadley/dplyr/issues/509
#      https://github.com/hadley/dplyr/issues/576
df %>% group_by(grps) %>% summarize_all( funs(nth(.,1)) )

# but, tidyr::fill() coerces most date/time classes to numeric
# (it doesn't coerce base::Date and base::POSIXct)
df %>% group_by(grps) %>% fill(to.fill)

# mean() works on many of these date/time classes, but 
# dplyr::cummean() coerces to numeric (including POSIXct)
df %>% mutate_at(vars(-grps),mean)
df %>% mutate_at(vars(-grps),cummean) 
  # NOTE: both mean() and cummean() don't work with  
  # lubridate::Interval ... that makes intuitive sense.
  # taking the mean() of lubridate::Period also doesn't
  # work, which maybe also makes sense? ... I'm not very
  # familiar with this class.
  # But both mean() and cummean() work with 
  # lubridate::Duration except that they coerce to
  # numeric. Same issue raised here in the lubridate repo: 
  # https://github.com/hadley/lubridate/issues/176

# dplyr::lag() coerces all three lubridate classes to numeric,
# but other date/times are fine
df %>% mutate_all(lag)

# dplyr::lead() oddly behaves differently from lag()
# first of all it has this strange error that lag() does not have ...
df %>% mutate_all(lead) # "Error: 'tim' is not character or numeric"
# this is an error with base::difftime it seems like, since we can
# get around this error by skipping that column:
df %>% mutate_at(vars(-base.difftime),lead)
  #1) oddly does keep all of the lubridate classes without coercion
  #2) BUT, the output is not correct for lubridate::interval and 
  #    lubridate::period columns ... basically it looks like it did not
  #    actually "lead" anything for these columns, and it just replaced
  #    the last row with NA
  #3) also, the NA it replaced the last row with for lubridate::interval
  #    is "1970-01-06 UTC--NA" instead of just "NA--NA"
```

EDIT: forgot to add sessionInfo()

```
sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lubridate_1.6.0 chron_2.3-47    date_1.2-34     tidyr_0.6.0     dplyr_0.5.0    

loaded via a namespace (and not attached):
[1] magrittr_1.5   R6_2.1.3       assertthat_0.1 DBI_0.5        tools_3.3.1    tibble_1.2     Rcpp_0.12.6   
[8] stringi_1.1.1  stringr_1.1.0 
```

**Comment by krlmlr** [comment] 2016-11-07 14:41
Awesome, thanks. The support for nonstandard representations in dplyr is weak (hadley/vctrs#27), but "plain old vectors" with a class shouldn't be coerced in most cases. Would you like to contribute individual tests for these cases?

**Comment by krlmlr** [comment] 2017-03-21 18:56
@hadley: Is this a duplicate of #2432?

**Comment by hadley** [comment] 2017-03-21 21:26
Yes, looks like it.

**Closed by hadley** 2017-03-21 21:26 UTC
Labels: bug, data frame, vector
