### ISSUE TITLE
Performance: Consider using radix sort for character vectors

### ISSUE THREAD

**Issue by krlmlr** [hadley/dplyr#2201] opened 2016-10-26 14:11 UTC
For a 1e7 vector, this is 10x faster than the currently used shell sort. Drawback: Requires same encoding for all values (which we'll have anyway at some point), and sorts in the C locale (i.e., locale-independent sorting which might give strange results in some scripts).

This could be bundled with a way to specify the collation used for sorting a character vector.

Affects data frames.

@hadley: Thoughts?

https://github.com/hadley/dplyr/issues/2198#issuecomment-256357482

**Comment by hadley** [comment] 2016-10-26 14:59
Seems like a reasonable idea

**Comment by krlmlr** [comment] 2016-10-26 22:53
Oh, it's actually documented that way, but there is a test that sorting is localized (#1280). ...

For fast localized sorting, we could use sort keys (see bottom of http://userguide.icu-project.org/collation).

**Comment by hadley** [comment] 2017-02-22 12:29
Duplicate of #2198

**Closed by hadley** 2017-02-22 12:29 UTC
Labels: data frame
