### ISSUE TITLE
dplyr::copy_to errors out with MySQL backend due to NA values

### ISSUE THREAD

**Issue by JohnMount** [hadley/dplyr#2259] opened 2016-11-19 17:16 UTC
The "insert flights into dplyr source" example from https://cran.r-project.org/web/packages/dplyr/vignettes/databases.html errors out in the presence of NA in character values when using MySQL 5.6.34 as the back end.  R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch" on OSX 10.11.6, dplyr 0.5.0, RMySQL 0.10.9, DBI 0.5.1.

```
> mysql <- src_mysql('mysql','127.0.0.1',3306,'root','passwd')
> library('nycflights13')
> flts <- flights
> flights_mysql <- copy_to(mysql, flts, temporary = FALSE, indexes = list(
+     c("year", "month", "day"), "carrier", "tailnum"))
 Hide Traceback
 
 Rerun with Debug
 Error in if (n <= 65535) { : missing value where TRUE/FALSE needed 
8 char_type(x) 
7 FUN(X[[i]], ...) 
6 vapply(fields, data_type, character(1)) 
5 db_data_type.MySQLConnection(dest$con, df) 
4 db_data_type(dest$con, df) 
3 types %||% db_data_type(dest$con, df) 
2 copy_to.src_sql(mysql, flts, temporary = FALSE, indexes = list(c("year", 
    "month", "day"), "carrier", "tailnum")) 
1 copy_to(mysql, flts, temporary = FALSE, indexes = list(c("year", 
    "month", "day"), "carrier", "tailnum")) 
```

Example of work-around (suppressing the NAs) here: http://www.win-vector.com/blog/2016/11/mysql-in-a-container/

**Comment by krlmlr** [comment] 2016-11-22 14:59
Thanks, confirmed with current master. Would you like to submit a PR with a test case and perhaps a fix?

**Comment by krlmlr** [comment] 2016-11-22 15:19
Duplicate of #2256. Let's move discussion there.

**Closed by krlmlr** 2016-11-22 15:19 UTC
Labels: bug, database
