### ISSUE TITLE
`count` not recognizing columns with non-ASCII characters

### ISSUE THREAD

**Issue by mgacc0** [hadley/dplyr#2147] opened 2016-09-26 15:51 UTC
On a environment with non-UTF8 encoding (for example on Windows),
`count` has some problems to recognize non-ASCII colnames:

``` r
    sessionInfo()
    # R version 3.3.1 (2016-06-21)
    # Platform: x86_64-w64-mingw32/x64 (64-bit)
    # Running under: Windows 7 x64 (build 7601) Service Pack 1
    # 
    # locale:
    # [1] LC_COLLATE=Spanish_Spain.1252  LC_CTYPE=Spanish_Spain.1252    LC_MONETARY=Spanish_Spain.1252 LC_NUMERIC=C                  
    # [5] LC_TIME=Spanish_Spain.1252    

    df1 <- tibble(a=c(1, 1, 2), b=c(1, 1, 1)) %>%
        mutate(ññ=a)
    df1 %>%
      select(ññ)
    # # A tibble: 3 × 1
    #      ññ
    #   <dbl>
    #1     1
    #2     1
    #3     2

    df1 %>%
       count(ññ)
    # Error: unknown column 'ññ' 

    df1 %>%
      `names<-`(iconv(names(.), from="UTF-8")) %>%
      count(ññ)
    # # A tibble: 2 × 2
    #      ññ     n
    #   <dbl> <int>
    #1     1     2
    #2     2     1
```

**Comment by krlmlr** [comment] 2016-11-07 21:42
Thanks. Is this a duplicate of #2105?

**Comment by krlmlr** [comment] 2016-11-08 07:21
Closing, probably duplicate of #1885.

**Closed by krlmlr** 2016-11-08 07:21 UTC
