### ISSUE TITLE
cbind'ing grouped df and df gives a matrix?

### ISSUE THREAD

**Issue by Hong-Revo** [hadley/dplyr#2475] opened 2017-02-27 10:39 UTC
This is... odd behaviour to say the least.
```
grp_df <- data_frame(x1 = 1:10, x2 = 1:10) %>% group_by(x1)
y_df <- data_frame(y = 1:10)

foo <- cbind(grp_df, y_df)

foo
#   grp_df               
#x1 Integer,10 Integer,10
#x2 Integer,10 Integer,10

foo[[1, 1]]
# [1] 1 2 3 4 5 6 7 8 9 10
```

This is with dplyr 0.5.0.9000, built on 24-Jan-2017.

**Comment by hadley** [comment] 2017-02-27 13:33
Duplicate of #2138. As far as I can tell, dplyr already provides the correct methods, but `rbind()`/`cbind()` don't call them because it uses a special dispatch mechanism that doesn't work for data frame subclasses.

**Closed by hadley** 2017-02-27 13:33 UTC

**Comment by Hong-Revo** [comment] 2017-02-27 13:50
I just rebuilt dplyr, and the problem is still there. Is there any solution besides just calling `cbind.data.frame` directly?

**Comment by hadley** [comment] 2017-02-27 15:05
Yes, call `bind_cols()`
