### ISSUE TITLE
"loss of precision" error when tbl_df contains numeric and integer fields

### ISSUE THREAD

**Issue by jordanwatson** [hadley/dplyr#1289] opened 2015-07-27 23:34 UTC
Maybe this isn't an issue and is just my poor understanding of the function. But if I have an statement that includes a numeric and an integer field, I get a loss of precision / conversion to integer error. However, I wasn't doing anything with the numeric field. 

If I convert the integer to numeric ahead of time however, the error goes away.
I saw a previous fix that seemed to address a similar issue so I thought I'd mention this in case it was a version of the same thing that slipped through.

dplyr version 0.4.2; Windows 8, 64-bit R V.3.2.1; RStudio V. 0.99.467

```
xx <- data.frame(Col1=letters[1:10],time1=as.numeric(rnorm(10,1,1)),time2=as.numeric(rnorm(10,1,1)),INDEX=as.integer(1:10))

my.df <- group_by(xx,Col1) %>% summarise(endIDX  = ifelse((time1<time2) | (time1==time2),INDEX,INDEX-1),startIDX= ifelse((time1<time2) | (time1==time2),INDEX+1,INDEX))

Error: loss of precision when attempting to convert a numeric to an integer

xx <- data.frame(Col1=letters[1:10],time1=as.numeric(rnorm(10,1,1)),time2=as.numeric(rnorm(10,1,1)),INDEX=as.numeric(1:10))

my.df <- group_by(xx,Col1) %>% summarise(endIDX  = ifelse((time1<time2) | (time1==time2),INDEX,INDEX-1),startIDX= ifelse((time1<time2) | (time1==time2),INDEX+1,INDEX))
```

**Comment by romainfrancois** [comment] 2015-08-02 09:28
I can't reproduce this with the dev version. 

```
> my.df <- group_by(xx,Col1) %>%
+     summarise(endIDX  = ifelse((time1<time2) | (time1==time2),INDEX,INDEX-1),
+                       startIDX= ifelse((time1<time2) | (time1==time2),INDEX+1,INDEX)
+     )
>
>
> my.df
Source: local data frame [10 x 3]

   Col1 endIDX startIDX
1     a      0        1
2     b      1        2
3     c      2        3
4     d      3        4
5     e      4        5
6     f      5        6
7     g      7        8
8     h      7        8
9     i      8        9
10    j     10       11
```

So I'm closing this. Please consider trying the dev version before filing an issue next time.

**Closed by romainfrancois** 2015-08-02 09:28 UTC
