### ISSUE TITLE
right_join with tbl_dt returns only data.frame

### ISSUE THREAD

**Issue by vvrably** [hadley/dplyr#1895] opened 2016-06-07 11:31 UTC
I tried to `right_join` two data tables, but the result is only a `data.frame`. On the other hand `left_join` returns also `data.table` and `tbl_dt`.  Why is it so?

```
library(data.table)
library(dplyr)

M <- 10
N <- 10
a <- data_frame(ix = 1:M, v = rnorm(M))
b <- data_frame(ix = 1:N, v = rnorm(N))

a <- tbl_dt(a)
b <- tbl_dt(b)
class(a)

abr <- right_join(a, b, by = 'ix')
class(abr)

abl <- left_join(a, b, by = 'ix')
class(abl)
```

**Comment by hadley** [comment] 2016-06-07 14:45
Duplicate of https://github.com/hadley/dtplyr/issues/16

**Closed by hadley** 2016-06-07 14:45 UTC
