### ISSUE TITLE
Conditional mutate

### ISSUE THREAD

**Issue by danielsjf** [hadley/dplyr#1665] opened 2016-02-17 15:52 UTC
Say I have a data frame:

    x <- data.frame(a=c(1,2,3,4,NA,6))

I want to replace all na values by 2 and limit the values at 4 in this data frame.
The limiting I could do by using pmin e.g.

    y <- x %>% mutate(b=pmin(a,4))

In the more difficult cases I could fall back on the _ifelse()_ function.

    y <- x %>% mutate(b=ifelse(is.na(a),2,a))

However the _ifelse()_ function has some serious drawbacks since it drops the attributes. Therefore you cannot do this with POSIXct objects and other types that depend on attributes.

A possible suggestion to overcome this issue and provide a more generic method could be to introduce a new keyword, similar to group_by. This keyword subsets the rows on which to apply the next operations in the same way that filter does but without throwing those rows out. E.g.:

    y <- x %>% 
      mutate(b=a) %>% 
      subset(is.na(a)) %>% 
      mutate(b=2) %>% 
      subset(b>4) %>% 
      mutate(b=4)

       a b
    1  1 1
    2  2 2
    3  3 3
    4  4 4
    5 NA 2
    6  6 4

Some use cases:
* NA replacement
* More general value replacement
* Data cleaning

Some stackoverflow posts:
http://stackoverflow.com/questions/24459752/can-dplyr-package-be-used-for-conditional-mutating
http://stackoverflow.com/questions/22337394/combine-mutate-with-conditional-values

**Comment by hadley** [comment] 2016-03-01 15:01
Duplicate of #631

**Closed by hadley** 2016-03-01 15:01 UTC
