### ISSUE TITLE
mutate_each will not append funs names to variables and overwrites if only one function specified

### ISSUE THREAD

**Issue by BrashEQLibrium** [hadley/dplyr#1259] opened 2015-07-10 22:12 UTC
```r
    # Get grouped data.
    by_species <- iris %>% group_by(Species)

    # Get mutated columns for min and max
    # Old columns retained, new columns with _min and _max added
    by_species %>% mutate_each(funs(blah = min, blergh = max))

    # But what if I only want to put one function in mutate_each and keep the old columns?
    by_species %>% mutate_each(funs(blah = min))
    # Too bad, so sad
```

**Comment by akhmed1** [comment] 2015-07-13 08:02
I think this is actually done on purpose.

**Comment by hadley** [comment] 2015-08-24 22:09
Duplicate of #442

**Closed by hadley** 2015-08-24 22:09 UTC
