### ISSUE TITLE
Inconsistencies result from copy_to

### ISSUE THREAD

**Issue by iangow** [hadley/dplyr#1558] opened 2015-11-29 15:08 UTC
I easily get situations where `copy_to` complains that a table already exists, yet there is no sign of the table in the database, even when accessed from the same connection.

There sees to be no equivalent of `overwrite=TRUE` as found in `RPostgreSQL::dbWriteTable`.

```
 # Make some fake data
> df_r <- tbl_df(expand.grid(1990:2000L, 1:4L, 1:50L))
> names(df_r) <- c("year", "quarter", "id")
> df_r$value <- rnorm(n=dim(df_r)[1])
> 
> pg <- src_postgres()
> 
> copy_to(pg, df_r, name="temp_df")
Error: Table temp_df already exists.
> 
> df <- tbl(pg, "temp_df")
Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  relation "temp_df" does not exist
LINE 1: SELECT * FROM "temp_df" WHERE 0=1
                      ^
)
```

**Comment by cronacronis** [comment] 2015-11-29 15:23
It is mentioned in #1471.
`copy_to` uses 
```
R
sql <- build_sql("INSERT INTO ", ident(table), " VALUES ", sql(values))
  dbGetQuery(con, sql)
```
https://github.com/hadley/dplyr/blob/dd10ccd543a2bea99573e6622b46d50f657b0c1f/R/src-postgres.r#L182

**Comment by iangow** [comment] 2015-11-29 15:27
That would explain why adding `overwrite=TRUE` didn't work. But the inconsistency still seems to be there.

**Comment by momeara** [comment] 2015-11-29 15:49
@iangow, this may be an issue with how postges schemas are handled in `dplyr`. If you have a table named `temp_df` in any other schema `dplyr` will complain that the table already exists. Is this what's going of for you?

**Comment by iangow** [comment] 2015-11-29 15:56
Perhaps, but I can't find this table (and it it seems that `dplyr::tbl` doesn't find it either), as the following yields nothing:

```
RPostgreSQL::dbGetQuery(pg$con, "SELECT table_schema, table_name, ordinal_position, column_name, data_type 
   FROM information_schema.columns 
   WHERE table_name = 'temp_df'
   ORDER BY table_schema, table_name, ordinal_position;")
```

**Comment by hadley** [comment] 2016-03-01 17:08
Duplicate of #1470

**Closed by hadley** 2016-03-01 17:08 UTC
Labels: database
