### ISSUE TITLE
Dplyr removes vector-attributes

### ISSUE THREAD

**Issue by sjPlot** [hadley/dplyr#1015] opened 2015-03-12 09:00 UTC
In addition to [this issue](https://github.com/hadley/dplyr/issues/859), and taking the new `haven` package into consideration, it would be great if the various `dplyr`-functions also return vector attributes and don't remove them.

**Comment by hadley** [comment] 2015-05-19 16:13
Duplicate of #1105

**Closed by hadley** 2015-05-19 16:13 UTC
