### ISSUE TITLE
Using "" in suffix option for join functions freezes R

### ISSUE THREAD

**Issue by jlegewie** [hadley/dplyr#2037] opened 2016-07-25 16:00 UTC
When I use `""` for the suffix option in any of the join functions freezes R. Below is an example. `suffix = c("_A", "_B")` works without any problems. `suffix = c("", "_B")`, however, freezes R and R eats up lots of resources. The idea of "" is to leave the variable name for one of the tibble's unchanged.

```
library("dplyr")

A <- tibble(id = 1:10, a  = rnorm(10))
B <- tibble(id = 2:11, a = 1, b  = rnorm(10))

A %>% left_join(B, by = "id", suffix = c("_A", "_B"))
A %>% left_join(B, by = "id", suffix = c("", "_B"))
```

```
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.5 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.5.0     svSocket_0.9-57

loaded via a namespace (and not attached):
 [1] lazyeval_0.2.0 magrittr_1.5   R6_2.1.2       assertthat_0.1 DBI_0.4-1      tools_3.3.1    svMisc_0.9-70  tibble_1.1     Rcpp_0.12.6   
[10] tcltk_3.3.1  
```

**Comment by bragil-massoud** [comment] 2016-08-09 09:40
Some observations:

```
  df1 = data_frame(a=1)
  df2 = data_frame(a=1, b=2)
  inner_join(df1, df2, by=c("a" = "a"), suffix=c("", ".y"))
```

works (probably as no suffix has to be added)

while

```
  df1 = data_frame(a=1, b=2)
  df2 = data_frame(a=1, b=2)
  inner_join(df1, df2, by=c("a" = "a"), suffix=c("", ".y"))
```
allocates memory infinitely.

**Comment by hadley** [comment] 2016-08-09 12:34
Duplicate of #2007

**Closed by hadley** 2016-08-09 12:34 UTC
