### ISSUE TITLE
Unexpected result from left_join

### ISSUE THREAD

**Issue by caijun** [hadley/dplyr#1998] opened 2016-07-06 15:27 UTC
The following is a reproducible example that using `dplyr::left_join()` in my data cleaning produced unexpected result.

```
> rm(list = ls())
> 
> library(dplyr)
> 
> load(url("http://tonytsai.name/area.RData"))
> ls()
[1] "area.crct" "area.name"
> subset(area.crct, area1 == "大兴安岭地区")
# A tibble: 2 x 2
          area        area1
         <chr>        <chr>
1   大兴安岭地 大兴安岭地区
2 大兴安岭地区 大兴安岭地区
> subset(area.name, area1 == "大兴安岭地区")
# A tibble: 1 x 2
         area1        area2
         <chr>        <chr>
1 大兴安岭地区 大兴安岭地区
> str(area.crct)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':   691 obs. of  2 variables:
 $ area : chr  "七台河" "七台河市" "三亚" "三亚市" ...
 $ area1: chr  "七台河" "七台河市" "三亚" "三亚市" ...
> str(area.name)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':   688 obs. of  2 variables:
 $ area1: chr  "七台河" "七台河市" "三亚" "三亚市" ...
 $ area2: chr  "七台河市" "七台河市" "三亚市" "三亚市" ...
> area.tbl <- left_join(area.crct, area.name, by = "area1")
> subset(area.tbl, is.na(area1))
# A tibble: 2 x 3
          area area1 area2
         <chr> <chr> <chr>
1 大兴安岭地区  <NA>  <NA>
2         襄阳  <NA>  <NA>
> 
> write.csv(area.crct, file = "area_crct.csv", quote = F, row.names = F)
> write.csv(area.name, file = "area_name.csv", quote = F, row.names = F)
> area.crct <- tbl_df(read.csv("area_crct.csv", stringsAsFactors = F))
> area.name <- tbl_df(read.csv("area_name.csv", stringsAsFactors = F))
> str(area.crct)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':   691 obs. of  2 variables:
 $ area : chr  "七台河" "七台河市" "三亚" "三亚市" ...
 $ area1: chr  "七台河" "七台河市" "三亚" "三亚市" ...
> str(area.name)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':   688 obs. of  2 variables:
 $ area1: chr  "七台河" "七台河市" "三亚" "三亚市" ...
 $ area2: chr  "七台河市" "七台河市" "三亚市" "三亚市" ...
> area.tbl <- left_join(area.crct, area.name, by = "area1")
> subset(area.tbl, is.na(area1))
# A tibble: 0 x 3
# ... with 3 variables: area <chr>, area1 <chr>, area2 <chr>
> 
> area.tbl <- merge(area.crct, area.name, by = "area1", all.x = T)
> subset(area.tbl, is.na(area1))
[1] area1 area  area2
<0 rows> (or 0-length row.names)
```

As shown in above example results, it's weird that the variable to join by, `area1` is NA when `left_join()` with RData; however, after writing the variables `area.crct` and `area.name` into csv and reading them into again, `left_join()` produces the correct result that is same to `merge()`.

**Comment by uhkeller** [comment] 2016-10-07 10:27
#1898

**Comment by caijun** [comment] 2016-10-07 14:03
Yes, it is related to the encoding of Chinese characters.

**Comment by krlmlr** [comment] 2016-11-07 22:54
We're working on this problem. For now please ensure that all your character data is encoded in UTF-8, but all your column names are encoded as "native", which is *not* UTF-8 on Windows.

**Comment by krlmlr** [comment] 2016-11-08 07:16
Closing, duplicate of #1885.

**Closed by krlmlr** 2016-11-08 07:16 UTC
