### ISSUE TITLE
type_of() in select()

### ISSUE THREAD

**Issue by bhive01** [hadley/dplyr#1490] opened 2015-10-30 17:48 UTC
Working on a complex dataset with text fields and numeric data. I need to split my dataset into two, summarize and rejoin. I need to be able to quickly select out the numeric columns and one other column (for grouping, summarizing and joining later), and then negate this for the other types. 

My suggestion is a type_of() selection function to be able to put in the type of data. 
select(DF, which(sapply(DF, typeof) == "double"))

From: https://stat.ethz.ch/R-manual/R-devel/library/base/html/typeof.html
"logical", "integer", "double", "complex", "character", "raw" and "list", "NULL", "closure"

Note: this doesn't work :/
```r
type_of <- function(vars, match, ignore.case = TRUE) {
  if (ignore.case) match <- tolower(match) 
  if (match == "numeric") {match <- c("integer", "double", "complex")} 
  possibletypes <- c("logical", "integer", "double", "complex", "character", "raw", "list", "NULL", "closure")
 
  stopifnot(is.string(match), !is.na(match), nchar(match) > 0, !match %in% possibletypes)
  
  which(sapply(., typeof) == match))  # won't work, see below
} 

#looking at the code in
# https://github.com/hadley/dplyr/blob/dd10ccd543a2bea99573e6622b46d50f657b0c1f/R/select-vars.R # https://github.com/hadley/dplyr/blob/dd10ccd543a2bea99573e6622b46d50f657b0c1f/R/select-utils.R
# https://github.com/hadley/dplyr/blob/master/src/select.cpp
# the sub-selection functions appear to only see column names of the columns as "vars".
```r

**Comment by hadley** [comment] 2015-10-30 18:14
Duplicate of #497

**Closed by hadley** 2015-10-30 18:14 UTC
