### ISSUE TITLE
Visibility of select() helper functions with ?

### ISSUE THREAD

**Issue by bhive01** [hadley/dplyr#1419] opened 2015-09-21 16:01 UTC
Was helping someone on the ggplot mailing list this morning and realized that the select's helper functions aren't visible, which means you can type them in and ask for help, but they aren't there. 

?starts_with
??starts_with 
and so on... 

They are there in ?select, but it took me a minute to realize that. I was looking for the grep-like function matches(), but didn't know what it was called. Is there a way to make them more visible? Or perhaps have them pull up ?select when called with ?* ?

**Comment by hadley** [comment] 2015-09-21 16:15
Duplicate of #1410 ;)

**Closed by hadley** 2015-09-21 16:15 UTC
