### ISSUE TITLE
potential bug in dplyr joins, behavior differs depending on datasource

### ISSUE THREAD

**Issue by wabarr** [hadley/dplyr#1458] opened 2015-10-16 19:44 UTC
I may have identified circumstances where join behavior depends on the data source.

I can join the following tables very easily using dplyr.  

```
observation <- data.frame(id=101:105, specimen_id=1:5, variable_id=1:5, value=rnorm(5))
specimen <- data.frame(id=1:5, specimen_name=LETTERS[1:5], species_id=1:5)
species <- data.frame(id=1:5, species_name=LETTERS[11:15])
variable <- data.frame(id=1:5, variable_name=LETTERS[6:10])

observation %>% 
  left_join(specimen, by=c("specimen_id"="id")) %>%
  left_join(species, by=c("species_id"="id")) %>%
  left_join(variable, by=c("variable_id"="id")) 
```

Result is

```
   id specimen_id variable_id      value specimen_name species_id species_name variable_name
1 101           1           1 -0.6782149             A          1            K             F
2 102           2           2 -1.3226305             B          2            L             G
3 103           3           3 -0.2670939             C          3            M             H
4 104           4           4 -1.2546326             D          4            N             I
5 105           5           5 -1.1453585             E          5            O             J
```

**However, if I copy the same dataframes to a sqlite data source, the identical join code will fail.** 

```
#create a database locally, and copy the dataframes
my_db <- src_sqlite("my_db.sqlite3", create = T)

copy_to(my_db, df=observation, temporary = FALSE)
copy_to(my_db, df=specimen, temporary = FALSE)
copy_to(my_db, df=species, temporary = FALSE)
copy_to(my_db, df=variable, temporary = FALSE)

#connect to those tables using dplyr
observation <- tbl(my_db, "observation")
specimen <- tbl(my_db, "specimen")
species <- tbl(my_db, "species")
variable <- tbl(my_db, "variable")
```

Now, the identical join code will fail.

```
observation %>% 
  left_join(specimen, by=c("specimen_id"="id")) %>%
  left_join(species, by=c("species_id"="id")) %>%
  left_join(variable, by=c("variable_id"="id")) 
```

**Results in the following error:**

```
Error in sqliteSendQuery(conn, statement) : 
 error in statement: ambiguous column name: id.y
```

**Comment by hadley** [comment] 2015-10-21 21:47
Possibly related to #1460

**Comment by krlmlr** [comment] 2016-11-08 08:05
I'm still seeing this with current master.

**Comment by hadley** [comment] 2017-02-20 17:07
Duplicate of #2410

**Closed by hadley** 2017-02-20 17:07 UTC
Labels: bug, database
