### ISSUE TITLE
matches() returns negative indices

### ISSUE THREAD

**Issue by ThomasSiegmund** [hadley/dplyr#1982] opened 2016-06-29 07:32 UTC
Hi,

when matches() doesn't find a match, it returns negative indices. 

```r
dplyr::matches("z", vars=c("x", "y"))
[1] 2
dplyr::matches("z", vars=c("x", "y"))
[1] -1 -2
```

Inside of a select this can result in no column selected, just because one matches() misses. This behaviour is new in dplyr 0.5.

```r
iris %>% tbl_df() %>% select(Species, matches("Width"), matches("Height"))
Source: local data frame [150 x 0]
```

**Comment by hadley** [comment] 2016-06-29 14:19
Duplicate of #1973

**Closed by hadley** 2016-06-29 14:19 UTC
