### ISSUE TITLE
do(lm()) doesn't work with tbl_dt

### ISSUE THREAD

**Issue by kismsu** [hadley/dplyr#849] opened 2014-12-15 14:49 UTC
Hi, I've noticed that you can't use lm in do for tbl_dt objects

```
models <- mtcars %>%
  tbl_dt() %>%
  group_by(cyl) %>% 
  do(
    mod = lm(mpg ~ disp, data = .)
  ) %>%
  do(data.frame(coef = coef(.$mod)))
```

I think because you're converting tbl_dt to data.frame in do.tbl_dt.

**Comment by hadley** [comment] 2015-11-04 17:23
Duplicate of #1081

**Closed by hadley** 2015-11-04 17:23 UTC
