### ISSUE TITLE
mutate fails with empty name-value pair

### ISSUE THREAD

**Issue by davidlockhart** [hadley/dplyr#1838] opened 2016-05-18 21:34 UTC
test.df <- data.frame(x = 1:2, y=3:4)
mutate(test.df,
          z = x+y,
          w = x-y,
       )

produces the error message:
Error in mutate_impl(.data, dots) : 
  attempt to use zero-length variable name

It would be really nice if this were just gracefully parsed away, perhaps with a warning, or if necessary gave a more informative error.  When I googled the message I found lots of suggestions of empty dataframe column names due to ingestion errors, which became rather a snipe hunt, but no suggestions that it could be an empty new variable name, which would have pointed me in a better direction.

**Comment by hadley** [comment] 2016-05-26 13:32
Duplicate of #1039

**Closed by hadley** 2016-05-26 13:32 UTC
