### ISSUE TITLE
summarise_if and mutate_if treat numeric column names as indices

### ISSUE THREAD

**Issue by dayey1** [hadley/dplyr#2424] opened 2017-02-14 19:18 UTC
When data frame has column names that are numeric, mutate_if and summarise_if return the wrong columns:

```{r}
library(dplyr)
tibble(char_col = 'chr', `1` = 1, `2` = 2) %>% summarise_if(is.numeric, is.numeric)
#> # A tibble: 1 × 2
#>   char_col   `1`
#>      <lgl> <lgl>
#> 1    FALSE  TRUE
```
```{r}
library(dplyr)
tibble(char_col = 'chr', `1` = 1, `2` = 2) %>% mutate_if(is.numeric, is.numeric)
#> # A tibble: 1 × 3
#>   char_col   `1`   `2`
#>      <lgl> <lgl> <dbl>
#> 1    FALSE  TRUE     2
```

**Comment by hadley** [comment] 2017-02-14 19:26
Duplicate of #2243

**Closed by hadley** 2017-02-14 19:26 UTC
