### ISSUE TITLE
dplyr crashes r session with incorrect filter() syntax

### ISSUE THREAD

**Issue by ronammar** [hadley/dplyr#1900] opened 2016-06-08 15:00 UTC
Couldn't figure out if this had already been resolved, so posting:

```r
library(dplyr)
mtcars %>% filter(mpg > 8)  # works
mtcars %>% filter(mtcars, mpg > 8)  # crashes
```
Thanks!

**Comment by hadley** [comment] 2016-06-08 16:20
Basically a duplicate of #1870

**Closed by hadley** 2016-06-08 16:20 UTC

**Comment by krlmlr** [comment] 2016-06-20 12:27
Not anymore, with the most recent dev version I'm getting:

```
> mtcars %>% filter(mtcars, mpg > 8) 
Error: incorrect length (352), expecting: 32
```

We could explicitly test for a matrix, but at least it doesn't crash anymore.
