### ISSUE TITLE
filter does not work on renamed fields via postgres

### ISSUE THREAD

**Issue by einarhjorleifsson** [hadley/dplyr#1322] opened 2015-08-14 15:12 UTC
When using `rename` when communicating with postgres, `select` works on the renamed fields while `filter` does not.

See details below: 

```r
library(dplyr)
Test_Table <- data_frame(ID = c(10,20), NAME = c("Einar", "Bjorn"))
Test_Table %>%
  rename(id = ID, name = NAME) %>%
  select(id) %>%
  filter(id == 20)
```

```
## Source: local data frame [1 x 1]
## 
##   id
## 1 20
```
Expected to be able to do similar via postgres:
```r
db <- src_postgres('test')
copy_to(db, Test_Table, temporary = FALSE)
rm(Test_Table)

q <- tbl(db,'Test_Table') %>%
  rename(id = ID, name = NAME) %>%
  select(id) 
q
```

```
## Source: postgres 9.3.6 [einarhj@localhost:5432/test]
## From: Test_Table [2 x 1]
## 
##   id
## 1 10
## 2 20
```
OK, above works as expected. But below not:
```r
q %>% filter(id == 20)
```

```
## Source: postgres 9.3.6 [einarhj@localhost:5432/test]
```

```
## Warning in postgresqlQuickSQL(conn, statement, ...): Could not create executeSELECT count(*) FROM (SELECT "ID" AS "id"
## FROM "Test_Table"
## WHERE "id" = 20.0) AS "master"
```

```
## From: Test_Table [1]
## Filter: id == 20
```

```
## Error in postgresqlExecStatement(conn, statement, ...): RS-DBI driver: (could not Retrieve the result : ERROR:  column "id" does not exist
## LINE 3: WHERE "id" = 20.0
##               ^
## )
```

```r
devtools::session_info()
```

regards,
einar

```
## Session info --------------------------------------------------------------
```

```
##  setting  value                       
##  version  R version 3.1.2 (2014-10-31)
##  system   x86_64, linux-gnu           
##  ui       X11                         
##  language (EN)                        
##  collate  en_US.UTF-8                 
##  tz       Atlantic/Reykjavik          
##  date     2015-08-14
```

```
## Packages ------------------------------------------------------------------
```

```
##  package     * version date       source                            
##  assertthat    0.1     2013-12-06 CRAN (R 3.0.1)                    
##  DBI           0.3.1   2014-09-24 CRAN (R 3.1.2)                    
##  devtools      1.9.0   2015-08-10 Github (hadley/devtools@2881db5)  
##  digest        0.6.8   2014-12-31 CRAN (R 3.1.2)                    
##  dplyr       * 0.4.2   2015-06-16 CRAN (R 3.1.2)                    
##  evaluate      0.7     2015-04-21 CRAN (R 3.1.2)                    
##  formatR       1.2     2015-04-21 CRAN (R 3.1.2)                    
##  htmltools     0.2.6   2014-09-08 CRAN (R 3.1.1)                    
##  knitr         1.10.12 2015-06-22 Github (yihui/knitr@1df6eee)      
##  lazyeval      0.1.10  2015-01-02 CRAN (R 3.1.2)                    
##  magrittr      1.5     2014-11-22 CRAN (R 3.1.2)                    
##  memoise       0.2.1   2014-04-22 CRAN (R 3.1.2)                    
##  R6            2.1.0   2015-07-04 CRAN (R 3.1.2)                    
##  Rcpp          0.12.0  2015-07-25 CRAN (R 3.1.2)                    
##  rmarkdown     0.7     2015-06-22 Github (rstudio/rmarkdown@82fde67)
##  RPostgreSQL   0.4     2013-03-27 CRAN (R 3.1.2)                    
##  stringi       0.5-5   2015-06-29 CRAN (R 3.1.2)                    
##  stringr       1.0.0   2015-04-30 CRAN (R 3.1.2)                    
##  yaml          2.1.13  2014-06-12 CRAN (R 3.1.2)
```

**Comment by hadley** [comment] 2015-08-24 22:03
Duplicate of #983

**Closed by hadley** 2015-08-24 22:03 UTC
