### ISSUE TITLE
[summarise_all] Spaces in grouping column names break the function

### ISSUE THREAD

**Issue by mr-majkel** [hadley/dplyr#2400] opened 2017-01-31 20:55 UTC
Hi, it seems that summarise_all (I have not tested other "underscored" functions) doesn't work when data.frame is grouped by a column that has a space in the name. It throws an error:
`Error in summarise_impl(.data, dots) : cannot modify grouping variable`

Example for replication (dplyr 0.5.0):
```
# With space - throws an error
iris %>% mutate(`Species B` = Species) %>% group_by(Species, `Species B`) %>% summarize_all(mean)

# Without space - works
iris %>% mutate(`Species_B` = Species) %>% group_by(Species, `Species_B`) %>% summarize_all(mean)
```

**Comment by hadley** [comment] 2017-01-31 22:52
Duplicate of #2243

**Closed by hadley** 2017-01-31 22:52 UTC
