### ISSUE TITLE
Error selecting columns in a data_frame with duplicate names

### ISSUE THREAD

**Issue by tchakravarty** [hadley/dplyr#1627] opened 2016-01-19 06:42 UTC
_Cross-posted from [here](http://stackoverflow.com/questions/34870094/dplyr-error-selecting-columns-with-duplicate-names)._

Since `data_frame` does not check variable names, it is possible to define a `data_frame` with duplicate column names. But, when trying to select columns based on column names, `dplyr` complains that there are duplicate names even when there is no ambiguity about the selection. 

For example, in the selection below, even though there are two columns with the name `var3`, given the desired selection, **both** would need to be dropped, so it is not clear why `dplyr` complains, and whether it should.

    df_x = data_frame(var1 = rnorm(100), 
               var2 = rnorm(100),
               var3 = rnorm(100), 
               var3 = rnorm(100))
    
    df_x %>% 
      select(var1:var2)

**Comment by hadley** [comment] 2016-01-19 14:31
Duplicate of #1562

**Closed by hadley** 2016-01-19 14:31 UTC
