### ISSUE TITLE
error: install_github("hadley/dplyr")

### ISSUE THREAD

**Issue by lixinyao** [hadley/dplyr#1954] opened 2016-06-22 07:05 UTC
```
> session_info()
Session info ------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.0 (2016-05-03)
 system   x86_64, darwin13.4.0        
 ui       RStudio (0.99.902)          
 language (EN)                        
 collate  zh_CN.UTF-8                 
 tz       Asia/Shanghai               
 date     2016-06-22                  

Packages ----------------------------------------------------------------------------
 package    * version    date       source                          
 assertthat   0.1        2013-12-06 CRAN (R 3.3.0)                  
 curl         0.9.7      2016-04-10 CRAN (R 3.3.0)                  
 DBI        * 0.4-1      2016-05-08 CRAN (R 3.3.0)                  
 devtools   * 1.11.1     2016-04-21 CRAN (R 3.3.0)                  
 digest       0.6.9      2016-01-08 CRAN (R 3.3.0)                  
 dplyr      * 0.4.3      2015-09-01 CRAN (R 3.3.0)                  
 git2r        0.15.0     2016-05-11 CRAN (R 3.3.0)                  
 httr         1.2.0      2016-06-15 CRAN (R 3.3.0)                  
 knitr        1.13       2016-05-09 CRAN (R 3.3.0)                  
 lazyeval     0.2.0.9000 2016-06-22 Github (hadley/lazyeval@c155c3d)
 magrittr     1.5        2014-11-22 CRAN (R 3.3.0)                  
 memoise      1.0.0      2016-01-29 CRAN (R 3.3.0)                  
 R6           2.1.2      2016-01-26 CRAN (R 3.3.0)                  
 Rcpp         0.12.5     2016-05-14 CRAN (R 3.3.0)                  
 RMySQL     * 0.10.9     2016-05-08 CRAN (R 3.3.0)                  
 stringi      1.1.1      2016-05-27 CRAN (R 3.3.0)                  
 stringr    * 1.0.0      2015-04-30 CRAN (R 3.3.0)                  
 tibble       1.0        2016-03-23 CRAN (R 3.3.0)                  
 tidyr      * 0.5.1      2016-06-14 CRAN (R 3.3.0)                  
 withr        1.0.2      2016-06-20 CRAN (R 3.3.0)                  
> install_github("hadley/dplyr")
Downloading GitHub repo hadley/dplyr@master
from URL https://api.github.com/repos/hadley/dplyr/zipball/master
Installing dplyr
Downloading GitHub repo hadley/dtplyr@master
from URL https://api.github.com/repos/hadley/dtplyr/zipball/master
Installing dtplyr
Downloading GitHub repo hadley/dplyr@master
from URL https://api.github.com/repos/hadley/dplyr/zipball/master
Installing dplyr
Downloading GitHub repo hadley/dtplyr@master
from URL https://api.github.com/repos/hadley/dtplyr/zipball/master
Installing dtplyr
Downloading GitHub repo hadley/dplyr@master
from URL https://api.github.com/repos/hadley/dplyr/zipball/master
Installing dplyr
Downloading GitHub repo hadley/dtplyr@master
from URL https://api.github.com/repos/hadley/dtplyr/zipball/master
Installing dtplyr
Downloading GitHub repo hadley/dplyr@master
from URL https://api.github.com/repos/hadley/dplyr/zipball/master
Installing dplyr
Downloading GitHub repo hadley/dtplyr@master
from URL https://api.github.com/repos/hadley/dtplyr/zipball/master

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Operation was aborted by an application callback
```

I can't install. Is it wrong here? `hadley/dtplyr@master`

**Comment by kleinschmidt** [comment] 2016-06-22 17:36
Duplicate of #1948

**Closed** 2016-06-22 23:23 UTC
