### ISSUE TITLE
median() fails if it produces numeric and integer vectors

### ISSUE THREAD

**Issue by pfabri** [hadley/dplyr#1909] opened 2016-06-12 21:14 UTC
This is a rather elusive one, which does unfortunately affect the current development version, dplyr_0.4.3.9001. I trust it is related to #1908.
## Repex:

**Problem demonstration**

This works (notice the values in the dataframe):

```
test <- data.frame(id = rep(1:4, each = 2),
                   value = as.integer(c(NA, NA, 2, 3, 3, 5, 21, 0)))

median.mutate <- test %>% 
                 group_by(id) %>% 
                 mutate(median = median(value, na.rm = TRUE)) %>% 
                 print()
#>
Source: local data frame [8 x 3]
Groups: id [4]

    id value median
    <int> <int>  <dbl>
1     1    NA     NA
2     1    NA     NA
3     2     2    2.5
4     2     3    2.5
5     3     3    4.0
6     3     5    4.0
7     4    21   10.5
8     4     0   10.5
```

But `median.mutate` will fail with each of the following dataframes, in which the only change is the number/position of NAs. The error returned is:  
**`Error: incompatible types, expecting a numeric vector`**

```
test <- data.frame(id = rep(1:4, each = 2),  # one NA only
                   value = as.integer(c(NA, 6, 2, 3, 3, 5, 1, 1)))

test <- data.frame(id = rep(1:4, each = 2),  # original + 1 additional NA
                   value = as.integer(c(NA, NA, 2, 3, 3, 5, NA, 1)))

test <- data.frame(id = rep(1:4, each = 2),  # two NAs at random positions
                   value = as.integer(c(NA, 5, 2, 3, 3, 5, NA, 1)))

test <- data.frame(id = rep(1:4, each = 2),  # two NAs at the end
                   value = as.integer(c(4, 3, 2, 3, 3, 5, NA, NA)))

test <- data.frame(id = rep(1:4, each = 2),  # one NA in random position
                   value = as.integer(c(4, 3, 2, 3, NA, 5, 1, 3)))

test <- data.frame(id = rep(1:4, each = 2),  # random group filled with NAs
                   value = as.integer(c(4, 3, 2, 3, NA, NA, 1, 3)))
```

What's really perplexing is that using `do` instead works with all of them, and so does the same chain, if instead of `median` one uses `mean` (this is why I believe it's related to #1908)

```
# Work with all of the above
median.do <- test %>% 
             group_by(id) %>% 
             do(mutate(., median = median(value, na.rm = TRUE))) %>% 
             print()

# Using 'mean' instead of 'median' also works with all of the above
mean.mutate <- test %>% 
                 group_by(id) %>% 
                 mutate(mean = mean(value, na.rm = TRUE)) %>% 
                 print()
```

Many thanks in advance for looking into this.

**Comment by krlmlr** [comment] 2016-11-07 23:48
Thanks. Does #2209 resolve this issue?

```r
devtools::install_github("hadley/dplyr#2209")
```

**Comment by hadley** [comment] 2017-02-09 20:38
I still see a failure with this reprex:

```R
test <- data_frame(
  id = rep(1:4, each = 2),
  value = as.integer(c(NA, 6, 2, 3, 3, 5, 1, 1))
)

test %>% 
  group_by(id) %>% 
  mutate(median = median(value, na.rm = TRUE))
```

**Comment by hadley** [comment] 2017-02-27 00:05
Minimal reprex:

```R
df <- tibble(
  g = c(1, 2, 2), 
  x = c(1L, 2L, 3L)
)

df %>%
  group_by(g) %>%
  mutate(median(x))
```

**Comment by hadley** [comment] 2017-02-27 00:07
Duplicate of #1892

**Closed by hadley** 2017-02-27 00:07 UTC
Labels: bug, vector
