### ISSUE TITLE
Arrange no longer sort on Netezza

### ISSUE THREAD

**Issue by philippechataignon** [hadley/dplyr#1979] opened 2016-06-28 16:07 UTC
Since dplyr 0.5.0, arrange no longer return sorted rows.

For example :

```
> aud %>% count(EVT, sort=T)
Source:   query [?? x 2]
Database: Netezza ODBC [NZN]

       EVT       n
     <chr>   <int>
1  TRANSFE       4
2  REQPENA      29
3   RENVOI   16126
4  AVISAUD    3753
5    FIXER 5444085
6   RENCIV      21
7  CONVJUG    2507
8  AVVICPC      86
9  CONVIMJ       7
10 COPJMEX    1574
..     ...     ...
```

show_query is correct :

```
> aud %>% count(EVT, sort=T) %>% show_query
<SQL>
SELECT *
FROM (SELECT "EVT", count(*)::integer AS "n"
FROM "DQ_AUD"
GROUP BY "EVT") "tikjjcfmkj"
ORDER BY "n" DESC
```

But the real query is this  :

```
SELECT * FROM 
  (SELECT * FROM 
    (SELECT "EVT", count(*)::integer AS "n" 
     FROM "DQ_AUD" GROUP BY "EVT"
    ) "jttsguvcce"
    ORDER BY "n" DESC
) "tnsoliurid" ;
```

The inside subquery ("tnsoliurid") returns an ordered table but the `select * from` lost order on Netezza (not with Postgresql) because it has no ORDER BY clause.

Before 0.5.0, query was :

```
SELECT "EVT", "n" FROM 
  (SELECT "EVT", count(*)::integer AS "n" FROM "DQ_AUD" GROUP BY "EVT") AS "zzz1" 
ORDER BY "n"
```

**Comment by benjaminrobinson** [comment] 2016-06-28 16:18
See #1206.

**Comment by philippechataignon** [comment] 2016-06-28 16:31
#1206 is about grouping and arrange. 

A simple arrange on a ungrouped table doesn't work : it's a change in the SQL query generation and the issue is related on the fact that, on Netezza, `select * from (sorted table)` isn't sorted. dplyr 0.5.0 seems to add such a (useless) statement.

**Comment by benjaminrobinson** [comment] 2016-06-28 16:36
`count` does create a grouping if I'm not mistaken?

**Comment by hhoeflin** [comment] 2016-07-11 08:56
I am running into the same issue on a vertica database. In my case, it occurs if you are asking for the first x rows of a sorted table. Using the sql_lite example with nycflights from the tuturials, the code I use is:

```
library(dplyr)
library(nycflights13)
flights_sqlite <- tbl(nycflights13_sqlite(), "flights")
flights_arranged <- arrange(flights_sqlite, desc(dep_delay))
flights_head <- head(flights_arranged, 5)
```

with the generated query as

```
> show_query(flights_head)
<SQL>
SELECT *
FROM (SELECT *
FROM `flights`
ORDER BY `dep_delay` DESC)
LIMIT 5
```

The issue is that the limit statement isn't attached directly attached after the ORDER_BY clause, but instead the ORDER_BY clause gets put into a subquery, and the outer query has the LIMIT clause. However, SQL does not guarantee that with such a statement, the ordering is retained. This is especially a problem on distributed databases such as VERTICA. 

From

[SubqueryRestriction in Vertica](https://my.vertica.com/docs/7.1.x/HTML/Content/Authoring/AnalyzingData/Queries/SubqueryRestrictions.htm
)

> If the ORDER BY clause is inside a FROM clause subquery, rather than in the containing query, the query could return unexpected sort results. This is because HP Vertica data comes from multiple nodes, so sort order cannot be guaranteed unless an ORDER BY clause is specified in the outer query block. This behavior is compliant with the SQL standard but it might differ from other databases.
 
I believe this could be fixed by making a change to the select_query function. Currently, when select_query is passed a select_query object in its from clause, it just wraps another select_query object around it - even if the inner select_query object could be amended with additional information. 

Amending select_query objects instead of nesting them may fix the issue?

**Comment by hhoeflin** [comment] 2016-07-12 08:30
A further note: Researching this a little more, it seems that the SQL created above

> show_query(flights_head)
<SQL>
SELECT *
FROM (SELECT *
FROM `flights`
ORDER BY `dep_delay` DESC)
LIMIT 5

Is in fact invalid on some implementations such as SQL Server

**Comment by hhoeflin** [comment] 2016-07-13 12:27
Here is a suggestion for a possible fix. First, lets look at the logical processing order of sql queries

https://msdn.microsoft.com/en-us/library/ms189499.aspx

The link is for SQL server, but I think (is this true??) this holds in general (where instead of "top" we usually have "limit").

Then, we can solve the issue by optimizing the result of sql_build before it is passed into sql_render

```
sql_render_optimize <- function(query, con=NULL, ...) {
    if(!inherits(query, "tbl_sql")) {
        stop("sql_render_optimize can only be used with tbl_sql objects")
    }

    sql_render(sql_optimizer(sql_build(query$ops, query$src$con, ...)), con = query$src$con, 
               ...)
}
```

The sql_optimizer here is very basic. It looks at the output of sql_build, and whenver it encounters nested "select_query" objects, it checks the following:
If all clauses of the outer query occur *after* all clauses of the inner query according to the logical processing order, then the clauses of the outer query can be attached to the clauses of the inner query.

In code: 
```
sql_optimizer <- function(x) {
    if(inherits(x, "select_query") && inherits(x$from, "select_query")) {
        x$from <- sql_optimizer(x$from)
        outer_clauses <- select_query_clauses(x)
        inner_clauses <- select_query_clauses(x$from)
        if(all(outer_clauses > inner_clauses)) {
            new_x <- x$from
            new_x[as.character(outer_clauses)] <- x[as.character(outer_clauses)]
            x <- new_x
        }
    }
    return(x)
}

```

Here select_query_clauses returns an "ordered" vector that encodes all the clauses that are present in the select_query object (here a select-clause that only consists of a "*" is being taken as the same as this clause not being set at all). 

```
select_query_clauses <- function(x) {
    clauses_present <- character(0)
    if(!is.null(x$where ) && length(x$where) > 0) {
        clauses_present <- c(clauses_present, "where")
    }

    if(!is.null(x$group_by ) && length(x$group_by) > 0) {
        clauses_present <- c(clauses_present, "group_by")
    }
    
    if(!is.null(x$having ) && length(x$having) > 0) {
        clauses_present <- c(clauses_present, "having")
    }

    if(!is.null(x$select) && length(x$select) > 0 && (length(x$select) > 1 || x$select[1] != "*")) {
        clauses_present <- c(clauses_present, "select")
    }

    if(x$distinct) {
        clauses_present <- c(clauses_present, "distinct")
    }

    if(!is.null(x$order_by) && length(x$order_by) > 0) {
        clauses_present <- c(clauses_present, "order_by")
    }

    if(!is.null(x$limit) && length(x$limit) > 0) {
        clauses_present <- c(clauses_present, "limit")
    }

    clauses_present <- ordered(clauses_present, levels=c("where", "group_by", "having", "select", "distinct", "order_by", "limit"))
    return(clauses_present)    
}

```

For the nycflights example above, the SQL then becomes

> <SQL> SELECT *
> FROM "flights"
> ORDER BY "dep_delay" DESC
> LIMIT 5
> 

instead of 

> <SQL>
> SELECT *
> FROM (SELECT *
> FROM `flights`
> ORDER BY `dep_delay` DESC)
> LIMIT 5

**Comment by hadley** [comment] 2016-07-13 12:38
This looks like a fantastic approach - thanks! I'll take when I'm working on dplyr again in the next couple of weeks.

**Comment by hhoeflin** [comment] 2016-07-14 02:30
Cool - thanks. A note though - it is not quite correct as it is. The approach doesn't optimize the SQL in join queries, semi_join_queries or set_op_queries. Problably dispatching on S3 class of its argument would be best here ...

**Comment by hadley** [comment] 2017-02-21 22:46
This optimisation works better than my understanding of SQL

```R
memdb_frame(x = 1, y = 2) %>%
    filter(x == 1) %>%
    select(x = y)
```

Is translated to 

```sql
SELECT `y` AS `x`
FROM `iegppmgmrs`
WHERE (`x` = 1.0)
```

which actually returns the right thing!

**Closed** 2017-02-21 23:26 UTC
Labels: bug, database
