### ISSUE TITLE
bug: group_by() cannot handle a column name with an international character created by separate()

### ISSUE THREAD

**Issue by bbTomas** [hadley/dplyr#1555] opened 2015-11-26 21:51 UTC
The source file encoding is UTF-8. Column "jídlo" created by separate() leads to Error: unknown column 'jídlo' in group_by() function, however the same column "jídlo" created manually (see tab4) works fine.

Thanks,
Tomas

``` r
library(tidyr)
library(dplyr)

tab1 <- data.frame(polevka_1 = 1:4,  hlavni_1 = 2:5, polevka_2 = 3:6,  hlavni_2 = 7:8)
tab2 <- gather(tab1, jidlo_menza, hodnoceni) %>% separate(jidlo_menza, c("jídlo", "menza"))
tab2 %>% group_by(jídlo) %>% summarize(mean(hodnoceni))   # Error: unknown column 'jídlo'

tab3 <- gather(tab1, jidlo_menza, hodnoceni) %>% separate(jidlo_menza, c("jidlo", "menza"))  
tab3 %>% group_by(jidlo) %>% summarize(mean(hodnoceni))  # it works

tab4 <- data.frame(jídlo = rep(c(rep("polevka", 4), rep("hlavni", 4)), 2), menza = c(rep(1, 8), rep(2, 8)), hodnoceni = c(1:4, 2:5, 3:8, 7, 8))
tab4 %>% group_by(jídlo) %>% summarize(mean(hodnoceni))  # it works

# It looks like column 'jídlo' created by separete() function in tab2 has different (hidden?)
# properties than 'jídlo' created by me in tab4.

tab2$jídlo   # ok
tab3$jidlo   # ok
tab4$jídlo   # ok
```

**Comment by hadley** [comment] 2016-03-01 15:46
Can you confirm that this still fails for you with the dev version of dplyr?

**Comment by bbTomas** [comment] 2016-03-02 10:25
It still fails, Error: unknown column 'jídlo'

I have installed the following packages
```{r}
devtools::install_github("hadley/dplyr")
devtools::install_github("hadley/tidyr")
```

**Comment by willmoura** [comment] 2016-04-12 14:02
I was getting the same message error, but when I changed the column name, replacing the character with accent worked fine.

**Comment by hadley** [comment] 2016-05-26 16:19
@bbTomas could you please give the output of `Sys.getlocale()` and tell me what OS you're using? (And this is Czech, right?)

**Comment by bbTomas** [comment] 2016-05-26 19:40
It was Windows 7. Now, it is Windows 10. With the same result.

```
sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=Czech_Czech Republic.1250  LC_CTYPE=Czech_Czech Republic.1250    LC_MONETARY=Czech_Czech Republic.1250 LC_NUMERIC=C                         
[5] LC_TIME=Czech_Czech Republic.1250    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.4.3 tidyr_0.4.1

loaded via a namespace (and not attached):
 [1] lazyeval_0.1.10    magrittr_1.5       R6_2.1.2           assertthat_0.1     rsconnect_0.4.1.11 parallel_3.3.0     DBI_0.4-1          tools_3.3.0       
 [9] Rcpp_0.12.5        stringi_1.0-1     
```

**Comment by krlmlr** [comment] 2016-06-04 11:36
Possibly related: #1885. Could you please check the output of `Encoding()` for the relevant columns?

**Comment by bbTomas** [comment] 2016-06-04 15:39
```{r}
> Encoding(names(tab2))
[1] "UTF-8"   "unknown" "unknown"
> Encoding(names(tab3))
[1] "unknown" "unknown" "unknown"
> Encoding(names(tab4))
[1] "unknown" "unknown" "unknown"
```

**Comment by krlmlr** [comment] 2016-06-04 18:22
Thanks. Definitely the same symptoms as in #1885.

**Comment by krlmlr** [comment] 2016-11-08 07:21
Closing, duplicate of #1950 (and not #1885).

**Closed by krlmlr** 2016-11-08 07:21 UTC
