### ISSUE TITLE
Make bind_cols(), bind_rows() generic

### ISSUE THREAD

**Issue by richierocks** [hadley/dplyr#2534] opened 2017-03-15 16:54 UTC
`bind_cols()` doesn't work for `tbl_spark` objects created by `sparklyr`.  See https://github.com/rstudio/sparklyr/issues/556.

If `bind_cols()` was generic, then`sparklyr` could solve the problem with its own `bind_cols.tbl_spark()` method.

A related problem occurs with `bind_rows()`, which is discussed in https://github.com/hadley/dplyr/issues/2373.

**Comment by hadley** [comment] 2017-03-15 18:51
Duplicate of #2457. Simply making it generic won't work.

**Closed by hadley** 2017-03-15 18:51 UTC
