### ISSUE TITLE
USING clause in SQL variants

### ISSUE THREAD

**Issue by mndrake** [hadley/dplyr#2023] opened 2016-07-18 00:43 UTC
I believe this is related to the root cause of #2022 #1997.

Per http://troels.arvin.dk/db/rdbms/ the `USING` clause is available in:

| Database | USING |
|-----------|-------|
| PostgreSQL | yes |
| DB2 | no |
| MSSQL	| no |
| MySQL	| yes |
| Oracle	| yes |
| Informix | no |

These days I spend most days in Hive and Spark and they also do not support `USING`.

The method `sql_join.default` contains `USING`. In libraries that relied on `dplyr v0.4` the workaround I saw was to use `dplyr::auto_names` to extract the column names and then construct the variable list to keep as the column names of `x` and `y` minus the join keys of `y`.  I cannot seem to find a way of querying the column names anymore within a custom `DBI` `sql_join` method.  Is there any new functionality in `dplyr` that can be used to fix joins for the other SQL variants?

**Comment by hadley** [comment] 2016-07-18 12:31
Duplicate of #1997. Not sure why you filed this issue when it's addressed in that PR. What am I missing?

**Closed by hadley** 2016-07-18 12:31 UTC
