### ISSUE TITLE
Problem with group_by and umlauts

### ISSUE THREAD

**Issue by dapper2dan** [hadley/dplyr#2105] opened 2016-09-01 07:48 UTC
`group_by` stumbles when the variable to group by contains an umlaut. 
Possibly related to #1898 

``` r
> library(dplyr)
# BTW, first time I am noticing the message regarding the masked objects , 
# but I guess this is expected?
Attache Paket: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

> 
> # rename cyl from mtcars to (German) schlüssel
> cars_umlaut  <- mtcars %>% rename(schlüssel = cyl)
> 
> # group by schlüssel
> cars_umlaut  <- mtcars %>% group_by(schlüssel)
Error: unknown variable to group by : schlüssel
> 
> # Enconding does not seem to be the problem here
> # or at least R knows that "schlüssel" is UTF-8
> Encoding((names(cars_umlaut)))
 [1] "unknown" "UTF-8"   "unknown" "unknown" "unknown" "unknown" "unknown" "unknown" "unknown" "unknown" "unknown"
> 
> cars_no_umlaut <- mtcars %>% rename(schluessel = cyl) %>% group_by(schluessel)
> 
> groups(cars_umlaut)
NULL
> groups(cars_no_umlaut)
[[1]]
schluessel

> 
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.5.0  

loaded via a namespace (and not attached):
[1] lazyeval_0.2.0.9000 magrittr_1.5        R6_2.1.3            assertthat_0.1      DBI_0.5            
[6] tools_3.3.1         tibble_1.2          Rcpp_0.12.6   
```

**Comment by krlmlr** [comment] 2016-11-07 21:45
Thanks, confirmed. You should ensure that the names in your data frames are always encoded in the "native" encoding, I agree that it's rename()'s job to ensure this in this particular case.

**Comment by krlmlr** [comment] 2016-11-08 07:15
Closing, duplicate of #1950.

**Closed by krlmlr** 2016-11-08 07:15 UTC
Labels: bug
