### ISSUE TITLE
select_if doesn't work on columns that contain spaces

### ISSUE THREAD

**Issue by double-y** [hadley/dplyr#2044] opened 2016-07-30 05:56 UTC
Hi

select_if doesn't seem to work on columns which contain spaces

To this dataset,
http://datascienceplus.com/wp-content/uploads/2016/07/dataset_HD_euro2016.csv

``` r
select_if(is.numeric)
> Error in parse(text = x) : <text>:1:7: unexpected symbol 1: Total goals ^
```

Doesn't work but

``` r
rename(Totalgoals = `Total goals`)
select_if(is.numeric)
```

Works

**Comment by izahn** [comment] 2016-08-25 04:18
http://stackoverflow.com/questions/39134602/how-to-pass-column-names-in-dplyr-select-without-evaluation might be the same problem. Here is a very simple example thanks to http://stackoverflow.com/users/496803/thelatemail

`dat <- data.frame(`A B`=1:3,check.names=FALSE); select_(dat, "A B")`

**Comment by krlmlr** [comment] 2016-11-07 23:03
Is this a duplicate of #1978?

**Comment by krlmlr** [comment] 2016-11-08 00:09
@hadley: Column names with spaces make a fairly large cluster, too. Okay to link+close?

**Comment by hadley** [comment] 2016-11-08 13:13
Yes, please.

**Comment by krlmlr** [comment] 2016-11-08 15:06
Duplicate of #1978.

**Closed by krlmlr** 2016-11-08 15:06 UTC

**Comment by krlmlr** [comment] 2016-11-08 15:16
#2243 groups all related issues.
