### ISSUE TITLE
dplyr/Rstudio crashes with mutate, filter, slice, summarise, and arrange on windows 32-bit R 3.3.0

### ISSUE THREAD

**Issue by marcmtk** [hadley/dplyr#1881] opened 2016-06-02 14:22 UTC
On windows 32-bit R 3.3.0 (patched and unpatched) the following lines reliably crash (as in "Fatal error", need to restart R session) when run in RStudio (v 0.99.902), but not when run in RGui.exe (where they produce the expected error message)

```r
dplyr::mutate(mtcars, stop("Induced crash"))
dplyr::summarise(mtcars, stop("Induced crash"))
dplyr::arrange(mtcars, stop("Induced crash"))
dplyr::filter(mtcars, stop("Induced crash"))
dplyr::slice(mtcars, stop("Induced crash"))
dplyr::distinct(mtcars, stop("Induced crash"))
dplyr::group_by(mtcars, stop("Induced crash"))
```

Select, frac_n, top_n, left_join, intersect, rename and bind_cols seems unaffected

I believe this bug is related to these two, as they seem to involve error handling in RStudio of dplyr functions.
https://github.com/hadley/dplyr/issues/1835 - this only crashes RStudio for me.
https://github.com/hadley/dplyr/issues/1832 - this only crashes RStudio for me.

It might also be related to https://github.com/hadley/dplyr/issues/1870 but that example crashes both RGui and RStudio for me.

**Comment by hadley** [comment] 2016-06-02 14:35
Duplicate of #1835 and please note https://github.com/hadley/dplyr/issues/1832#issuecomment-221635608

**Closed by hadley** 2016-06-02 14:35 UTC

**Comment by kevinushey** [comment] 2016-06-02 17:31
FWIW, I was initially able to reproduce this crash on 32bit R, but it went away after reinstalling both Rcpp and dplyr.
