### ISSUE TITLE
Select with NOT statements

### ISSUE THREAD

**Issue by ajmazurie** [hadley/dplyr#1907] opened 2016-06-10 22:51 UTC
I'm not sure if this is a bug, but I was certainly surprised by the following behavior:

```R
> d <- tbl_df(data.frame(xxx = 1:2, yyy = 1:2, bxx = 1:2, bbb = 1:2))
> d
Source: local data frame [2 x 4]

    xxx   yyy   bxx   bbb
  (int) (int) (int) (int)
1     1     1     1     1
2     2     2     2     2
> select(d, starts_with("dummy"))
Source: local data frame [2 x 0]

> select(d, -starts_with("dummy"))
Source: local data frame [2 x 0]
```

While the first selection (`select(d, starts_with("dummy"))`) returns what one would expect; i.e., an empty data frame since there is no column which name starts with "dummy", I am puzzled by the second behavior.

In the second selection (`select(d, -starts_with("dummy"))`) I thought we were asking for all columns which name do not start with "dummy"; in this case, all columns.

Is there something I do not understand here?
Aurélien

**Comment by hadley** [comment] 2016-06-14 20:56
Duplicate of #1834

**Closed by hadley** 2016-06-14 20:56 UTC
