### ISSUE TITLE
package conflict

### ISSUE THREAD

**Issue by chine007** [hadley/dplyr#2163] opened 2016-10-08 09:00 UTC
qh2 <- mydf %>% filter(date >= as.Date('2013-08-14'),date <= as.Date('2013-08-20'))
Error in `<=.default`(date, as.Date("2013-08-20")) :
  comparison (4) is possible only for atomic and list types

detach fBasics and timeSeries
The above command returns OK.

**Comment by krlmlr** [comment] 2016-11-07 16:34
Thanks. Could you please provide a reproducible example?

**Comment by hadley** [comment] 2017-02-02 22:18
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed** 2017-02-02 22:18 UTC
