### ISSUE TITLE
cbind'ing vector to grouped df fails

### ISSUE THREAD

**Issue by Hong-Revo** [hadley/dplyr#2474] opened 2017-02-27 10:27 UTC
Whereas `cbind`ing a vector to a tibble succeeds. I would think that either both should work, or both should fail (with my preference being the former).

```
df <- data_frame(x1 = 1:10, x2 = 1:10)
grp_df <- group_by(df, x1)

y <- 1:10

cbind(df, y)  # works

cbind(grp_df, y)  # fails
#Error in eval(substitute(expr), envir, enclos) : 
#  cannot convert object to a data frame
```

This is with dplyr 0.5.0.9000, built on 24-Jan-2017.

**Comment by hadley** [comment] 2017-02-27 13:23
This is basically a duplicate of #1676

**Closed by hadley** 2017-02-27 13:23 UTC

**Comment by Hong-Revo** [comment] 2017-03-05 07:38
I don't see how this is a dup of #1676. That one is talking about rows, not columns.

But assuming it is, has there been any progress? That issue has been open for more than a year now.
