### ISSUE TITLE
a problem related to translate_sql for %in% operator

### ISSUE THREAD

**Issue by shrektan** [hadley/dplyr#1282] opened 2015-07-22 08:04 UTC
Hi, when I execute `translate_sql(x %in% c("a"))`, the expected result should be:

```
<SQL> "x" IN ('a')
```

However, in `dplyr 0.4.1` the result turns out to be:

```
<SQL> "x" IN 'a'
```
Notice that the `a` doesn't surrounded with `(`and `)`. Thus, this SQL can't be executed.

**Comment by hadley** [comment] 2015-08-24 22:06
Duplicate of #511

**Closed by hadley** 2015-08-24 22:06 UTC
