### ISSUE TITLE
as.character() not correctly vectorised in mutate()

### ISSUE THREAD

**Issue by ThierryO** [hadley/dplyr#1669] opened 2016-02-20 20:49 UTC
Please have a look at this example. Without the grouping the result is as I expect. With grouping, the column `Missing` contains only missing values instead of just one `NA`.

    library(dplyr)
    df <- data.frame(
      ID = 1:2,
      Text = c("A", "B"),
      Factor = factor(c("A", "B")),
      Integer = 1:2,
      Numeric = c(0.5, pi),
      Missing = c(NA, 1.5),
      Logical = c(TRUE, FALSE),
      stringsAsFactors = FALSE
    )
    df %>% 
      mutate_each(funs(as.character))

output

    Source: local data frame [2 x 7]
    
         ID  Text Factor Integer          Numeric Missing Logical
      (chr) (chr)  (chr)   (chr)            (chr)   (chr)   (chr)
    1     1     A      A       1              0.5      NA    TRUE
    2     2     B      B       2 3.14159265358979     1.5   FALSE

code with grouping

    df %>% 
      group_by(ID) %>%
      mutate_each(funs(as.character)) %>%
      as.tbl()

output with grouping

    Source: local data frame [2 x 7]
    Groups: ID [2]
    
         ID  Text Factor Integer          Numeric Missing Logical
      (int) (chr)  (chr)   (chr)            (chr)   (chr)   (chr)
    1     1     A      A       1              0.5      NA    TRUE
    2     2     B      B       2 3.14159265358979      NA   FALSE

**Comment by hadley** [comment] 2016-03-01 14:59
Can you please provide a simpler reprex? I don't immediately see what the problem is. (Also please use `data_frame()` instead of `data.frame())

**Comment by ThierryO** [comment] 2016-03-01 15:14
The problem is in the `Missing` column. With grouping all values become `NA`. The output without grouping is correct (one `NA` and one string). Here is a smaller example

    df <- data_frame(
      ID = 1:2,
      Text = c("A", "B"),
      Missing = c(NA, 1.5)
    )
    test1 <- df %>% 
      mutate_each(funs(as.character))
    test2 <- df %>% 
      group_by(ID) %>%
      mutate_each(funs(as.character))
    all.equal(test1$Missing, test2$Missing)

**Comment by hadley** [comment] 2016-03-01 15:22
Thanks. Here's an even simpler reprex:

```R
df <- data_frame(
  g = 1:2,
  x = c(NA, 1.5)
)
df %>% 
  group_by(g) %>%
  mutate(x = as.character(x))
```

@romainfrancois can you please see what's going wrong here?

**Comment by hadley** [comment] 2016-03-01 15:36
And this is fixed in dev

**Closed by hadley** 2016-03-01 15:36 UTC
Labels: bug

**Comment by HughParsonage** [comment] 2016-03-15 21:21
In which commit was this bug fixed? (There were a lot on that date.)
