### ISSUE TITLE
a bug with group_by + mutate_each ?

### ISSUE THREAD

**Issue by GodefroyClair** [hadley/dplyr#2049] opened 2016-07-31 23:01 UTC
Hi,
With dplyr Version: 0.4.3 and R :
version 3.3.0 (2016-05-03)
Platform: x86_64-apple-darwin14.5.0 (64-bit)
Running under: OS X 10.11.6 (El Capitan)
this code :
```
set.seed(7)
df <- data.frame(x=10*runif(9), y=20*rnorm(9), group=rep(c("a","b","c"),3))
df2 <- df %>% group_by(group) %>% mutate_each(funs(scale))
```
passes ok and if  I call df2, I can see its content. But if I do `View(df2)` or `str(df2)` I got an error

> Error in FUN(X[[i]], ...) : 
 > dims [product 3] do not match the length of object [9]

**Comment by GodefroyClair** [comment] 2016-09-13 19:54
Can someone answer me on this please ? :)

**Comment by joranE** [comment] 2016-09-14 14:29
The issue seems to be that `scale` returns a matrix not a vector, and somehow (in dplyr?) the dimension attribute is being set to be 3x1 for the whole column. Note that if you type `df2[[1]]` you only see three values, because the dimension attribute is sort of "lying".

A workaround might be to use `my_scale <- function(x) c(scale(x))` instead to force a dimensionless vector to be returned.

**Comment by GodefroyClair** [comment] 2016-09-16 12:02
Thank you for the answer JoranE. That was what I suspected but your proof and your solution are better than mine. Is there something else to do to report this now that we suspect quite strongly that it's a bug in dplyr ?

**Comment by jrosen48** [comment] 2016-09-21 15:46
I think this SO question and answer may be relevant: http://stackoverflow.com/questions/35775696/trying-to-use-dplyr-to-group-by-and-apply-scale

**Comment by krlmlr** [comment] 2016-09-24 01:38
I think this is a duplicate of #1918.

**Comment by krlmlr** [comment] 2016-09-24 08:15
Can you please try `devtools::install_github("krlmlr/dplyr@b-1918-grouped-dims")`?

**Comment by vnijs** [comment] 2016-09-25 17:41
Possibly related issue:

```r
> dat <- mtcars[1:5,1:3]
> df <- mutate_each(dat, funs(scale(.))) %>% mutate(somevar = cyl)
Error: Each variable must be a 1d atomic vector or list.
Problem variables: 'mpg', 'cyl', 'disp'
```

Using `as.vector(scale(.))`, suggested by @krlmlr, works

**Closed** 2016-09-29 12:49 UTC
