### ISSUE TITLE
RPostgres is unable to find table without manually giving the sql call

### ISSUE THREAD

**Issue by cboettig** [hadley/dplyr#1277] opened 2015-07-19 22:03 UTC
When using the postgresql connection, calls like:

```{r}
tbl(mydb, "tablename")
```

fail with:

```
Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  relation "tablename" does not exist
LINE 1: SELECT * FROM "tablename" WHERE 0=1
```

while falling back on manually giving the SQL call to dplyr works:

```r
tbl(mydb, sql("SELECT * FROM databasename.tablename"))
```

Not sure if this is a `dplyr` or `RPostgres` issue, bug first reported under the latter with a copy-pastable reproducible example there: https://github.com/rstats-db/RPostgres/issues/32 .

**Comment by kismsu** [comment] 2015-07-23 13:13
Are you sure that tablename is a table now a view? I've seen this for views?

**Comment by cboettig** [comment] 2015-07-23 17:34
@kismsu Good question, I'm not all that familiar with the distinction, but I think these are real tables.  `dplyr` print method for mydb calls them tables at any rate, so that's pretty confusing. There's a completely reproducible example in the link I provide that accesses the exact database and table where I see this error if that's helpful.  I'll paste it over here for convenience:



```r
library("dplyr")
library("RPostgreSQL")
mydb = src_postgres(dbname = "srdb", host="nautilus-vm.mathstat.dal.ca", user = "srdbuser", password =  "srd6us3r!", port = 5432)
```

I can now see a list of the tables:

```r
mydb
```

shows:
```
src:  postgres 8.4.10 [srdbuser@nautilus-vm.mathstat.dal.ca:5432/srdb]
tbls: area, assessment, assessmethod, assessor, biometrics, bioparams, brptots,
  fishbasesaupcodes, geometry_columns, lmerefs, lmes, lmetostocks, management,
  mostrecent, recorder, referencedoc, reference_point_units_view,
  reference_point_values_view, risfields, risfieldvalues, spatial_ref_sys,
  stock, taxonomy, timeseries, timeseries_units_view, timeseries_values_view,
  tsmetrics, tsrelative_explicit_view
```

Note that `dplyr` is listing these as `tbls` above, which implies to me that they should be accessible with the `tbl` method, right?  I try to access a table:

```r
tbl(mydb, "stock")
```

and I get the error:

```
Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  relation "stock" does not exist
LINE 1: SELECT * FROM "stock" WHERE 0=1
                      ^
```

No idea what that `0=1` business is for either.  Manually constructing the SQL query seems to work though:

```r
tbl(mydb, sql("SELECT * FROM srdb.stock"))
```

returns the table as expected:

```
Source: postgres 8.4.10 [srdbuser@nautilus-vm.mathstat.dal.ca:5432/srdb]
From: <derived table> [?? x 8]

      stockid    tsn scientificname   commonname                 areaid
1        COD1 164712   Gadus morhua Atlantic cod   multinational-NAFO-1
2    COD2J3KL 164712   Gadus morhua Atlantic cod       Canada-DFO-2J3KL
3  COD2J3KLIS 164712   Gadus morhua Atlantic cod       Canada-DFO-2J3KL
4       COD3M 164712   Gadus morhua Atlantic cod  multinational-NAFO-3M
5      COD3NO 164712   Gadus morhua Atlantic cod multinational-NAFO-3NO
6      COD3Ps 164712   Gadus morhua Atlantic cod         Canada-DFO-3Ps
7   COD3Pn4RS 164712   Gadus morhua Atlantic cod      Canada-DFO-3Pn4RS
8       COD4T 164712   Gadus morhua Atlantic cod          Canada-DFO-4T
9     COD4VsW 164712   Gadus morhua Atlantic cod        Canada-DFO-4VsW
10    COD4TVn 164712   Gadus morhua Atlantic cod          Canada-DFO-4T
..        ...    ...            ...          ...                    ...
Variables not shown: stocklong (chr), inmyersdb (int), myersstockid (chr)
```

**Comment by einarhjorleifsson** [comment] 2015-07-23 19:21
hi
i will throw my spanner in here, for better or worse.

firstly, i can reproduce the code by @cboettig.

secondly, i suspect that these may be views. specific to the specified user. the actual data are i suspect are stored in srdb.tablename (e.g. "srdb.stock" ). and the "srdb" is what falls likely under <schema> - so when executing:
sql("SELECT * FROM srdb.stock")
one is (i think) generally executing:
sql("SELECT * FROM <schema>.<table>")
i.e. one is not accessing "tables"/"views" directly available at the root of the "srdbuser" when executing the above.

now - i say suspect in the above, because i come from the oracle world (which also has the capability of having <schema>.<table> structure). in my world i can access stuff via the old fashioned way by:
require(DBI)
require(ROracle)
mar <- dbConnect(dbDriver("Oracle"))  # additional information (username, password) not needed, accessed directly from the personal computer).
dbListTables(mar, schema = "FISKAR")   # list of tables in schema FISKAR
now then all sql statements go like "SELECT ....... FROM FISKAR.xxxx [xxxx stands for different table names]. in my case i can then access different schemas than FISKAR - could e.g. have two identical table names under different schemas, e.g. <schema1>.STATIONS, <schema2>.STATIONS.  

in the dplyr-world i always have to do (with the help the dplyrOracle package [on github]):
tbl(mydb, sql("FISKAR.table_name"))
{which is the same as:
tbl(mydb, sql("SELECT * FROM FISKAR.table_name"))}

making tables under schema accessible to the rest of the dplyr verbs via the above is really inferior compared with what one can achieve with tables that are under no <schema>. as manifested e.g. in the the "From: <derived table> [?? x 8]" - i.e. row numbers are not returned. just have not yet figured out where the problem lies (in what package).

i started off by saying better or worse. because the above may not help in clarifying the issue.

regards,
einar

ps! thanx very much for dplyr - has really made my work a lot more streamlined and efficient.

**Comment by einarhjorleifsson** [comment] 2015-07-23 19:56
apologies:
sql("SELECT * FROM .
")
should be sql("SELECT * FROM <schema><table>")

**Comment by einarhjorleifsson** [comment] 2015-07-23 19:57
hmmm. markdown problem here, last trial: sql("SELECT from SCHEMA.TABLE")

**Comment by kismsu** [comment] 2015-07-24 07:30
It looks like you can't get access to table if it's schema not public. As stock table is in srdb schema, simple tbl(mydb, "table_name") doesn't work.

**Comment by einarhjorleifsson** [comment] 2015-07-24 16:35
This seems to do the trick:

```r
library("dplyr")
```

```
## 
## Attaching package: 'dplyr'
## 
## The following objects are masked from 'package:stats':
## 
##     filter, lag
## 
## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
```

```r
library("RPostgreSQL")
```

```
## Loading required package: DBI
```

```r
mydb = src_postgres(dbname = "srdb", host="nautilus-vm.mathstat.dal.ca", user = "srdbuser", password =  "srd6us3r!", port = 5432)
mydb
```

```
## src:  postgres 8.4.10 [srdbuser@nautilus-vm.mathstat.dal.ca:5432/srdb]
## tbls: area, assessment, assessmethod, assessor, biometrics, bioparams,
##   brptots, fishbasesaupcodes, geometry_columns, lmerefs, lmes,
##   lmetostocks, management, mostrecent, recorder,
##   reference_point_units_view, reference_point_values_view, referencedoc,
##   risfields, risfieldvalues, spatial_ref_sys, stock, taxonomy, timeseries,
##   timeseries_units_view, timeseries_values_view, tsmetrics,
##   tsrelative_explicit_view
```

```r
dbExistsTable(mydb$con,"stock")
```

```
## [1] FALSE
```

```r
dbGetQuery(mydb$con, "set search_path to srdb")
```

```
## NULL
```

```r
dbExistsTable(mydb$con,"stock")
```

```
## [1] TRUE
```

```r
tbl(mydb,"stock")
```

```
## Source: postgres 8.4.10 [srdbuser@nautilus-vm.mathstat.dal.ca:5432/srdb]
## From: stock [424 x 8]
## 
##       stockid    tsn scientificname   commonname                 areaid
## 1        COD1 164712   Gadus morhua Atlantic cod   multinational-NAFO-1
## 2    COD2J3KL 164712   Gadus morhua Atlantic cod       Canada-DFO-2J3KL
## 3  COD2J3KLIS 164712   Gadus morhua Atlantic cod       Canada-DFO-2J3KL
## 4       COD3M 164712   Gadus morhua Atlantic cod  multinational-NAFO-3M
## 5      COD3NO 164712   Gadus morhua Atlantic cod multinational-NAFO-3NO
## 6      COD3Ps 164712   Gadus morhua Atlantic cod         Canada-DFO-3Ps
## 7   COD3Pn4RS 164712   Gadus morhua Atlantic cod      Canada-DFO-3Pn4RS
## 8       COD4T 164712   Gadus morhua Atlantic cod          Canada-DFO-4T
## 9     COD4VsW 164712   Gadus morhua Atlantic cod        Canada-DFO-4VsW
## 10    COD4TVn 164712   Gadus morhua Atlantic cod          Canada-DFO-4T
## ..        ...    ...            ...          ...                    ...
## Variables not shown: stocklong (chr), inmyersdb (int), myersstockid (chr)
```

einar

**Comment by cboettig** [comment] 2015-07-24 16:38
@einarhjorleifsson very nice! 

Would it be possible to get `dplyr` to set the search path automatically?  Since `mydb` is reporting these a `tbls` it seems reasonable a user would expect them to work with the `tbl` method.

**Comment by einarhjorleifsson** [comment] 2015-07-24 16:45
and/or additionally to be able to do call schema in the `src_postgres` function. in this particular case something like

```r
mydb = src_postgres(dbname = "srdb", schema = "srdb", ... )
```
say this because the schema name may be different from the database name.

**Comment by einarhjorleifsson** [comment] 2015-07-25 10:40
alternative and more direct way: looks like one can access the "srdb" schema within the `src_postgres` function by specifying options:
```r
library(dplyr)
library(RPostgreSQL)
mydb = src_postgres(dbname = "srdb",
                    host="nautilus-vm.mathstat.dal.ca",
                    user = "srdbuser",
                    password =  "srd6us3r!",
                    port = 5432,
                    options="-c search_path=srdb") 
tbl(mydb, "stock")
```
wandering if this option syntax could be hidden within the `src_postgres` function such that the user could do something like:
```r
src_postgres(dbname = "dbname", schema = "schemaname", ...)
```
einar

**Comment by einarhjorleifsson** [comment] 2015-08-04 20:43
since this issue is still 'open'. wandering (see inline comments/questions) given this postgres datasource:
```
library(dplyr)
library(RPostgreSQL)
ram <- src_postgres(dbname = "srdb", 
                    host="nautilus-vm.mathstat.dal.ca", 
                    user ="srdbuser", 
                    password ="srd6us3r!",
                    port = 5432,
                    options="-c search_path=srdb")
x <- tbl(ram, "assessment") %>%
  filter(stockid == "CODICE") %>%
  select(assessid) %>%
  left_join(tbl(ram, "timeseries"))

# why does this generate a warning message ?
explain(x)
# given that the following 'works':
library(ggplot2)
x %>%
  collect() %>%
  ggplot() +
  geom_line(aes(tsyear, tsvalue)) +
  facet_wrap(~ tsid, scale = "free_y")
```
einar

**Comment by hadley** [comment] 2015-08-24 22:07
Seems to be duplicate of #244

**Closed by hadley** 2015-08-24 22:07 UTC
