### ISSUE TITLE
left_join() on postgres tbl duplicates join variables in some cases

### ISSUE THREAD

**Issue by Vestaxis** [hadley/dplyr#1690] opened 2016-03-07 11:02 UTC
Somehow, somewhere a recent change to the development version of dplyr breaks left_join() for tables created with tbl() for database objects created with src_postgres().

It's been pretty hard to create a reproducible example. Say I have three tbl objects. 

my_db <- tbl(src_postgres("nycflights13"), "flights")
tbl1 <- tbl(my_db, sql("select year, origin, tailnum, carrier from flights"))
tbl2 <- tbl(my_db, sql("select year, origin, tailnum, carrier from flights"))
tbl3 <- tbl(my_db, sql("select * from (values (1, 'UA'), (2, 'AA'), (3, 'B6')) as t (num,carrier)"))

This works fine: 
```
tbl1 %>% left_join(tlb2, by = c("carrier" = "carrier"))
From: <derived table> [?? x 7]

   year.x origin.x tailnum.x carrier year.y origin.y tailnum.y
    (int)    (chr)     (chr)   (chr)  (int)    (chr)     (chr)
1    2013      EWR    N14228      UA   2013      EWR    N14228
2    2013      EWR    N14228      UA   2013      LGA    N24211
3    2013      EWR    N14228      UA   2013      EWR    N39463
```

This does not: 
```
tbl1 %>% left_join(tlb3, by = c("carrier" = "carrier"))
From: <derived table> [?? x 6]

    year origin tailnum carrier   num carrier
   (int)  (chr)   (chr)   (chr) (int)   (chr)
1   2013    EWR  N14228      UA     1      UA
2   2013    LGA  N24211      UA     1      UA
3   2013    JFK  N619AA      AA     2      AA

```

This issue is that in the first example, I get column carrier back only once. In the second example dplyr returns the carrier column twice. This is problematic because when adding a bunch of operations and then collecting the data, postgres complains that the column reference to carrier is ambiguous. 

Btw, I could have used tbl1 %>% left_join(tlb3, by = "carrier") in this case but that doesn't change the result.

This did not happen in previous dplyr versions I have been using.

**Comment by hadley** [comment] 2016-03-17 22:02
I'm pretty sure this is now fixed in the dev version:

```R
df1 <- memdb_frame(x = 1:5, y = 1:5, .name = "df1")
df2a <- memdb_frame(x = 1:5, z = 1:5, .name = "df2")
df2b <- tbl(src_memdb(), sql("SELECT * FROM `df2`")) 

left_join(df1, df2a, by = "x")
left_join(df1, df2b, by = "x")
```

If it still fails for you, could you please modify the above reproducible example to illustrate the problem? (It's extremely likely that the problem is common to both SQLite and Postgres)

**Closed by hadley** 2016-03-17 22:02 UTC
Labels: bug, database

**Comment by Vestaxis** [comment] 2016-03-18 07:09
This is now fixed for me. Thanks.
