### ISSUE TITLE
Feature request: ``do``-like progress bar for mutate

### ISSUE THREAD

**Issue by kendonB** [hadley/dplyr#1920] opened 2016-06-13 18:42 UTC
Moving to tidyr/purr nest/map (described here: https://www.youtube.com/watch?v=rz3_FDVt9eg) method from do loses the nice automatic progressbar.

e.g.

complicated_operation <- function(x){
  this_op_has_more_steps <- 2
  lm(Petal.Length ~ Petal.Width, data = x)
  Sys.sleep(10)
}

iris %>% 
  group_by(Species) %>% 
  nest() %>% 
  # Now a df with "data" as a column of data.frames
  mutate(model = data %>% map(complicated_operation))

**Comment by hadley** [comment] 2016-06-13 19:16
Duplicate of https://github.com/hadley/purrr/issues/149

**Closed by hadley** 2016-06-13 19:16 UTC
