### ISSUE TITLE
grouped mutate with ifelse() and NA throws error

### ISSUE THREAD

**Issue by sfirke** [hadley/dplyr#1432] opened 2015-10-01 01:43 UTC
Seems similar to https://github.com/hadley/dplyr/issues/958 and https://github.com/hadley/dplyr/issues/1381 but those seem to have been addressed.  I'm using dplyr 0.4.3.9.

````
dat <- data_frame(
  a = c("c", "c", "c", "d", "d"),
  b = c("hi", "lo", "hi", NA, NA)
)

dat %>%
  group_by(a) %>%
  mutate(is_hi = ifelse(b == "hi", "it's hi", "it's lo"))
````
Returns:
*Error: incompatible types, expecting a character vector*

Without the group_by() it returns what I would expect:
Source: local data frame [5 x 3]

````
      a     b   is_hi
  (chr) (chr)   (chr)
1     c    hi it's hi
2     c    lo it's lo
3     c    hi it's hi
4     d    NA      NA
5     d    NA      NA
````

**Comment by romainfrancois** [comment] 2015-10-01 14:34
Hmm, that's because 

```
> x <- c(NA_character_, NA_character_)
> ifelse( x == "hi", "it's hi", "it's lo")
[1] NA NA
> ifelse( x == "hi", "it's hi", "it's lo") %>% str
 logi [1:2] NA NA
```

I'll think about what I can do.

**Comment by hadley** [comment] 2015-10-20 02:23
Maybe we need an alternative to ifelse which has three args - true, false and NA.

**Comment by hadley** [comment] 2015-10-21 22:11
Duplicate of #1463

**Closed by hadley** 2015-10-21 22:11 UTC
