### ISSUE TITLE
Multivariate mutate

### ISSUE THREAD

**Issue by etiennebr** [hadley/dplyr#2286] opened 2016-12-02 19:14 UTC
Is there an easy way to mutate multiple columns with a single call ?

Something like 
```r
data.frame(text=c("a b c", "c i a", "r p g", "x y z", "r m d", "r e m")) %>%
  mutate(split=reshape2::colsplit(text, " ", 1:3))
```

would yield
```r
#> # A tibble: 6 × 4
#>    text split_1 split_2 split_3
#>   <chr>   <chr>   <chr>   <chr>
#> 1 a b c       a       b       c
#> 2 c i a       c       i       a
#> 3 r p g       r       p       g
#> 4 x y z       x       y       z
#> 5 r m d       r       m       d
#> 6 r e m       r       e       m
```

I know this specific case can be solved with [`separate()`](http://stackoverflow.com/a/24936825/171659), but in the generic case where calling a function takes a few seconds to compute and returns multiple variables, it would be great to have a simple solution.

Using
```
mutate(split_1=reshape2::colsplit(text, " ", 1:3)[[1]], 
             split_2=reshape2::colsplit(text, " ", 1:3)[[2]], 
             split_3=reshape2::colsplit(text, " ", 1:3)[[3]])
```
or
```r
group_by(x,n) %>%
  do(...)
```
feels tortuous. I found other similar [solutions](http://stackoverflow.com/questions/29614849/dplyrmutate-to-add-multiple-values). What would be the tidy way ?

This is somewhat related to #154, but this time not for a summary.

**Comment by cderv** [comment] 2016-12-03 11:09
Hi, 

Maybe you can do something with `purrr` and nested data frames.
Here is an exemple using a function that returns 2 variables in a data.frame. 
First I add with `mutate` a list column and using `tidyr::unnest`, I obtain a new column by variable

``` r
set.seed(1000)
library(purrr)
library(dplyr)
df <- tibble(x = rnorm(5))

test_func <- function(x) {
  res <- tibble(
    xsign = sign(x),
    xabs = abs(x))
  res
}

df %>%
  mutate(res = map(x, test_func)) %>%
  tidyr::unnest(res)
#> # A tibble: 5 x 3
#>             x xsign       xabs
#>         <dbl> <dbl>      <dbl>
#> 1 -0.44577826    -1 0.44577826
#> 2 -1.20585657    -1 1.20585657
#> 3  0.04112631     1 0.04112631
#> 4  0.63938841     1 0.63938841
#> 5 -0.78655436    -1 0.78655436
```

Your proposition for `group_by` and `do` should work to pretty well.
Here, I uses `purrr` functions and I think it is not so far from the tidy way. 

Do you think this kind of solution could help you?

**Comment by etiennebr** [comment] 2016-12-05 19:53
However I can see two drawbacks (other solutions have those too):

1. Can only multivariate mutate on a single column
2. Need to use two more expressions
3. When exploring its pretty cool to skip a few steps and allow multiple rows to be added at one.

I've explored a multivariate mutate (`mutatem`). I think it could be useful, I'd be glad to make a pull request if it was deemed tidy enough, although it would require a few tweaks to be 100% consistent with `dplyr`. 

```r
mutatem_ <- function(.df, args) {
  args <- lazyeval::as_f_list(args) %>%
    lazyeval::auto_name()
  
  for(nm in names(args)) {
    o <- lazyeval::f_eval(args[[nm]], .df)
    if(length(dim(o)) > 1) {
      if(!has_valid_names(names(o))) {
        stop(lazyeval::f_label(args[[nm]], 
                   " must return a named list or data.frame."), call. = FALSE)
      }
      o <- setNames(o, paste0(nm, "_", names(o)))
      .df <- bind_cols(.df, o)
    } else {
      .df[[nm]] <- o
    }
  }
  
  .df
}
```

I've made a choice to force name the multivariate output, but it could be different, I guess.
Full function : https://gist.github.com/etiennebr/e83e344be1499b4cbc94fd69f00bf8d3

**Comment by hadley** [comment] 2017-01-31 23:34
Duplicate of #2326

**Closed by hadley** 2017-01-31 23:34 UTC
