### ISSUE TITLE
using %in% operation is not smart with database and shiny selectInput(multiple)

### ISSUE THREAD

**Issue by harryprince** [hadley/dplyr#2374] opened 2017-01-22 02:37 UTC
```{r}
shiny::selectInput(inputId = "batteryVoltageEnum",
                              label = "batteryVoltageEnum",
                              choices = batteryVoltageEnum,
                              multiple = T,
                              selected = c("LOW_POWER","NORMAL_POWER"))
```

when I select only one item in this multi-selector, below is sucess
```
 src_pool(pool) %>% tbl("batteryInfo") %>%
      filter(batteryVoltageEnum == input$batteryVoltageEnum)

 src_pool(pool) %>%
     tbl("batteryInfo") %>% 
     collect(n = Inf) %>%
      filter(batteryVoltageEnum %in% input$batteryVoltageEnum)
```

however, this will fail

```
 src_pool(pool) %>% tbl("batteryInfo") %>%
      filter(batteryVoltageEnum %in% input$batteryVoltageEnum)
```

it means using %in% directly in database side is not elegant.

**Comment by krlmlr** [comment] 2017-01-25 22:06
I can't replicate this problem with SQLite:

```r
memdb_frame(a = 1:3) %>% filter(a %in% 1:2)

ok <- 1:2
memdb_frame(a = 1:3) %>% filter(a %in% ok)
```

Could you please provide a reproducible example?

**Comment by hadley** [comment] 2017-01-31 22:54
Probable duplicate of #511

**Closed by hadley** 2017-01-31 22:54 UTC
