### ISSUE TITLE
inner_join returns no observations

### ISSUE THREAD

**Issue by NicolaPasquino** [hadley/dplyr#1970] opened 2016-06-27 15:13 UTC
The inner_join() command that has always worked fine has recently started returning 0 observations after updating to version 0.5.0 under Windows.

**Comment by hadley** [comment] 2016-06-27 16:26
Please provide a reproducible example

**Comment by NicolaPasquino** [comment] 2016-06-27 20:19
This is x:
```
structure(list(path = c("prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/freefree.mat", 
"prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/freefree.mat", 
"prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/freefree.mat", 
"prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/freefree.mat", 
"prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/freefree.mat"
), time = c(0, 0.001, 0.002, 0.003, 0.004), Fx = c(-0.985714900000062, 
-1.14501090000005, -1.04943330000009, -0.125516500000003, -0.603404500000011
), Fz = c(2.81372249999995, 3.19240889999998, 3.60265249999998, 
3.38175209999991, 3.63420969999999), speed = c(0.359728241512398, 
0.36892362237038, 0.37811900322836, 0.386607047097266, 0.397924438922477
), aux = c(10.305460575, 10.305460575, 10.305460575, 10.305460575, 
10.305460575)), .Names = c("path", "time", "Fx", "Fz", "speed", 
"aux"), row.names = c(NA, 5L), class = "data.frame")
```
and this is y:
```
structure(list(path = c("prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/freefree.mat", 
"prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/NIData_20160204_130733.mat", 
"prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/NIData_20160204_130810.mat", 
"prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/NIData_20160204_130853.mat", 
"prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/NIData_20160204_130917.mat"
), PreT = structure(c(1L, 1L, 1L, 1L, 1L), .Label = c("050N", 
"250N", "350N"), class = "factor"), hardness = structure(c(1L, 
1L, 1L, 1L, 1L), .Label = c("Hard", "Medm", "Soft"), class = "factor"), 
    Temp = structure(c(1L, 1L, 1L, 1L, 1L), .Label = c("100°C", 
    "25°C", "65°C"), class = "factor"), angle = structure(c(1L, 
    1L, 1L, 1L, 1L), .Label = c("50", "60", "70", "75", "80", 
    "85"), class = "factor"), material = structure(c(1L, 1L, 
    1L, 1L, 1L), .Label = c("marble", "new", "new1", "new2", 
    "old", "old2"), class = "factor"), filename = c("freefree", 
    "NIData_20160204_130733", "NIData_20160204_130810", "NIData_20160204_130853", 
    "NIData_20160204_130917")), .Names = c("path", "PreT", "hardness", 
"Temp", "angle", "material", "filename"), row.names = c(NA, 5L
), class = "data.frame")
```
`inner_join(x,y)` returns a void dataframe although with the correct columns names.
I would really appreciate your help

**Comment by NicolaPasquino** [comment] 2016-06-29 10:38
I realized that the definition used above for the two `df`'s does not give any problem with `inner_join()`. I may not follow the "reproducible example" rules, but if you use the following two `df`'s I am pretty sure you will be able to reproduce the error:

```
path  time         Fx       Fz     speed      aux
prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/freefree.mat 0.000 -0.9857149 2.813722 0.3597282 10.30546
prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/freefree.mat 0.001 -1.1450109 3.192409 0.3689236 10.30546
prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/freefree.mat 0.002 -1.0494333 3.602652 0.3781190 10.30546
prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/freefree.mat 0.003 -0.1255165 3.381752 0.3866070 10.30546
prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/freefree.mat 0.004 -0.6034045 3.634210 0.3979244 10.30546
```

```
path PreT hardness  Temp angle material               filename
prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/freefree.mat 050N     Hard 100°C    50   marble               freefree
prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/NIData_20160204_130733.mat 050N     Hard 100°C    50   marble NIData_20160204_130733
prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/NIData_20160204_130810.mat 050N     Hard 100°C    50   marble NIData_20160204_130810
prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/NIData_20160204_130853.mat 050N     Hard 100°C    50   marble NIData_20160204_130853
prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/NIData_20160204_130917.mat 050N     Hard 100°C    50   marble NIData_20160204_130917
```

**Comment by iangow** [comment] 2016-07-11 18:49
The revised versions seem not to give any problem either:

```r
library(readr)
library(dplyr)
x_text <- "path  time         Fx       Fz     speed      aux
prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/freefree.mat 0.000 -0.9857149 2.813722 0.3597282 10.30546
prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/freefree.mat 0.001 -1.1450109 3.192409 0.3689236 10.30546
prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/freefree.mat 0.002 -1.0494333 3.602652 0.3781190 10.30546
prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/freefree.mat 0.003 -0.1255165 3.381752 0.3866070 10.30546
prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/freefree.mat 0.004 -0.6034045 3.634210 0.3979244 10.30546"

y_text <- "path PreT hardness  Temp angle material               filename
prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/freefree.mat 050N     Hard 100°C    50   marble               freefree
prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/NIData_20160204_130733.mat 050N     Hard 100°C    50   marble NIData_20160204_130733
prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/NIData_20160204_130810.mat 050N     Hard 100°C    50   marble NIData_20160204_130810
prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/NIData_20160204_130853.mat 050N     Hard 100°C    50   marble NIData_20160204_130853
prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/NIData_20160204_130917.mat 050N     Hard 100°C    50   marble NIData_20160204_130917"

y_2 <- read_csv(gsub(" +", ",", x_text))
x_2 <- read_csv(gsub(" +", ",", y_text))
inner_join(x_2, y_2)
```

**Output:**

```r
> inner_join(x_2, y_2)
Joining, by = "path"
# A tibble: 5 x 12
                                                                     path  PreT hardness  Temp angle material filename  time         Fx       Fz     speed      aux
                                                                    <chr> <chr>    <chr> <chr> <int>    <chr>    <chr> <dbl>      <dbl>    <dbl>     <dbl>    <dbl>
1 prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/freefree.mat  050N     Hard 100°C    50   marble freefree 0.000 -0.9857149 2.813722 0.3597282 10.30546
2 prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/freefree.mat  050N     Hard 100°C    50   marble freefree 0.001 -1.1450109 3.192409 0.3689236 10.30546
3 prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/freefree.mat  050N     Hard 100°C    50   marble freefree 0.002 -1.0494333 3.602652 0.3781190 10.30546
4 prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/freefree.mat  050N     Hard 100°C    50   marble freefree 0.003 -0.1255165 3.381752 0.3866070 10.30546
5 prove_senza_fascetta_050N/mrb/provino_Hard_100°C_50_marble/freefree.mat  050N     Hard 100°C    50   marble freefree 0.004 -0.6034045 3.634210 0.3979244 10.30546
> 
```r

**Comment by krlmlr** [comment] 2016-11-07 23:29
We're working on this problem. For now please ensure that all your character columns are encoded in UTF-8, but all your column names are encoded as "native", which is *not* UTF-8 on Windows.

**Comment by hadley** [comment] 2016-11-08 00:05
@krlmlr can you please create on new meta issue, link all these issues to it, and then close them?

**Comment by krlmlr** [comment] 2016-11-08 00:09
Okay to keep my issues #1950 and #1885 as canonical issues, they contain mostly technical discussion? I'll link+close tomorrow.

**Comment by krlmlr** [comment] 2016-11-08 07:17
Closing, probably duplicate of #1885.

**Closed** 2016-11-08 07:22 UTC
