### ISSUE TITLE
Question: -starts_with() behaviour

### ISSUE THREAD

**Issue by ronammar** [hadley/dplyr#1925] opened 2016-06-14 20:09 UTC
This works:

```r
select(iris, -starts_with("Petal"))
```

Why does the following output an empty data frame?

```r
select(iris, -starts_with("shazoom"))
# data frame with 0 columns and 150 rows
```

Shouldn't the entire table be returned as is, since there is no column that starts with "shazoom"?

**Comment by hadley** [comment] 2016-06-14 20:56
Duplicate of #1834

**Closed by hadley** 2016-06-14 20:56 UTC
