### ISSUE TITLE
.Call("dplyr_mutate_impl", PACKAGE = "dplyr", df, dots) fails on "incompatible types, expecting a numeric vector"

### ISSUE THREAD

**Issue by AndreMikulec** [hadley/dplyr#1608] opened 2016-01-02 00:29 UTC
```text
All,

This data frame 
  data.frame(perdivisions = c("A","C"), instances = c(7, NA))

With dots
  as.formula("~SportsRank(x = instances, numb_ranks = 10)")

will cause an error in C code
  .Call("dplyr_mutate_impl", PACKAGE = "dplyr", df, dots)

Responds back with error
 "incompatible types, expecting a numeric vector"

***
I do not know anything about C,C++ code, would someone mind
looking at this.  Is there something that I am missing?
***

Here, I am repeating the problem

hdquantile <- function (x, probs = seq(0, 1, 0.25), se = FALSE, na.rm = FALSE
  , names = TRUE, weights = FALSE, outlook = "optimistic" ) {

  # outlook = "BLAH"
  if( !(outlook %in% c("optimistic","pessimistic","neutral")) ) stop("outlook must be \"optimistic\", \"pessimistic\", or \"neutral\"")

  if(!na.rm && !is.null(x)) {
    if(any(is.na(x))) stop("missing values and NaN's not allowed if 'na.rm' is FALSE" )
  }

  # edge case not handled properly
  is_nrow_is_zero <- FALSE
  if(is.null(x)) is_nrow_is_zero <- TRUE  

  # edge case not handled properly
  if(na.rm) x[!is.na(x)] -> x

  if( length(unique(x)) == 1 ) {  # length(unique(NULL)) == 0

    # optimistic - behaves like stats::quantile
    if( outlook == "optimistic" )   rep( length(probs) -1,length(probs)) -> y

    # pessimistic
    if( outlook == "pessimistic" )  rep( 1,length(probs)) -> y

    if( outlook == "neutral" ) {

      middle_value <- length(probs) %/% 2 + length(probs) %% 2
      rep(middle_value,length(probs)) -> y 

    }

  # format headers
  setNames( y, stringr::str_c(probs * 100,"%")) -> y; return(y)

  }

  Hmisc::hdquantile(x, probs = probs, se = se, na.rm = na.rm , names = names, weights = weights ) -> y

  # edge case : subtle bug
  if( all(is.na(y)) ) { y[is.na(y)] <- NA_real_ ; setNames( y, stringr::str_c(probs * 100,"%")) -> y; return(y) }

  # format headers
  setNames( y, stringr::str_replace(as.numeric(names(y)) * 100, "$", "%" ) ) -> y

  # same as quantile
  if(is_nrow_is_zero)  y[] <- NA_real_

  return(y)

}


SportsRank <- function(x, numb_ranks = 100, outlook = "pessimistic") {
  
  if(all(is.null(x))) return(invisible(NULL))

  if(all(is.na(x)))   return(rep(NA,length(x)))

  if(outlook == "optimistic"  ) outlook_final <- "pessimistic"

  if(outlook == "pessimistic" ) outlook_final <- "optimistic"

  abs(findInterval(x = x, tail(head(hdquantile(x = x, probs = seq(0, 1, 1/numb_ranks) , na.rm = TRUE, outlook = outlook_final ),-1),-1)) + 1 - length(seq(0, 1, 1/numb_ranks)))

}



numb_of_divisions <- 10

used_col_name <- "instances" 

grouped_by    <- "perdivisions"

new_formula <- "~ SportsRank(x = a,  numb_ranks = b)" 

                                                                # want the symbol       # want the literal
mutate_call <-  lazyeval::interp(as.formula(new_formula), a = as.name(used_col_name), b = numb_of_divisions) 
# formula

new_col_name <- "result_of"

dplyr::transmute_(dplyr::group_by_(data.frame(perdivisions = c("A","C"), instances = c(7,NA), stringsAsFactors = FALSE)[,,drop = FALSE], .dots = grouped_by), .dots = setNames(list(mutate_call), new_col_name))
#### NOT WORK - ERROR ### - Error: incompatible types, expecting a numeric vector # SHOULD NOT GET AN ERROR

dplyr::transmute_(dplyr::group_by_(data.frame(perdivisions = c("A","C"), instances = c(NA,7), stringsAsFactors = FALSE)[,,drop = FALSE], .dots = grouped_by), .dots = setNames(list(mutate_call), new_col_name))
# WORKS - BUT BAD WRONG ANSWER

Source: local data frame [2 x 2]
Groups: perdivisions [2]

  perdivisions result_of
         (chr)     (lgl)
1            A        NA # CORRECT
2            C        NA # WRONG ANSWER - SHOULD HAVE BEEN 10

# THESE ARE ALL CORRECT

> SportsRank(NA,10)  
[1] NA
> SportsRank(7,10)
[1] 10
> SportsRank(c(NA,7),10)
[1] NA 10
> SportsRank(c(7,NA),10)
[1] 10 NA


> debug(dplyr:::transmute_.default)

# WORKS CORRECTLY
# WORKS CORRECLTY ( SEE 'DOES NOT WORK CORRECTLY' BELOW )

> dplyr::transmute_(dplyr::group_by_(data.frame(perdivisions = c("A","C"), instances = c(7,7), stringsAsFactors = FALSE)[,,drop = FALSE], .dots = grouped_by), .dots = setNames(list(mutate_call), new_col_name))

debugging in: transmute_.default(dplyr::group_by_(data.frame(perdivisions = c("A",
    "C"), instances = c(7, 7), stringsAsFactors = FALSE)[, ,
    drop = FALSE], .dots = grouped_by), .dots = setNames(list(mutate_call),
    new_col_name))
debug: {
    dots <- lazyeval::all_dots(.dots, ..., all_named = TRUE)
    out <- mutate_(.data, .dots = dots)
    keep <- names(dots)
    select(out, one_of(keep))
}
Browse[2]> debug(mutate_)
Browse[2]> n
debug: dots <- lazyeval::all_dots(.dots, ..., all_named = TRUE)
Browse[2]> n
debug: out <- mutate_(.data, .dots = dots)
Browse[2]> n
debugging in: mutate_(.data, .dots = dots)
debug: {
    UseMethod("mutate_")
}
Browse[3]> n
debug: UseMethod("mutate_")
Browse[3]> n
debugging in: mutate_.tbl_df(.data, .dots = dots)
debug: {
    dots <- lazyeval::all_dots(.dots, ..., all_named = TRUE)
    mutate_impl(.data, dots)
}
Browse[4]> ls()
character(0)
Browse[4]> n
debug: dots <- lazyeval::all_dots(.dots, ..., all_named = TRUE)
Browse[4]> ls()
character(0)
Browse[4]> n
debug: mutate_impl(.data, dots)
Browse[4]> ls()
[1] "dots"
Browse[4]> dots
$result_of
<lazy>
  expr: SportsRank(x = instances, numb_ranks = 10)
  env:  <environment: R_GlobalEnv>

attr(,"class")
[1] "lazy_dots"
Browse[4]> mutate_impl(.data,dots)   # WORKS CORRECTLY 
Source: local data frame [2 x 3]
Groups: perdivisions [2]

  perdivisions instances result_of
         (chr)     (dbl)     (dbl)
1            A         7        10    # RIGHT ANSWER
2            C         7        10    # RIGHT ANSWER
Browse[4]> debug(mutate_impl)
Browse[4]> n
debugging in: mutate_impl(.data, dots)
debug: {
    .Call("dplyr_mutate_impl", PACKAGE = "dplyr", df, dots)
}
Browse[5]>


# DOES NOT WORK CORRECTLY - # NOT WORK - ERROR - Error: incompatible types, expecting a numeric vector # SHOULD NOT GET AN ERROR
# DOES NOT WORK CORRECTLY - # NOT WORK - ERROR - Error: incompatible types, expecting a numeric vector # SHOULD NOT GET AN ERROR


> debug(dplyr:::transmute_.default)

# DOES NOT WORK CORRECTLY - # NOT WORK - ERROR - Error: incompatible types, expecting a numeric vector # SHOULD NOT GET AN ERROR
> dplyr::transmute_(dplyr::group_by_(data.frame(perdivisions = c("A","C"), instances = c(7,NA), stringsAsFactors = FALSE)[,,drop = FALSE], .dots = grouped_by), .dots = setNames(list(mutate_call), new_col_name))

debugging in: transmute_.default(dplyr::group_by_(data.frame(perdivisions = c("A",
    "C"), instances = c(7, NA), stringsAsFactors = FALSE)[, ,
    drop = FALSE], .dots = grouped_by), .dots = setNames(list(mutate_call),
    new_col_name))
debug: {
    dots <- lazyeval::all_dots(.dots, ..., all_named = TRUE)
    out <- mutate_(.data, .dots = dots)
    keep <- names(dots)
    select(out, one_of(keep))
}
Browse[2]> debug(mutate_)
Browse[2]> n
debug: dots <- lazyeval::all_dots(.dots, ..., all_named = TRUE)
Browse[2]> n
debug: out <- mutate_(.data, .dots = dots)
Browse[2]> n
debugging in: mutate_(.data, .dots = dots)
debug: {
    UseMethod("mutate_")
}
Browse[3]> n
debug: UseMethod("mutate_")
Browse[3]> n
debugging in: mutate_.tbl_df(.data, .dots = dots)
debug: {
    dots <- lazyeval::all_dots(.dots, ..., all_named = TRUE)
    mutate_impl(.data, dots)
}
Browse[4]> ls()
character(0)
Browse[4]> n
debug: dots <- lazyeval::all_dots(.dots, ..., all_named = TRUE)
Browse[4]> ls()
character(0)
Browse[4]> n
debug: mutate_impl(.data, dots)
Browse[4]> ls()
[1] "dots"
Browse[4]> dots
$result_of
<lazy>
  expr: SportsRank(x = instances, numb_ranks = 10)
  env:  <environment: R_GlobalEnv>

attr(,"class")
[1] "lazy_dots"
Browse[4]> debug(mutate_impl) ### DEBUG IT
Browse[4]> n
debugging in: mutate_impl(.data, dots)
debug: {
    .Call("dplyr_mutate_impl", PACKAGE = "dplyr", df, dots)
}
Browse[5]> df                              # DF
Source: local data frame [2 x 2]
Groups: perdivisions [2]

  perdivisions instances        # MY ENTERED DATAFRAME
         (chr)     (dbl)
1            A         7
2            C        NA
Browse[5]> dots                           # DOTS
$result_of
<lazy>
  expr: SportsRank(x = instances, numb_ranks = 10)
  env:  <environment: R_GlobalEnv>

attr(,"class")
[1] "lazy_dots"
Browse[5]> .Call("dplyr_mutate_impl", PACKAGE = "dplyr", df, dots)
Error: incompatible types, expecting a numeric vector                #### ERROR ####
Browse[5]> n
debug: .Call("dplyr_mutate_impl", PACKAGE = "dplyr", df, dots)
Browse[5]> n
Error: incompatible types, expecting a numeric vector
>

***
I do not know anything about C,C++ code, would someone mind
looking at this.  Is there something that I am missing?
***


Thanks,
Andre Mikulec
Andre Mikulec@Hotmail.com


> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252
[2] LC_CTYPE=English_United States.1252
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C
[5] LC_TIME=English_United States.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.1         Formula_1.2-1       cluster_2.0.3
 [4] magrittr_1.5        splines_3.2.2       MASS_7.3-43
 [7] munsell_0.4.2       colorspace_1.2-6    lattice_0.20-33
[10] R6_2.1.1            stringr_1.0.0       plyr_1.8.3
[13] dplyr_0.4.3         tools_3.2.2         nnet_7.3-10
[16] parallel_3.2.2      grid_3.2.2          gtable_0.1.2
[19] latticeExtra_0.6-26 DBI_0.3.1           survival_2.38-3
[22] lazyeval_0.1.10     assertthat_0.1      digest_0.6.8
[25] gridExtra_2.0.0     RColorBrewer_1.1-2  reshape2_1.4.1
[28] ggplot2_1.0.1       acepack_1.3-3.3     rpart_4.1-10
[31] stringi_1.0-1       scales_0.3.0        Hmisc_3.17-0
[34] foreign_0.8-65      proto_0.3-10
```

**Comment by hadley** [comment] 2016-01-02 15:14
Can you please make a minimal example? I would also be helpful I you learned a little markdown so you could style prose as text and code as code.

**Comment by AndreMikulec** [comment] 2016-01-02 22:42
```text

Hadley,

Here is a minimalist example.
O.K. I have some markdown.

I copied and pasted this *MANY* times to my command shell window.

## BEGIN COPY HERE ##
#### MINMALIST EXAMPLE #####
# BEGIN COPY and PASTE #
```
```{r}

rm(list=ls())

mydf <- data.frame(perdivisions = c("A","C"), instances = c(7,NA))

grouped_by    <- "perdivisions"

mygroup <- dplyr::group_by_(mydf, .dots = grouped_by)

SportsRank <- function(x, numb_ranks = 100) { 

  sapply(X=x, FUN = function(x) {
  
    if(is.na(x)) { return(NA) } 
    if(x == 7) { return(numb_ranks) } # USUALLY 100 
                                      #   BUT as.formula(BELOW) 
                                      #   will make it 10
})}

# grouped ERROR ( *THIS* is my ERROR )
dplyr::transmute_(mygroup,    # GROUPED DF #
  .dots = setNames(
     list(as.formula("~SportsRank(x = instances, numb_ranks = 10)"))
   , "instances")
)
# Error: incompatible types, expecting a numeric vector

# un-grouped OK
dplyr::transmute_(   mydf,    # REGULAR DF #
  .dots = setNames(
    list(as.formula("~SportsRank(x = instances, numb_ranks = 10)"))
  , "instances")
)

# instances
# 1        10 # RIGHT ANSWER # PROVIDED BY THE as.formula
# 2        NA # RIGHT ANSWER
```
```text
# END COPY and PASTE #
#### END MINMALIST EXAMPLE #####
## END COPY HERE ##
```
```{r}
sessionInfo()

> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252
[2] LC_CTYPE=English_United States.1252
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C
[5] LC_TIME=English_United States.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] dplyr_0.4.3 plyr_1.8.3

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.1         Formula_1.2-1       cluster_2.0.3
 [4] magrittr_1.5        splines_3.2.2       MASS_7.3-43
 [7] munsell_0.4.2       colorspace_1.2-6    lattice_0.20-33
[10] R6_2.1.1            stringr_1.0.0       tools_3.2.2
[13] parallel_3.2.2      nnet_7.3-10         grid_3.2.2
[16] gtable_0.1.2        DBI_0.3.1           latticeExtra_0.6-26
[19] lazyeval_0.1.10     assertthat_0.1      survival_2.38-3
[22] digest_0.6.8        gridExtra_2.0.0     RColorBrewer_1.1-2
[25] reshape2_1.4.1      ggplot2_1.0.1       acepack_1.3-3.3
[28] rpart_4.1-10        stringi_1.0-1       scales_0.3.0
[31] Hmisc_3.17-0        foreign_0.8-65      proto_0.3-10
```

**Comment by hadley** [comment] 2016-01-04 14:57
Here is a minimal reproducible example, based on your rather more complicated code:

```R
library(dplyr)

df <- data.frame(x = c("A","C"), y = c(7,NA))

f <- function(x) { 
  sapply(x, function(x) if (is.na(x)) NA else 7)
}

df %>% 
  group_by(x) %>% 
  transmute(z = f(y))
```

It works for me (as does your original example). I'm pretty sure this is because this problem is fixed in the dev version, but the source of the problem is your use of `sapply()`. It's a bad idea to use this inside functions because it is not type-stable, and you never know what sort of output it's going to return.

**Closed by hadley** 2016-01-04 14:57 UTC

**Comment by AndreMikulec** [comment] 2016-01-07 00:34
I checked. 
It works in dev.
Thanks.
