### ISSUE TITLE
choices: new function to be used from within mutate and transmute functions

### ISSUE THREAD

**Issue by sumprain** [hadley/dplyr#1557] opened 2015-11-28 15:25 UTC
During creation of new variable using mutate function based on values of other variables, we usually use `ifelse` function as below

```
mutate(df, col2 = ifelse(col1 > 10, "val1", "val2")
```

The problem occurs when there are multiple criteria based on which values are to be assigned to a given variable

```
mutate(df, col2 = ifelse(col1 > 10, "val1", 
                            ifelse(col1 > 100, "val2", 
                            ifelse(col1 > 1000, "val3", "val4"))
```

The above function quickly gets messy and is difficult to comprehend and maintain.

I saw the above discussion in one of the issues (I am not able to trace it out now) and am suggesting a new function `choices` to be used within `mutate` and `transmute` function with the form below which can circumvent the above problem

```
mutate(df, col2 = choices("val1" ~ (col1 > 10), 
                                         "val2" ~ (col1 > 100),
                                         "val3" ~ (col1 > 1000),
                                          escape = "val4"))
```
 
The implementation of the function is in the [gist link](https://gist.github.com/sumprain/e53e21e58548229bd2d9)

Is it possible to include the code in the package?

Will it be possible to link this issue with the ongoing discussion?

Thanks a lot and keep up the exemplary work going.

**Comment by hadley** [comment] 2015-12-09 15:08
Duplicate of #631

**Closed by hadley** 2015-12-09 15:08 UTC
