### ISSUE TITLE
group_by %>% mutate in database not grouping

### ISSUE THREAD

**Issue by wtcooper** [hadley/dplyr#1413] opened 2015-09-16 13:37 UTC
Upgraded to 0.4.3, and noticed different behavior when doing a group_by() %>% mutate() in database versus first bringing into R and then doing the group_by() %>% mutate().  For example if I calculate a min() value in the mutate(), it won't group and provide a value for all observations in original dataset (I want mutate() instead of summarize()), but instead calculate the min() across all data observaitons.  It appears the in database version is not grouping at all.  

See example below where only thing I changed was the location of the collect():

```R
my_db <- src_sqlite("my_db.sqlite3", create = T)

library(nycflights13)
flights_sqlite <- copy_to(my_db, flights, temporary = FALSE, indexes = list(
				c("year", "month", "day"), "carrier", "tailnum"))

## Do group_by() %>% mutate() in database
datInDB = my_db %>% tbl("flights") %>% 
		select(carrier, distance) %>% 
		filter(carrier %in% c("OO", "F9")) %>%
		group_by(carrier) %>% 
		mutate(minDist = min(distance)) %>% 
		collect()
dim(datInDB)
#[1] 1 3

## Do group_by() %>% mutate() in R data frame
datOutDB = my_db %>% tbl("flights") %>% 
		select(carrier, distance) %>% 
		filter(carrier %in% c("OO", "F9")) %>% 
		collect() %>%
		group_by(carrier) %>% 
		mutate(minDist = min(distance, na.rm=T)) 
dim(datOutDB)
#[1] 717   3

sessionInfo()

#R version 3.2.2 (2015-08-14)
#Platform: x86_64-w64-mingw32/x64 (64-bit)
#Running under: Windows Server 2008 R2 x64 (build 7601) Service Pack 1
#
#locale:
#		[1] LC_COLLATE=English_United States.1252 
#[2] LC_CTYPE=English_United States.1252   
#[3] LC_MONETARY=English_United States.1252
#[4] LC_NUMERIC=C                          
#[5] LC_TIME=English_United States.1252    
#
#attached base packages:
#		[1] stats     graphics  grDevices utils     datasets  methods   base     
#
#other attached packages:
#		[1] nycflights13_0.1 dplyr_0.4.3      rj_2.0.4-2      
#
#loaded via a namespace (and not attached):
#		[1] lazyeval_0.1.10.9000 magrittr_1.5         R6_2.1.1            
#[4] assertthat_0.1       parallel_3.2.2       DBI_0.3.1           
#[7] tools_3.2.2          Rcpp_0.12.1          RSQLite_1.0.0       
```

**Comment by tinmice** [comment] 2015-09-24 15:19
I found similar behaviour in 0.4.2 but was sorted upon switching to 0.4.3.

**Comment by hadley** [comment] 2015-10-21 22:30
Minimal reprex:

```R
library(dplyr)
db <- src_sqlite("", create = TRUE)

df1 <- data.frame(g = c(1, 2, 2, 3, 3, 3), x = 1:6)
df2 <- copy_to(db, df1)

df1 %>% group_by(g) %>% mutate(y = min(x))
df2 %>% group_by(g) %>% mutate(y = min(x))
```

**Comment by hadley** [comment] 2015-10-21 22:30
This should be an error since SQLite doesn't support windowing functions.

**Comment by wtcooper** [comment] 2015-10-22 00:51
Ah yes that makes sense, since it didn't throw a warning or error I forgot group_by+mutate is a windows function, so used to using it on data frames.  An error would be useful for the inadvertent usage on SQLite for folks that are used to using it on other sources where it is supported.

**Comment by hadley** [comment] 2016-03-08 23:01
Duplicate of #907

**Closed by hadley** 2016-03-08 23:01 UTC
Labels: bug, database

**Comment by SteveOhh** [comment] 2016-11-10 00:54
With a Postgres 8.2.15 backend, if I use @hadley's example:
```
df1 <- data.frame(g = c(1, 2, 2, 3, 3, 3), x = 1:6)
df2 <- copy_to(db, df1)

df1 %>% group_by(g) %>% mutate(y = min(x))
df2 %>% group_by(g) %>% mutate(y = min(x))
```
...I get the following error on the df2 version:
```
Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  window specifications with a framing clause must have an ORDER BY clause
LINE 2: FROM (SELECT "g", "x", min("x") OVER (PARTITION BY "g" ROWS ...
```
Is that expected? Min() is most definitely a Postgres function.
