### ISSUE TITLE
`distinct` create duplicated column names

### ISSUE THREAD

**Issue by dfalbel** [hadley/dplyr#2109] opened 2016-09-05 14:44 UTC
I think it's not convenient that a function could create duplicated column names in a data.frame.
See this minimal example:

```
df <- data_frame(id = rep(1:2, each = 4), id2 = rep(1:2, 4))

df %>% group_by(id, id2) %>% distinct(id)
Source: local data frame [4 x 3]
Groups: id, id2 [4]

     id    id   id2
  <int> <int> <int>
1     1     1     1
2     1     1     2
3     2     2     1
4     2     2     2

df %>% group_by(id, id2) %>% select(-id2) %>% distinct(id)
Adding missing grouping variables: `id2`
Source: local data frame [4 x 3]
Groups: id, id2 [4]

     id    id   id2
  <int> <int> <int>
1     1     1     1
2     1     1     2
3     2     2     1
4     2     2     2
```

Maybe it should act like `mutate` that raises an error when modifying grouping variable?

```
> df %>% group_by(id) %>% mutate(id = 1)
Error: cannot modify grouping variable
```

**Comment by krlmlr** [comment] 2016-12-09 20:30
Thanks, confirmed. @hadley: Should `iris %>% group_by(Species) %>% distinct(Species)` raise an error? (Currently returns a grouped data frame with two columns named `Species`.)

**Comment by hadley** [comment] 2016-12-09 20:39
Yeah, I think that's reasonable.

**Comment by krlmlr** [comment] 2017-02-21 08:18
Duplicate of #2001.

**Closed by krlmlr** 2017-02-21 08:18 UTC
Labels: bug, data frame
