### ISSUE TITLE
filter() fails when variable condition shares column name with filtered table

### ISSUE THREAD

**Issue by jesse-ross** [hadley/dplyr#1836] opened 2016-05-18 19:16 UTC
I am trying to use a value from a tbl_df as a condition to filter another tbl_df, and it fails when the columns in the two tables have the same name. This happens using dplyr 0.4.3 in R 3.3.0.

```r
library(dplyr)
lookup_table = dplyr::data_frame(key = c("foo", "bar"),
                                 value = c("this", "that"))

colliding_table = dplyr::data_frame(baz = c("one", "two"),
                                    key = c("foo", "bar"))

other_table = dplyr::data_frame(baz = c("one", "two"),
                                schmey = c("foo", "bar"))

identical("foo", colliding_table[1, ]$key)
#[1] TRUE
identical("foo", other_table[1, ]$schmey)
#[1] TRUE
```

This `filter()` works when I use the bare string:

```r
dplyr::filter(lookup_table, key == "foo")
# Source: local data frame [1 x 2]
# 
#     key value
#   (chr) (chr)
# 1   foo  this
```
And it works when I use a different column name:

```r
dplyr::filter(lookup_table, key == other_table[1, ]$schmey)
# Source: local data frame [1 x 2]
# 
#     key value
#   (chr) (chr)
# 1   foo  this
```

But it fails when the column names of the two tables are the same:

```r
dplyr::filter(lookup_table, key == colliding_table[1, ]$key)
# Error: incorrect length (0), expecting: 2
```

**Comment by hadley** [comment] 2016-05-26 13:31
Duplicate of #1400

**Closed by hadley** 2016-05-26 13:31 UTC
