### ISSUE TITLE
Hmisc labels not compatible with left_join

### ISSUE THREAD

**Issue by rdisalv2** [hadley/dplyr#1567] opened 2015-12-02 23:23 UTC
left_join gives up when it encounters an Hmisc:label

```r
> test <- data.frame(x=rep(1,5),y=rep(2,5))
> test2 <- data.frame(x=rep(1,5),z=rep(5,5))
> 
> test3 <- test %>% left_join(test2)
Joining by: "x"
> # :)
> 
> Hmisc::label(test$x) <- "This is x"
> Hmisc::label(test2$x) <- "This is x"
> test3 <- test %>% left_join(test2)
Joining by: "x"
Error: cannot join on columns 'x' x 'x': Can't join on 'x' x 'x' because of incompatible types (labelled, numeric / labelled, numeric) 
> # :(
```

It's fine for it to give up, but the error message is definitely confusing for a new user like me. (labelled numeric type definitely looks the same as labelled numeric type!) It's something I kept hitting when I use an Hmisc function to read in a dataset and then try left_join.

I think this is related to https://github.com/hadley/dplyr/issues/375, https://github.com/hadley/dplyr/issues/1105 and https://github.com/hadley/dplyr/issues/228. If I understand correctly because you don't have support for copying over the attributes you've set things to stop rather than strip the attributes.

**Comment by hadley** [comment] 2016-03-01 17:02
Duplicate of #1636

**Closed by hadley** 2016-03-01 17:02 UTC
