### ISSUE TITLE
Error using "median" in summarise_each

### ISSUE THREAD

**Issue by Henrik-P** [hadley/dplyr#1168] opened 2015-05-25 18:11 UTC
In `summarise_each`, `funs` can be specified as a "character vector of function names". However, when specifying `"median"`, an error is generated:
`Error in summarise_impl(.data, dots) : could not find function "median"`

Specifying `funs(median)` works though. Small example:

    df <- data.frame(grp = rep(1:2, each = 2), x = 1:4, y = 5:8)
    df

    # does not work
    df %>% group_by(grp) %>% summarise_each("median")
    # Error in summarise_impl(.data, dots) : could not find function "median"

    # works
    df %>% group_by(grp) %>% summarise_each(funs(median))
    
    # just check some other functions provided as character vector
    # e.g. min and max, as used in ?summarise_each
    df %>% group_by(grp) %>% summarise_each(c("min", "max"))

`R 3.2.0, dplyr_0.4.1`

**Comment by hadley** [comment] 2015-08-24 21:47
Duplicate of #893 and fixed in dev version :)

**Closed by hadley** 2015-08-24 21:47 UTC

**Comment by maluram** [comment] 2015-10-16 09:48
Hi Found following error while using median and IQR for summarise each

conDplyr%>%
  tbl("mtcars")%>%
  summarise_each(funs(min, mean, max, sd, median), mpg, hp)

Error in .local(conn, statement, ...) : 
  could not run statement: FUNCTION userlogin.MEDIAN does not exist

**Comment by SebastianBloy** [comment] 2017-02-03 09:14
Dear all,

i just found this closed Issue as i was trying to use the "summarise_each_" function. I get the error described above. Has this only been fixed for "summarise_each"?

See example:

`library("dplyr")


groupss <- c("gear", "carb")
statistics <- c("min", "max", "mean") ## Add  "median" to see it fail
metrics <- c("drat", "hp")

grp_cols <- names(mtcars[colnames(mtcars) %in% groupss])
dots <- lapply(grp_cols, as.symbol)

funct <- statistics
funct <- lapply(funct, as.symbol)

vars <- lapply(metrics, as.symbol)


# A table is created successfully!
  mtcars %>%
  group_by_ (.dots = dots) %>%
  summarise_each_ (funs_ (funct), vars)



`

Best regards

Sebastian
