### ISSUE TITLE
Implement easy way to see remote data type for each tibble field

### ISSUE THREAD

**Issue by richierocks** [hadley/dplyr#2510] opened 2017-03-08 18:52 UTC
Inspired by this issue, https://github.com/rstudio/sparklyr/issues/537, it would be useful to have a `dplyr` function to retrieve the type of each column.

For local tibbles, this is not so important, since there are already easy ways of doing that. However, for remote data sources, it [becomes tricky](http://stackoverflow.com/a/39371653/134830).  For example, with a tibble whose data is in a database table, you need to write something like this:

```r
first_row <- a_db_tibble %>% head(1) %>% collect()
db_data_type(dbconn, first_row)
```

It would be useful to have a function (`tbl_schema`?) that returns the remote database/Spark data type of each field. To make it easy to work with programmatically, the return value should be a tibble with two columns: `name` and `type`.

**Comment by hadley** [comment] 2017-03-22 13:06
Since all remote backends are DBI based, this is basically a duplicate of https://github.com/rstats-db/DBI/issues/75

**Closed by hadley** 2017-03-22 13:06 UTC

**Comment by krlmlr** [comment] 2017-03-22 13:30
Perhaps dplyr should just call `dbColumnInfo()` during `collect()`, and make this information available in an attribute?
