### ISSUE TITLE
Error when using package::function() in mutate_at()

### ISSUE THREAD

**Issue by bschneidr** [hadley/dplyr#2461] opened 2017-02-22 13:49 UTC
When I call a function in `mutate_at()` by specifying the package and the function (e.g. `base::mean()`), I receive the following error:
```r
Error in vapply(dots[missing_names], function(x) make_name(x$expr), character(1)) : 
values must be length 1,
but FUN(X[[1]]) result is length 3
```
An example using the `iris` data is as follows.
The following code works:
```r
iris %>%
     mutate_at(.cols = c("Sepal.Length", "Sepal.Width"),
               .funs = funs(mean(.)))
```
The following code does not:
```r
iris %>%
     mutate_at(.cols = c("Sepal.Length", "Sepal.Width"),
               .funs = funs(base::mean(.)))
```

**Comment by hadley** [comment] 2017-02-22 16:49
Duplicate of #2089

**Closed by hadley** 2017-02-22 16:49 UTC
