### ISSUE TITLE
Session crashes with dplyr (and lubridate)

### ISSUE THREAD

**Issue by lordadeloss** [hadley/dplyr#1288] opened 2015-07-27 20:25 UTC
R studio or my R engine is crashing when I execute the code below or a version of that code. I have tried the code on a different computer with the same result. Any ideas of what is going on?

I have attached 
•	the data, https://www.dropbox.com/s/m7yg1cb3o7la59k/df_eo.RData?dl=0 

> sessionInfo()
R version 3.2.1 (2015-06-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=Swedish_Sweden.1252  LC_CTYPE=Swedish_Sweden.1252    LC_MONETARY=Swedish_Sweden.1252 LC_NUMERIC=C                   
[5] LC_TIME=Swedish_Sweden.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.2.1

# set working dir
setwd("C:\\Users\\Lord Adellus\\SkyDrive\\Daoud-Kohl\\Data") # Samsung-laptop

# load packages
load("df_eo.RData") 
library(ggplot2)
library(VGAM) 
library(dplyr)
library(R2MLwiN)
library(lubridate)

## create variable
df.eo.sorted <- df.eo %>%
    mutate(Article_ID = 1:NROW(df.eo),
           Era_1890to1920 = ifelse(ymd(date) < ymd("1921-01-01"), 1, 0),
           Era_1921to1985 = ifelse(ymd(date) %within% interval(ymd("1921-01-01"), ymd("1985-12-31")), 1, 0),
           Era_1986to2014 = ifelse(ymd(date) %within% interval(ymd("1986-01-01"), ymd("2014-12-31")), 1, 0)
           ) # it crashes sometimes here !
View(df.eo.sorted) # or it crashes here !

## This craches the session as well
df.eo.sorted <- df.eo %>%
    mutate(Era_1890to1920 = ifelse(ymd(date) < ymd("1921-01-01"), 1, 0),
           Era_1921to1985 = ifelse(ymd(date) %within% interval(ymd("1921-01-01"), ymd("1985-12-31")), 1, 0),
           Era_1986to2014 = ifelse(ymd(date) %within% interval(ymd("1986-01-01"), ymd("2014-12-31")), 1, 0)) %>%
    select(date, Era_1890to1920, Era_1921to1985, Era_1986to2014)

**Comment by lordadeloss** [comment] 2015-07-28 15:18
My problem seem to be similar to that of, https://github.com/hadley/lubridate/issues/330

**Comment by romainfrancois** [comment] 2015-08-02 09:58
I believe this has been fixed in early july. I can't reproduce this. 
Can you reopen if it still happens for you in the dev version.

**Closed by romainfrancois** 2015-08-02 09:58 UTC
