### ISSUE TITLE
dplyr can't access elements of nested lists

### ISSUE THREAD

**Issue by gzgreg** [hadley/dplyr#1067] opened 2015-04-10 23:31 UTC
Example:
```
tbl <- data.frame(id=c(1, 2, 3))
vals <- list(n=list(n=2))
filter(tbl, id >= vals$n$n)
Error in vals$n$function ()  : invalid subscript type 'closure'
```

**Comment by hadley** [comment] 2015-10-22 20:45
Duplicate of #1400

**Closed by hadley** 2015-10-22 20:45 UTC
