### ISSUE TITLE
%in% does not work with sql when vector is length 1

### ISSUE THREAD

**Issue by carlganz** [hadley/dplyr#2399] opened 2017-01-31 18:40 UTC
```{R}
library(dplyr)

src_memdb()

df <- memdb_frame(x = runif(2), y = c("A","B"))

df %>% filter(y %in% "B") # errors

df %>% filter(y %in% c("B","B")) # works

df %>% filter(y %in% "B") %>% explain

```
I do not know how other SQL engines work, but with sqlite you need parenthesis for in statements regardless if they are length 1, so `translate_sql(y %in% "B")` needs parenthesis around "B".

**Comment by hadley** [comment] 2017-01-31 22:48
Duplicate of #511

**Closed by hadley** 2017-01-31 22:48 UTC
