### ISSUE TITLE
SQL translation of "x %in% 1" fails

### ISSUE THREAD

**Issue by zozlak** [hadley/dplyr#982] opened 2015-02-18 08:44 UTC
`sql_translate(x %in% 1)` is `x IN 1`, which is a not valid SQL syntax.
In fact every SQL infix operator which takes a vector of values on the right side and is passed a vector of length 1 is affected by this issue.

This can be solved by changing dplyr::sql_vector() defaults to add parens regarding the length of a vector.

In cases when parens are not needed, this should not break anything (adding parens around single values is valid in SQL, e.g. `(1.0) + (2.0)` is valid) and it will assure that infix operators taking vector on the right side will be properly translated into SQL.

I also reccomend to add a test to test-translate-sql:
```r
out <- translate_sql(x %in% 1)
expect_equal(out, sql('"x" IN (1.0)'))
out <- translate_sql(x %in% 1:2)
expect_equal(out, sql('"x" IN (1.0, 2.0)'))
```

I can prepare a patch but wanted to discuss it before.

**Comment by vzemlys** [comment] 2015-02-18 09:13
Duplicate of #511

**Closed** 2015-05-19 16:20 UTC
