### ISSUE TITLE
mutate ifelse using a list doesn't work

### ISSUE THREAD

**Issue by steadyfish** [hadley/dplyr#1031] opened 2015-03-20 20:27 UTC
`mutate`ing a variable using `ifelse` based on a list range, results in `invalid subscript type 'integer'` error.

```R
# Example:
d = data_frame(a = 1:10,b = 2:11)
l = list(d = d)

# This works -
d2 = d %>% mutate(c = ifelse(a %in% d$b,1,0)) #works d$b a numeric vector
d2 = d %>% mutate(c = ifelse(a %in% l$d["b"],1,0)) #works l$d["b"] a data.frame

# But this doesn't
d2 = d %>% mutate(c = ifelse(a %in% l$d$b,1,0)) #doesn't work l$d$b is still a numeric vector
# Error in l$d$2:11 : invalid subscript type 'integer'
```

**Comment by steadyfish** [comment] 2015-03-29 23:02
@umyarov I can't see how this issue is related to #464 or # 1036. 

The issue is just that I'm able to reference a `data.frame` column but not when the `data.frame` is a `list` element.

**Comment by hadley** [comment] 2015-05-19 16:07
Duplicate of #1067

**Closed by hadley** 2015-05-19 16:07 UTC
