### ISSUE TITLE
mutate_each_ fails when vars is vector containing strings composed of digits

### ISSUE THREAD

**Issue by holstius** [hadley/dplyr#1401] opened 2015-09-10 17:19 UTC
Example:

    my_data <- data_frame(foo = 1.2, `1990` = 1.3)

    # This fails with "Error: Position must be between 0 and n"
    mutate_each_(my_data, funs(round), "1990")
   
    # But this works
    mutate_each_(my_data, funs(round), list(quote(`1990`)))

    # Both variants will work if you're dealing with "normal" strings (i.e. var names)
    mutate_each_(my_data, funs(round), "foo")
    mutate_each_(my_data, funs(round), list(quote(`foo`)))

Some would say it's best practice to avoid column names that are four-digit strings. Duly noted! But, it's often convenient to `spread` by a column `year` when working with annual data, without having to first (for example) `mutate(year = str_c("Y", year))`.

**Comment by hadley** [comment] 2015-09-10 18:21
This is basically a duplicate of #1392

**Closed by hadley** 2015-09-10 18:21 UTC
