### ISSUE TITLE
please alert when deselecting group_by variable

### ISSUE THREAD

**Issue by mplourde** [hadley/dplyr#1667] opened 2016-02-18 19:33 UTC
Currently nothing happens when you attempt to deselect a column that is part of your group_by:

```{r}
data_frame(a=1:5, b=1:5) %>% group_by(a) %>% select(-a)
# Source: local data frame [5 x 2]
# Groups: a [5]
# 
#       a     b
#   (int) (int)
# 1     1     1
# 2     2     2
# 3     3     3
# 4     4     4
# 5     5     5
```

Could `select` and `select_` raise an error in this situation or at the very least a warning?

**Comment by hadley** [comment] 2016-03-01 14:56
Duplicate of #1511

**Closed by hadley** 2016-03-01 14:56 UTC
