### ISSUE TITLE
dplyr cannot handle data frames with unrecognized types?

### ISSUE THREAD

**Issue by cswarth** [hadley/dplyr#1124] opened 2015-05-05 01:20 UTC
Is it just an inherent limitation that if `dplyr` is to be fast, it has to recognized the type of every column? I **love** dplyr and tidyr and am so surprised when I find something that doesn't work.
This is unfortunate,
```
> files <- c('/etc/hostname', '/missing')
> do.call("file.info", list(unique(files))) %>% filter(!is.na(size))
Error: column 'mode' has unsupported type : octmode
17: stop(list(message = "column 'mode' has unsupported type : octmode", 
        call = NULL, cppstack = NULL))
16: .Call("dplyr_filter_impl", PACKAGE = "dplyr", df, dots)
15: filter_impl(.data, dots)
14: filter_.tbl_df(tbl_df(.data), .dots = dots)
13: filter_(tbl_df(.data), .dots = dots)
12: as.data.frame(filter_(tbl_df(.data), .dots = dots))
11: filter_.data.frame(.data, .dots = lazyeval::lazy_dots(...))
10: filter_(.data, .dots = lazyeval::lazy_dots(...))
9: filter(., !is.na(size))
8: function_list[[k]](value)
7: withVisible(function_list[[k]](value))
6: freduce(value, `_function_list`)
5: `_fseq`(`_lhs`)
4: eval(expr, envir, enclos)
3: eval(quote(`_fseq`(`_lhs`)), env, env)
2: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
1: do.call("file.info", list(unique(files))) %>% filter(!is.na(size))
```

```
> sessionInfo()
R version 3.1.3 (2015-03-09)
Platform: x86_64-unknown-linux-gnu (64-bit)
Running under: Ubuntu 14.04.2 LTS

locale:
 [1] LC_CTYPE=en_US.utf8       LC_NUMERIC=C              LC_TIME=en_US.utf8        LC_COLLATE=en_US.utf8     LC_MONETARY=en_US.utf8    LC_MESSAGES=en_US.utf8   
 [7] LC_PAPER=en_US.utf8       LC_NAME=C                 LC_ADDRESS=C              LC_TELEPHONE=C            LC_MEASUREMENT=en_US.utf8 LC_IDENTIFICATION=C      

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.4.1    optparse_1.3.0 gsubfn_0.6-6   proto_0.3-10   ape_3.2       

loaded via a namespace (and not attached):
 [1] assertthat_0.1.0.99 compiler_3.1.3      DBI_0.3.1           getopt_1.20.0       grid_3.1.3          lattice_0.20-31     lazyeval_0.1.10    
 [8] magrittr_1.5        nlme_3.1-120        parallel_3.1.3      R6_2.0.1            Rcpp_0.11.4         tcltk_3.1.3         tools_3.1.3        
```

**Comment by hadley** [comment] 2015-05-05 11:57
Duplicate of #1105

**Closed by hadley** 2015-05-05 11:57 UTC
