### ISSUE TITLE
Will labelled vectors be supported in the future version?

### ISSUE THREAD

**Issue by jjchern** [hadley/dplyr#1149] opened 2015-05-19 21:31 UTC
Will labelled vectors (from the `haven` package) be supported in future versions? I tried the branch `dealing-custom-classes `, but it's still not working at the moment.

```r
# Data frame example

var = rnorm(10)
female = rbinom(n = 10, 1, prob = 0.5)
married = rbinom(n = 10, 1, prob = 0.5)
df = data_frame(var, female, married)

df %>% filter(female == 1) # it works

df %>% # it works
  group_by(female, married) %>% 
  summarize(avg = mean(var))

# Data frame with labelled vectors
library(haven)
female = labelled(female, c(Female = 1L, Male = 0L))
married = labelled(married, c(Married = 1L, Unmarried = 0L))
df = data_frame(var, female, married)

df %>% filter(female == 1) # unsupported type: labelled

df %>% # unsupported type: labelled
  group_by(female, married) %>% 
  summarize(avg = mean(var))
```

**Comment by hadley** [comment] 2015-05-19 21:33
Duplicate of #1105

**Closed by hadley** 2015-05-19 21:33 UTC
