### ISSUE TITLE
Fatal error using mutate w/ floor_date

### ISSUE THREAD

**Issue by kurtosis-color** [hadley/dplyr#1324] opened 2015-08-16 23:21 UTC
Rstudio is giving me "R Session Aborted / R encountered a fatal error" when I run the following. It is loading a table w/ 1800 rows and 6 POSIXct columns, with several missing values. However, it runs successfully under various modifications:

- Running `install.packages("dplyr")` at the start of a session causes it to succeed, but not in future sessions.

- Splitting it into multiple mutate calls succeeds.

- Taking only a subset of rows in date_test makes it less likely to fail, but not in any reproducible way. (Does not seem to be due to a specific row)

```
library(dplyr)
library(lubridate)

date_test = read.table("./dates_test.tsv", header=T, sep="\t", colClasses="POSIXct")

date_test=mutate(date_test,
                week_1 = floor_date(date_1, "week"),
                week_2 = floor_date(date_2, "week"),
                week_3 = floor_date(date_3, "week"),
                week_4 = floor_date(date_4, "week"),
                week_5 = floor_date(date_5, "week"),
                week_6 = floor_date(date_6, "week")
                )
```
I'm running RStudio Version 0.99.660 on OS X Yosemite.
```
> sessionInfo()
R version 3.2.1 (2015-06-18)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.4 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lubridate_1.3.3 dplyr_0.4.2    

loaded via a namespace (and not attached):
 [1] plyr_1.8.3     magrittr_1.5   R6_2.1.0       assertthat_0.1 parallel_3.2.1
 [6] DBI_0.3.1      tools_3.2.1    memoise_0.2.1  Rcpp_0.12.0    stringi_0.5-5 
[11] digest_0.6.8   stringr_1.0.0 
```

**Comment by romainfrancois** [comment] 2015-08-17 15:57
We don't have `"./dates_test.tsv"` but this looks like another version of the infamous `mutate` that has already been fixed in dev. 

Can you try the dev version and reopen if you still can reproduce the problem ?

**Closed by romainfrancois** 2015-08-17 15:57 UTC
