### ISSUE TITLE
joins with non-standard characters

### ISSUE THREAD

**Issue by MansMeg** [hadley/dplyr#2210] opened 2016-10-27 13:35 UTC
I realized that if I join two tables by a character vector with non-standard characters (Swedish letters in my case) and the encoding is not set similar they do not match in the final table. I guess there should be a warning that this can happen or an assertion that only basic characters can be used in a merge (probably the safest choice).

**Comment by krlmlr** [comment] 2016-11-07 14:47
Thanks. We're working on providing better warning mechanisms. In general, column data should always be UTF-8 encoded, but column *names* should be in the native encoding (which is always different on Windows, and may be different on other systems, too).

**Comment by krlmlr** [comment] 2016-11-08 07:14
Closing, duplicate of #1885.

**Closed by krlmlr** 2016-11-08 07:14 UTC
Labels: bug, data frame
