### ISSUE TITLE
Factor ordering removed by summarise

### ISSUE THREAD

**Issue by seanmullane** [hadley/dplyr#2565] opened 2017-03-23 18:18 UTC
I have a tbl_df that includes ordered factors. I am performing a group_by %>% summarise %>% ungroup operation to find the max level of each of these factors within certain groups. The tbl_df that results from this operation has the Ord.factor variables converted to unordered factors. I wish to preserve these as Ord.factors.

This was tested in dplyr 0.5.0

```r
library(dplyr)

d.iris <- tbl_df(iris)

# Reorder d.iris so that max operation in later steps produces varied results
set.seed(13)
d.iris <- sample_n(d.iris, size = 150, replace = T)

factor_levels <- unique(d.iris$Species)
factor_levels <- factor_levels[order(factor_levels)]

# Create grouping variables and make Species an ordered factor
d.iris <- mutate(d.iris, Species = factor(Species, levels = factor_levels, ordered = T),
                 rn = row_number(),
                 dummy_group1 = rn %% 10,
                 dummy_group2 = rn %% 30)

str(d.iris)

# After this operation, Species is no longer ordered
d.iris2 <- group_by(d.iris, dummy_group1, dummy_group2) %>%
  summarise(Species = max(Species)) %>%
  ungroup

str(d.iris2)

# This operation produces error
d.iris3 <- group_by(d.iris2, dummy_group1) %>%
  summarise(Species = max(Species)) %>%
  ungroup
```

**Comment by hadley** [comment] 2017-03-23 18:25
Duplicate of #2200

**Closed by hadley** 2017-03-23 18:25 UTC
