### ISSUE TITLE
order_by/arrange with multiple variables in window function

### ISSUE THREAD

**Issue by philippechataignon** [hadley/dplyr#1656] opened 2016-02-05 12:53 UTC
```r
tbl(kpc, 'jgt') %>% 
  group_by(pev_id)  %>% 
  arrange(mes_critere, inf_critere) %>% 
  mutate(ordre=row_number()) %>% sql
```

leads to 

```r
(...)
row_number() OVER (PARTITION BY "pev_id" ORDER BY ("mes_critere", "inf_critere")) AS "ordre"
(...)
```

Idem when using `order_by` in `mutate`.

With [Netezza](https://github.com/philippechataignon/dplyrnz) , this syntax is incorrect and must be :
`row_number() OVER (PARTITION BY "pev_id" ORDER BY "mes_critere", "inf_critere") AS "ordre"`

Both syntax are admitted by Postgresql but the last is in the documentation and I don't think parentheses are in the standard.

Proposed patch:

```
--- a/R/over.R
+++ b/R/over.R
@@ -12,7 +12,7 @@ over <- function(expr, partition = NULL, order = NULL, frame = NULL) {
       sql_vector(partition, collapse = ", "))
   }
   if (!is.null(order)) {
-    order <- build_sql("ORDER BY ", sql_vector(order, collapse = ", "))
+    order <- build_sql("ORDER BY ", sql_vector(order, collapse = ", ", parens=F))
   }
   if (!is.null(frame)) {
     if (is.numeric(frame)) frame <- rows(frame[1], frame[2])

**Comment by hadley** [comment] 2016-03-10 17:05
Duplicate of #1060

**Closed by hadley** 2016-03-10 17:05 UTC
Labels: bug, database
