### ISSUE TITLE
Consider adding a ``drop'' rows operation 

### ISSUE THREAD

**Issue by kendonB** [hadley/dplyr#1527] opened 2015-11-11 23:57 UTC
I know that ``filter`` can easily achieve this, but it is error prone when there are ``NA`` values.

Dropping using ``filter(!condition)`` drops ``NA``s but ``drop(condition)`` would keep them.

Hope this helps.

**Comment by krlmlr** [comment] 2015-11-12 14:21
Something like `drop()` has been discussed in #741. You could write a tiny helper that achieves this effect.

**Comment by hadley** [comment] 2016-03-01 15:48
Duplicate of #741

**Closed by hadley** 2016-03-01 15:48 UTC
