### ISSUE TITLE
wrong result when trying to join by columns with different character encoding

### ISSUE THREAD

**Issue by mgacc0** [hadley/dplyr#2111] opened 2016-09-06 17:08 UTC
It seems that, when joining data.frames (or tibbles),
the comparison of key columns should previously convert the character strings to a common encoding:

``` r
    df1 <- data_frame(tipo  = c("Física", "Psíquica", "Sensorial"),
                         n_Ben = c(13, 5, 3))
    df2 <- df1

    df1$tipo <- iconv(df2$tipo, to="UTF-8")
    Encoding(df1$tipo)
    # [1] "UTF-8"   "UTF-8"   "unknown"
    Encoding(df2$tipo)
    # [1] "latin1"  "latin1"  "unknown"
    all.equal(df1$tipo, df2$tipo)
    # [1] TRUE

    merge(df1, df2)
    #        tipo n_Ben
    #1    Física    13
    #2  Psíquica     5
    #3 Sensorial     3
```

But `inner_join` gives a wrong result:

``` r
    inner_join(df1, df2)
    # Joining, by = c("tipo", "n_Ben")
    # # A tibble: 1 × 2
    #        tipo n_Ben
    #       <chr> <dbl>
    #1 Sensorial     3
```

If we convert implicitly the columns to UTF-8 before the join operation, the result is correct.
For example:

``` r
    inner_join(df1 %>%
                 mutate_if(is.character, str_trim),
               df2 %>%
                 mutate_if(is.character, str_trim))
    # Joining, by = c("tipo", "n_Ben")
    # # A tibble: 3 × 2
    #        tipo n_Ben
    #       <chr> <dbl>
    #1    Física    13
    #2  Psíquica     5
    #3 Sensorial     3
```

The error happens on Windows (where the default encoding is "latin1"):

``` r
    sessionInfo()
    # R version 3.3.1 (2016-06-21)
    # Platform: x86_64-w64-mingw32/x64 (64-bit)
    # Running under: Windows 7 x64 (build 7601) Service Pack 1
    # 
    # locale:
    # [1] LC_COLLATE=Spanish_Spain.1252  LC_CTYPE=Spanish_Spain.1252    LC_MONETARY=Spanish_Spain.1252 LC_NUMERIC=C                  
    # [5] LC_TIME=Spanish_Spain.1252    
```

But I think it happens on Linux too (where the default is UTF-8) doing the opposite conversion:

``` r
df1$tipo <- iconv(df2$tipo, to="latin1")
```

**Comment by trevorld** [comment] 2016-10-02 20:54
I can confirm this issue also exists on Linux and it seems like  ``base::merge`` doesn't have this issue:

```r
> freq <- read.delim("http://corpus.leeds.ac.uk/frqc/internet-zh.num", skip=4, sep=" ")
> names(freq) <- c("Frequency", "Score", "Hanzi")
> new_words <- data.frame(Hanzi = c("一技之长", "不可或缺", "不懈", "不拘",  "丑陋", "专栏"))
> dplyr::left_join(new_words, freq, by="Hanzi")
     Hanzi Frequency Score
1 一技之长        NA    NA
2 不可或缺        NA    NA
3     不懈        NA    NA
4     不拘        NA    NA
5     丑陋        NA    NA
6     专栏        NA    NA
> base::merge(new_words, freq, by="Hanzi", all.x=TRUE)
     Hanzi Frequency Score
1 一技之长     33466  1.25
2 不可或缺     19771  2.74
3     不懈     18077  3.10
4     不拘     30125  1.47
5     丑陋      9592  7.47
6     专栏      6282 13.06
> dplyr::left_join(new_words, freq %>% mutate_if(is.character, stringr::str_trim), by="Hanzi")
     Hanzi Frequency Score
1 一技之长     33466  1.25
2 不可或缺     19771  2.74
3     不懈     18077  3.10
4     不拘     30125  1.47
5     丑陋      9592  7.47
6     专栏      6282 13.06
> unique(Encoding(freq$Hanzi))
[1] "unknown"
> unique(Encoding(new_words$Hanzi))
[1] "UTF-8"


```

**Comment by uhkeller** [comment] 2016-10-10 12:49
This has been reported multiple times over the last few months (#1885, #1898,  #1998). No fix in sight.

**Comment by krlmlr** [comment] 2016-11-07 22:55
We're working on this problem. For now please ensure that all your character columns are encoded in UTF-8, but all your column names are encoded as "native", which is *not* UTF-8 on Windows.

**Comment by krlmlr** [comment] 2016-11-08 07:14
Closing, duplicate of #1885.

**Closed by krlmlr** 2016-11-08 07:14 UTC
