### ISSUE TITLE
Unable to Access PostgreSQL tables because there's no way to unquote without parentheses

### ISSUE THREAD

**Issue by pourzanj** [hadley/dplyr#2538] opened 2017-03-17 15:34 UTC
I'm able to connect to my PostgreSQL server and see all the tables just fine:

```r
> sp <- src_postgres(dbname = "mimic", host = "127.0.0.1", user = "mimic", password = "****")
> sp
#src:  postgres 9.3.16 [mimic@127.0.0.1:5432/mimic]
#tbls: admissions, callout, caregivers, chartevents, chartevents_1, chartevents_10, chartevents_11, #chartevents_12, chartevents_13,
#  chartevents_14, chartevents_2, chartevents_3, chartevents_4, chartevents_5, chartevents_6, #chartevents_7, chartevents_8, chartevents_9,
#  cptevents, datetimeevents, d_cpt, diagnoses_icd, d_icd_diagnoses, d_icd_procedures, d_items, #d_labitems, drgcodes, icustays, inputevents_cv,
#  inputevents_mv, labevents, microbiologyevents, noteevents, outputevents, patients, prescriptions, #procedureevents_mv, procedures_icd,
#  services, transfers
```
When I'm connected to PostgreSQL in my terminal I'm able to access these tables, but only if they are unquoted with no parentheses e.g.

```bash
#WORKS
SELECT COUNT(*) FROM mimiciii.admissions;

#DOES NOT WORK
SELECT COUNT(*) FROM (mimiciii.admissions);
SELECT COUNT(*) FROM "mimiciii.admissions";
```

I can't access my tables in R, because R will not remove both the quotes and parentheses

```r
MimicPostgre <- tbl(sp, "mimiciii.admissions")
#Error in postgresqlExecStatement(conn, statement, ...) : 
#  RS-DBI driver: (could not Retrieve the result : ERROR:  relation "mimiciii.admissions" does not #exist
#LINE 1: SELECT * FROM "mimiciii.admissions" AS "zzz22" WHERE 0=1
#                      ^
#)

MimicPostgre <- tbl(sp, escape(sql("mimiciii.admissions")))
#Error in postgresqlExecStatement(conn, statement, ...) : 
#  RS-DBI driver: (could not Retrieve the result : ERROR:  syntax error at or near ")"
#LINE 1: SELECT * FROM (mimiciii.admissions) "zzz21" WHERE 0=1
#                                          ^
#)

MimicPostgre <- tbl(sp, escape(sql("mimiciii.admissions"), paren = FALSE))
#Error in postgresqlExecStatement(conn, statement, ...) : 
#  RS-DBI driver: (could not Retrieve the result : ERROR:  syntax error at or near ")"
#LINE 1: SELECT * FROM (mimiciii.admissions) "zzz23" WHERE 0=1
#                                          ^
#)
```

**Comment by hadley** [comment] 2017-03-22 13:12
Duplicate of #244, and hence https://github.com/rstats-db/DBI/issues/24

**Closed by hadley** 2017-03-22 13:12 UTC

**Comment by hadley** [comment] 2017-03-22 13:13
For now, you can work around with a full sql query: `sql("SELECT * FROM mimiciii.admissions")`
