### ISSUE TITLE
mutate_each/summarise_each output inconsistent names

### ISSUE THREAD

**Issue by edwindj** [hadley/dplyr#1173] opened 2015-05-27 11:41 UTC
Calling `summarise_each` (and `mutate_each`) with one named function, the name of the function
is ignored. (It is I think a `colwise_` issue).

```R
iris %>% summarise_each(funs(m1 = min, m2 = max), 1:2) %>% names 
# "Sepal.Length_m1" "Sepal.Width_m1"  "Sepal.Length_m2" "Sepal.Width_m2"

iris %>% summarise_each(funs(m1 = min), 1:2) %>% names  
# "Sepal.Length" "Sepal.Width"
```
I was expecting  "Sepal.Length_m1", "Sepal.Width_m1".

**Comment by docendodiscimus** [comment] 2015-12-26 17:55
IMO, It would also be a helpful enhancement if there was a more standardized way for `mutate_each` to specify if the original columns shall be kept (as is currently the case when applying 2 or more functions in `mutate_each`) or to modify the existing columns (as is currently the case when applying only 1 function in `mutate_each`). For example, I recently discovered that one way to create new/additional columns when only applying 1 function in `mutate_each` is when you supply a named vector of variables to `mutate_each_` (as described in https://stackoverflow.com/questions/27027347/mutate-each-summarise-each-in-dplyr-how-do-i-select-certain-columns-and-give/27027681#27027681 option a.4).

**Comment by hadley** [comment] 2016-03-07 22:09
Duplicate of #442

**Closed by hadley** 2016-03-07 22:09 UTC
Labels: enhancement
