### ISSUE TITLE
Warning messages: Unknown column 'XYZ' 

### ISSUE THREAD

**Issue by codingbutstillalive** [hadley/dplyr#2396] opened 2017-01-31 13:31 UTC
I once used add_column to add a new column to my data frame, something along the line of:

```
dat <- dat %>% add_column(QUARTAL=rep(NA, nrow(dat)))
dat$QUARTAL[dat$MONTH %in% 1:3] <- "Q1"
dat$QUARTAL[dat$MONTH %in% 4:6] <- "Q2"
dat$QUARTAL[dat$MONTH %in% 7:9] <- "Q3"
dat$QUARTAL[dat$MONTH %in% 10:12] <- "Q4"

dat$QUARTAL <- as.factor(dat$QUARTAL)
```

Since then, every now and then I get warning messages "Unknown column 'QUARTAL'". Those appear arbitrarily upon invoking commands, not only when issuing the add_column command. I have no clue why.

I already cleared up the whole environment and tried to reset the cache of latest warnings like this:

`assign("last.warning", NULL, envir = baseenv())`

Nothing helps.

**Comment by hadley** [comment] 2017-01-31 22:50
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](https://github.com/jennybc/reprex#what-is-a-reprex)", and follow the advice further down the page.

**Comment by adisarid** [comment] 2017-02-02 19:09
Hi Hadley,
I encountered the same thing just now. It's extremely weird and really hard to reproduce.
This issue "sticks like a gum", even when the environment is cleaned and Rstudio restarted.

I tried reproducing with iris, it's hard to know if I was able to reproduce the bug with it, because I'm still getting warning messages relating to the original dataset I used and not to the new one.
You can try something along the lines of:

data(iris)
iris.tibble <- as_data_frame(iris)
iris.tibble$Sepal.Length.str[iris.tibble$Sepal.Length >= 5] <- "Above 5"
iris.tibble$Sepal.Length.str[iris.tibble$Sepal.Length < 5] <- "Under 5"


Maybe this will do the trick to reproduce the bug. No guarantees though...

I think it's related to the following thread in stackoverflow (which is also unresolved):
http://stackoverflow.com/questions/39041115/fixing-a-multiple-warning-unknown-column
There are some additional examples at that thread.

**Comment by codingbutstillalive** [comment] 2017-02-02 19:15
@adisarid Thanks for you assist, I hadn't had time to figure out a reprex, unfortunately. Your guys are great, thanks so much, also Hadley!

**Comment by hadley** [comment] 2017-02-02 19:31
I don't see the warning, unfortunately.

**Comment by adisarid** [comment] 2017-02-02 20:30
@hadley Did you check the stackoverflow thread?
http://stackoverflow.com/questions/39041115/fixing-a-multiple-warning-unknown-column

**Comment by hadley** [comment] 2017-02-02 20:31
@adisarid none of those are a standalone reprex, but I did try and couldn't see the problem.

**Comment by zeehio** [comment] 2017-02-15 15:37
This issue has been dealt at https://github.com/tidyverse/tibble/issues/199.

I suffered this warning but I don't get it anymore. Probably it has been addressed by the development tibble version. In any case the suggested approach is to initialize the column:

```r
data(iris)
iris.tibble <- as_data_frame(iris)
iris.tibble$Sepal.Length.str <- NA # Add this line
iris.tibble$Sepal.Length.str[iris.tibble$Sepal.Length >= 5] <- "Above 5"
iris.tibble$Sepal.Length.str[iris.tibble$Sepal.Length < 5] <- "Under 5"
```

**Closed** 2017-02-15 15:58 UTC
Labels: reprex

**Comment by zeehio** [comment] 2017-03-01 14:26
@adisarid  @codingbutstillalive If you still get these warnings try to add

```r
# !diagnostics off
```
as the first line in the source code file. Save the file. And try to see if it appears again. There seems to be a bug in Rstudio code diagnostics. I just reported it.

https://support.rstudio.com/hc/en-us/community/posts/115001180488-Diagnostics-and-tibble-warning

Now we can guess that @hadley codes without all the RStudio diagnostics enabled, because if anyone can code without diagnostics is him. :stuck_out_tongue_closed_eyes:

**Comment by adisarid** [comment] 2017-03-01 20:35
Thanks @zeehio !
I was able to avoid these by using something similar to your previous suggestion.
Finally this makes sense to me... I knew something was weird because I was getting the errors even before running the related code in the script. So I knew it wasn't an error in the code itself which was generating these errors. I didn't know that RStudio has code diagnostics like these. 
Thnx.

**Comment by zeehio** [comment] 2017-03-09 18:02
@adisarid, as you may have seen [here (stackoverflow)](http://stackoverflow.com/a/42536153/446149) this issue has been addressed today at https://github.com/rstudio/rstudio/commit/bcad791aa3500db24aacdbf60effc1cdfae4be5d so it won't affect you in RStudio v1.1.103 or newer (as far as I know that version is not yet published at the RStudio Preview page).

**Comment by Ninoninoninonino** [comment] 2017-06-25 17:03
I had the problem with the unknown column as well.
Converting Tibble back to Dataframe and then using Mutate worked for me.
