### ISSUE TITLE
Allow mutate_if to work with new types

### ISSUE THREAD

**Issue by thomasp85** [hadley/dplyr#2506] opened 2017-03-08 13:46 UTC
As part of my work on tidygraph I've ran into problems with `mutate_if`. While `mutate_all` and `mutate_at` works as long as `mutate_`, `groups`, and `tbl_vars` methods have been defined for the new class, `mutate_if` throws an error.

The problem lies in `dplyr:::probe_colwise_names` that uses `vapply` to apply the predicate to each column. `vapply` is called on the original data (in my case an `igraph` object) yielding the problem.

Possible solutions:

1. Call as.data.frame (or similar) on the data before it is passed to vapply
2. make either `mutate_if` or `probe_colwise_names` generics

Solution one would be the easiest to implement and I cannot see any regressions doing this - I'll be happy to make the PR if you agree this should be changed

**Comment by hadley** [comment] 2017-03-08 18:04
Duplicate of #2129

**Closed by hadley** 2017-03-08 18:04 UTC
