### ISSUE TITLE
mutate_impl doesn't drop last group

### ISSUE THREAD

**Issue by abicky** [hadley/dplyr#1121] opened 2015-05-04 17:14 UTC
`mutate_impl` doesn't drop the last group and the results are different between data.frame and data.table as you can see below:

```r
> packageVersion("dplyr")
[1] ‘0.4.1’
> df <- data.frame(a = c(1, 2, 2), b = 1:3)
> df %>% group_by(a) %>% mutate(min_b = min(b)) %>% summarize(n())
Source: local data frame [2 x 2]

  a n()
1 1   1
2 2   2
> as.data.table(df) %>% group_by(a) %>% mutate(min_b = min(b)) %>% summarize(n())
Source: local data table [1 x 1]

  n()
1   3
```

**Comment by hadley** [comment] 2015-05-19 15:26
It's not supposed to drop the last group.  The problem is that `mutate.data.table` does:

```R
df <- data.frame(a = c(1, 2, 2), b = 1:3)
tbl_dt(df) %>% 
  group_by(a) %>% 
  mutate(min_b = min(b)) %>% 
  groups()
```

**Comment by hadley** [comment] 2015-05-19 18:27
Duplicate of #919

**Closed by hadley** 2015-05-19 18:27 UTC
