### ISSUE TITLE
%in% operator doesn't work for a single value (when translating to SQLite query)

### ISSUE THREAD

**Issue by cpsievert** [hadley/dplyr#1466] opened 2015-10-22 02:10 UTC
```r
library(dplyr)
db <- src_sqlite("mtcars.sqlite3", create = T)
copy_to(db, mtcars)
tbl(db, "mtcars") %>%
  filter(cyl %in% 4)
#> Error in sqliteSendQuery(con, statement, bind.data) : 
#> error in statement: near "4.0": syntax error
```

This works fine however

```r
tbl(db, "mtcars") %>%
  filter(cyl %in% c(4, 6))
```

```r
session_info()
#> Session info -----------------------------------------------------------
#>   setting  value                       
#> version  R version 3.2.2 (2015-08-14)
#> system   x86_64, darwin13.4.0        
#> ui       RStudio (0.99.732)          
#> language (EN)                        
#> collate  en_US.UTF-8                 
#> tz       Australia/Melbourne         
#> date     2015-10-22                  
#> 
#> Packages ---------------------------------------------------------------
#>   package    * version date       source        
#> assertthat   0.1     2013-12-06 CRAN (R 3.2.0)
#> DBI          0.3.1   2014-09-24 CRAN (R 3.2.0)
#> devtools   * 1.9.1   2015-09-11 CRAN (R 3.2.0)
#> digest       0.6.8   2014-12-31 CRAN (R 3.2.0)
#> dplyr      * 0.4.3   2015-09-01 CRAN (R 3.2.0)
#> fortunes     1.5-2   2013-12-14 CRAN (R 3.2.0)
#> lazyeval     0.1.10  2015-01-02 CRAN (R 3.2.0)
#> magrittr     1.5     2014-11-22 CRAN (R 3.2.0)
#> memoise      0.2.1   2014-04-22 CRAN (R 3.2.0)
#> R6           2.1.1   2015-08-19 CRAN (R 3.2.0)
#> Rcpp         0.12.1  2015-09-10 CRAN (R 3.2.0)
#> RSQLite      1.0.0   2014-10-25 CRAN (R 3.2.0)
```

**Comment by hadley** [comment] 2015-10-22 13:05
Duplicate of a really old bug (will try again for this release)

**Closed by hadley** 2015-10-22 13:05 UTC
