### ISSUE TITLE
mutate_each does not always create new columns

### ISSUE THREAD

**Issue by matthieugomez** [hadley/dplyr#712] opened 2014-10-21 20:18 UTC
When more than one function is specifed in `fun`, `mutate_each` adds new columns to the dataset. 

However, when only one function is specified in `fun`, `mutate_each` *does not add* new columns. I find this puzzling

````R
df <- data.frame(
       v1 = sample(5, 10 , replace = TRUE)
)

# Output has 3 columns in both cases
df %>% mutate(v1_mean=mean(v1), v1_sd = sd(v1))
df %>% mutate_each(funs(mean, sd))

 # Output has 2 columns in the first case, and 1 in the second case.
df %>% mutate(v1_mean=mean(v1))
df %>% mutate_each(funs(mean))  
````

More importantly, I could no find an easy way to add a set of variables to an existing data.frame using `mutate_each` and one function. I tried to rename the function `mean` to force a new name for the variables output by `mutate_each` but this did not work:

````R
df %>% mutate_each(funs(mean = mean))
````
I think this would be an easy work around. Another way would be to always name variables output by `mutate_each` with a suffix (but this may break existing code)

A user example is to add new columns corresponding to all lagged variables in a dataset

**Comment by hadley** [comment] 2016-03-07 22:10
Duplicate of #442

**Closed by hadley** 2016-03-07 22:10 UTC
Labels: data frame, enhancement
