### ISSUE TITLE
Working with large database tables *much* slower with 0.4.3.9000

### ISSUE THREAD

**Issue by iangow** [hadley/dplyr#1872] opened 2016-05-31 20:10 UTC
Suppose `some_table` is a table in PostgreSQL with several gigabytes of data. Code like the following is superfast in `dplyr` version `0.4.3`, but very slow in `dplyr` version `0.4.3.9001`. It seems that something is causing the running of a query that materializes the whole table somehow (though it's not clear where it's being put).

```r
library(dplyr)
pg <- src_postgres()
some_table <- tbl(pg, sql("SELECT * FROM some_table"))

some_table %>%
    mutate(new_var=some_function(some_field)) %>%
    print(n=100)
```

This breaks a pretty snazzy workflow in which data tables are built up in R with little concern for the size of the underlying tables (in straight-up SQL, `LIMIT` might be used to similar effect).

I have confirmed that reverting to `dplyr` version `0.4.3` solves the issue (no other changes). It is hard to spot any difference in the generated SQL based on the output of `explain()`. And it is difficult to supply a minimal reproducible example given the "several gigabytes of data" dimension.

Is this a known issue?

**Comment by hadley** [comment] 2016-06-07 21:12
Duplicate of #1725

**Closed by hadley** 2016-06-07 21:12 UTC
