### ISSUE TITLE
Duplicate column after SQL join with different columns

### ISSUE THREAD

**Issue by krlmlr** [hadley/dplyr#2331] opened 2016-12-17 21:20 UTC
```r
left_join(memdb_frame(a=1), memdb_frame(b=1), by = c("a" = "b"))
## Source:   query [?? x 1]
## Database: sqlite 3.11.1 [:memory:]
## 
##       a     b
##   <dbl> <dbl>
## 1     1     1
left_join(data_frame(a=1), data_frame(b=1), by = c("a" = "b"))
## # A tibble: 1 × 1
##       a
##   <dbl>
## 1     1
```

@hadley: Fixing this may break users' scripts. Shall we anyway?

**Comment by hadley** [comment] 2017-02-20 17:05
Duplicate of #2410.

**Closed by hadley** 2017-02-20 17:05 UTC
Labels: database
