### ISSUE TITLE
mutate_tbl.sql doesn't support in-place renaming

### ISSUE THREAD

**Issue by jarodmeng** [hadley/dplyr#1503] opened 2015-11-03 18:28 UTC
mutate_.tbl_sql combines new input with all previous select ([here](https://github.com/hadley/dplyr/blob/dd10ccd543a2bea99573e6622b46d50f657b0c1f/R/tbl-sql.r#L339)). If any input element has the same name as any original column, it will result in duplicated column name error in SQL.

This behavior is also different from mutate_.tbl_df.

**Comment by hadley** [comment] 2015-11-03 23:19
Duplicate of #1000

**Closed by hadley** 2015-11-03 23:19 UTC

**Comment by jarodmeng** [comment] 2015-11-04 05:47
I don't think this is a duplicate issue of #1000.

Perhaps an example will help. The following command fails in MySQL.

```r
> remote_iris <- copy_to(my_db, iris)
> remote_iris %>% mutate(Petal.Width = Petal.Width * 10L)
Source: mysql 5.7.9 [...]
Error in .local(conn, statement, ...) : 
  could not run statement: Duplicate column name 'Petal.Width'
```

The reason is that [this line of code](https://github.com/hadley/dplyr/blob/dd10ccd543a2bea99573e6622b46d50f657b0c1f/R/tbl-sql.r#L339) combines the old select directly with the new input without considering the possibility that some new inputs might have the same names with the old select names.

Changing it to
```r
new <- update(.data, select = c(setdiff(.data$select, names(input), input))
```
should solve the problem?

**Comment by hadley** [comment] 2015-11-04 13:23
Yes, it really needs an additional subquery in there for other reasons, and I'm pretty sure it will also fix this problem.

**Comment by jarodmeng** [comment] 2015-11-04 19:38
How does subquery help if there's only one mutate transformation? I'm basically trying to do some transformation on an existing column and assign the transformed value back to the original column name. `mutate` is failing because now the select statement includes two columns with the same name.

Here I assign the mutate result to `x` and print out the SQL statement for `x`. You can see that two columns now have the name `Petal.Width` and that's causing the error.

```r
> x <- remote_iris %>% mutate(Petal.Width = Petal.Width * 10L)
> x$query$sql
<SQL> SELECT `Sepal.Length`, `Sepal.Width`, `Petal.Length`, `Petal.Width`, `Species`, `Petal.Width` * 10 AS `Petal.Width`
FROM `iris`
```

I don't see how wrapping this query into a subquery would help fix this issue. What would the wrapped query look like?

**Comment by krlmlr** [comment] 2015-11-04 20:01
Something like this, I guess:

```
SELECT Petal.Width * 10 AS Petal.Width FROM (SELECT * FROM iris)
```

To me, it looks like doing each step in a subquery solves the issue you're having, plus many others. The SQL engine will probably optimize those subqueries away most of the time.

**Comment by jarodmeng** [comment] 2015-11-04 20:11
@krlmlr It's no different than `SELECT Petal.Width * 10 AS Petal.Width FROM iris`. The problem is not about creating the select statement. `mutate` generates the right select statement `[SELECT] Petal.Width * 10 AS Petal.Width`. The issue is that it also merges the old select statements. In this case, all columns from `iris` which include the original `Petal.Width` column.

Basically `mutate` will create something like `SELECT *, Petal.Width * 10 AS Petal.Width FROM (SELECT * FROM iris)` which will still cause the error because `Petal.Width` is still included in the `*` operator.

**Comment by krlmlr** [comment] 2015-11-04 20:15
There are more complicated examples than yours, in all of which a subquery will simply work as expected, while generating a shorter SQL expression may be far from trivial or even impossible. SQL code generation is *not* about producing short or nice or even human-readable SQL, it's about working reliably in all cases.

**Comment by krlmlr** [comment] 2015-11-04 20:17
For starters:

```
iris %>% mutate(Petal.Width = Petal.Width + 2, Petal.Width = Petal.Width * Petal.Width)
```

**Comment by jarodmeng** [comment] 2015-11-04 20:28
@krlmlr I'm not trying to generate a shorter SQL expression, but a working one. The current one is *not* working and I'm not convinced that wrapping a subquery around it would fix the issue. I'm certainly open to ideas on how to fix the problem.

The fact that in-place renaming works for data frames, but not databases is exactly the problem I'm trying to find a solution here.

**Comment by krlmlr** [comment] 2015-11-04 20:40
I'm pretty sure that the one I showed earlier works, at least on Postgres. (Other engines might have a different syntax.)

https://github.com/hadley/dplyr/issues/1503#issuecomment-153846891

It looks like the idea behind #1000 is to employ this pattern for *each* mutated variable, that is, each mutated variable will get its own subquery. My double-mutation example above will therefore translate to sth like

```
SELECT Petal.Width * Petal.Width AS Petal.Width FROM (SELECT Petal.Width + 2 AS Petal.Width FROM (SELECT * FROM iris) iris1) iris2)
```

**Comment by einarhjorleifsson** [comment] 2015-11-04 20:48
is the above issue related to the issue below (intuitively i expect that all the code provided should lead to the same result - which they do not):

```
library(dplyr)
library(RPostgreSQL)
# connect to a database
ram <- src_postgres(dbname = "srdb", 
                    host="nautilus-vm.mathstat.dal.ca", 
                    user ="srdbuser", 
                    password ="srd6us3r!",
                    port = 5432,
                    options="-c search_path=srdb")
tbl(ram, "assessment")
tbl(ram, "assessment") %>%
  filter(stockid == "CODICE")
tbl(ram, "assessment") %>%
  filter(stockid == "CODICE") %>%
  rename(s.id = stockid)
tbl(ram, "assessment") %>%
  rename(s.id = stockid) %>%
  filter(s.id == "CODICE")
```

**Comment by krlmlr** [comment] 2015-11-04 20:58
@einarhjorleifsson: I guess subqueries could help here, too. I think a good way forward would be to create test cases as testthat tests (currently failing); those would be needed anyway. (#1000 is still open, so you might want to link the PR to that issue.)

**Comment by jarodmeng** [comment] 2015-11-05 00:52
@krlmlr I think we're not talking about the same thing here. Your example works because it doesn't select other columns from the table. It would be helpful if you can try to run `db_iris %>% mutate(Petal.Width = Petal.Width * 10L)` in your preferred database to see what happens.

When I tried in postgresql, it generates result, but a wrong one because the previous `Petal.Width` column is *not* replaced. The result now shows the table has two columns with the same name `Petal.Width`. This is confusing because `Petal.Width` is now ambiguous and any subsequent operations on `Petal.Width` cannot resolve to a single column. I'm not sure why PostgreSQL allows this, but it doesn't seem right.

```r
> library(RPostgreSQL)
Loading required package: DBI
> my_postgre <- src_postgres(...)
> postgre_iris <- copy_to(my_postgre, iris)
> postgre_iris %>% mutate(Petal.Width = Petal.Width * 10L)
Source: postgres 9.4.5 [jarodmeng@localhost:5432/jarodmeng]
From: iris [150 x 6]

   Sepal.Length Sepal.Width Petal.Length Petal.Width Species Petal.Width
          (dbl)       (dbl)        (dbl)       (dbl)   (chr)       (dbl)
1           5.1         3.5          1.4         0.2  setosa           2
2           4.9         3.0          1.4         0.2  setosa           2
3           4.7         3.2          1.3         0.2  setosa           2
4           4.6         3.1          1.5         0.2  setosa           2
5           5.0         3.6          1.4         0.2  setosa           2
6           5.4         3.9          1.7         0.4  setosa           4
7           4.6         3.4          1.4         0.3  setosa           3
8           5.0         3.4          1.5         0.2  setosa           2
9           4.4         2.9          1.4         0.2  setosa           2
10          4.9         3.1          1.5         0.1  setosa           1
..          ...         ...          ...         ...     ...         ...
```

**Comment by jarodmeng** [comment] 2015-11-05 00:57
@einarhjorleifsson Implementing subquery for `rename` would work for your last example. But I don't think your issue is the same as the one I'm raising.

Also, you might want to conceal your database host name, user name and password since Github is public. They're not essential in explaining the issue, but could potentially cause harm to you.

**Comment by krlmlr** [comment] 2015-11-05 08:11
@jarodmeng: There's no doubt that the current implementation behaves in unexpected ways. And, of course, my queries were sloppy. I believe the following translation of `remote_iris %>% mutate(Petal.Width = Petal.Width * 10L)` is correct:

```
SELECT Sepal.Length, Sepal.Width, Petal.Length, Petal.Width * 10 AS Petal.Width, Species FROM (SELECT * FROM iris) iris1
```

I also agree that the following is correct as well:

```
SELECT Sepal.Length, Sepal.Width, Petal.Length, Petal.Width * 10 AS Petal.Width, Species FROM iris
```

Subqueries help in more complicated cases like the following:

```
remote_iris %>% mutate(Petal.Width = Petal.Width + 2, Petal.Width = Petal.Width * Petal.Width)
```

BTW, this problem is also mentioned in #1423.

srdb is a public database with published credentials.

**Comment by jarodmeng** [comment] 2015-11-06 01:20
@krlmlr I would certainly love to see subquery implemented for every mutate actions. It would solve quite a few outstanding bugs.

@hadley Can you mark this issue a duplicate of #1423 instead of #1000?

Thanks.
